package catalog

const (
	tryN8nSpecRoot = "../try-n8n/reducibility/specs/"
	n8nNodeRoot    = "../n8n/packages/nodes-base/nodes/"
)

var builtInCandidates = []Candidate{
	workflowCandidate(candidateSeed{
		id:          "activecampaign",
		displayName: "ActiveCampaign",
		aliases:     []string{"activecampaign api", "active campaign"},
		category:    "email-marketing",
		n8nNode:     "ActiveCampaign",
		relevance:   "Popular marketing automation platform for contacts, campaigns, automations, deals, and email workflow automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "action-network",
		displayName: "Action Network",
		aliases:     []string{"action network api", "actionnetwork", "osdi api"},
		category:    "advocacy",
		n8nNode:     "ActionNetwork",
		relevance:   "Popular organizing platform for activists, petitions, events, forms, tags, campaigns, and nonprofit advocacy automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "adalo",
		displayName: "Adalo",
		aliases:     []string{"adalo api", "adalo collections api"},
		category:    "app-builder",
		n8nNode:     "Adalo",
		relevance:   "Popular no-code app builder for application collections, records, and push notification automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "affinity",
		displayName: "Affinity",
		aliases:     []string{"affinity api", "affinity crm api"},
		category:    "crm",
		n8nNode:     "Affinity",
		relevance:   "Popular relationship intelligence CRM for lists, people, organizations, opportunities, interactions, notes, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "agile-crm",
		displayName: "Agile CRM",
		aliases:     []string{"agile crm", "agilecrm", "agilecrm api"},
		category:    "crm",
		n8nNode:     "AgileCrm",
		relevance:   "Popular CRM and marketing automation service for contacts, companies, deals, tasks, events, campaigns, and help desk records.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "asana",
		displayName: "Asana",
		aliases:     []string{"asana api"},
		category:    "project-management",
		n8nNode:     "Asana",
		relevance:   "Popular workflow service for task, project, and work-management automation.",
	}),
	workflowCandidate(candidateSeed{
		id:              "aws-s3",
		displayName:     "AWS S3",
		aliases:         []string{"amazon s3", "aws s3 api", "s3"},
		category:        "cloud-storage",
		n8nNode:         "Aws/S3",
		relevance:       "Popular infrastructure service for object storage, buckets, object metadata, and file automation.",
		machineSpecKind: string(SpecKindSmithyJSON),
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "aws-sns",
		displayName:     "AWS SNS",
		aliases:         []string{"amazon sns", "aws sns api", "sns"},
		category:        "messaging",
		n8nNode:         "Aws/AwsSns",
		relevance:       "Popular infrastructure service for topics, subscriptions, publish operations, SMS, and notification automation.",
		machineSpecKind: string(SpecKindSmithyJSON),
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "aws-lambda",
		displayName:     "AWS Lambda",
		aliases:         []string{"amazon lambda", "aws lambda api", "lambda"},
		category:        "serverless-compute",
		n8nNode:         "Aws/AwsLambda",
		relevance:       "Popular infrastructure service for functions, invocations, event source mappings, aliases, and serverless automation.",
		machineSpecKind: string(SpecKindSmithyJSON),
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "airtable",
		displayName: "Airtable",
		aliases:     []string{"airtable api"},
		category:    "database",
		fixture:     "airtable.json",
		n8nNode:     "Airtable",
		relevance:   "Common workflow source and destination for records in bases and tables.",
	}),
	workflowCandidate(candidateSeed{
		id:          "bamboohr",
		displayName: "BambooHR",
		aliases:     []string{"bamboohr api", "bamboo hr"},
		category:    "hr",
		n8nNode:     "BambooHr",
		relevance:   "Popular HR platform for employee records, reports, time off, and people operations automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "box",
		displayName: "Box",
		aliases:     []string{"box api"},
		category:    "files",
		n8nNode:     "Box",
		relevance:   "Popular workflow service for file storage, sharing, and content-management automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "bannerbear",
		displayName: "Bannerbear",
		aliases:     []string{"bannerbear api", "bannerbear image api"},
		category:    "media-generation",
		n8nNode:     "Bannerbear",
		relevance:   "Popular media automation service for generated images, videos, PDFs, screenshots, templates, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "baserow",
		displayName: "Baserow",
		aliases:     []string{"baserow api", "baserow database api"},
		category:    "database",
		n8nNode:     "Baserow",
		relevance:   "Popular open-source database platform for workspaces, databases, tables, fields, rows, views, and automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "beeminder",
		displayName: "Beeminder",
		aliases:     []string{"beeminder api"},
		category:    "productivity",
		n8nNode:     "Beeminder",
		relevance:   "Popular goal tracking and commitment platform for users, goals, datapoints, charges, and reminder automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "bitbucket",
		displayName: "Bitbucket",
		aliases:     []string{"bitbucket api", "bitbucket cloud"},
		category:    "developer-tools",
		n8nNode:     "Bitbucket",
		relevance:   "Popular developer platform for repositories, pull requests, pipelines, workspaces, and source automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "brandfetch",
		displayName: "Brandfetch",
		aliases:     []string{"brandfetch api", "brand api", "brandfetch brand api"},
		category:    "brand-data",
		n8nNode:     "Brandfetch",
		relevance:   "Popular brand-data API for logos, colors, fonts, images, firmographic information, and personalization automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "calendly",
		displayName: "Calendly",
		aliases:     []string{"calendly api"},
		category:    "scheduling",
		n8nNode:     "Calendly",
		relevance:   "Popular workflow service for scheduling events, invitees, and booking automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "chargebee",
		displayName: "Chargebee",
		aliases:     []string{"chargebee api"},
		category:    "billing",
		n8nNode:     "Chargebee",
		relevance:   "Popular subscription billing platform for customers, subscriptions, invoices, payments, and revenue automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "circleci",
		displayName: "CircleCI",
		aliases:     []string{"circleci api", "circleci v2"},
		category:    "ci-cd",
		n8nNode:     "CircleCi",
		relevance:   "Popular workflow service for pipelines, workflows, jobs, artifacts, contexts, and CI/CD automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "clearbit",
		displayName: "Clearbit",
		aliases:     []string{"clearbit api", "clearbit enrichment api", "clearbit prospector"},
		category:    "data-enrichment",
		n8nNode:     "Clearbit",
		relevance:   "Popular B2B data enrichment platform for person, company, prospecting, reveal, and legacy lookup automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "cloudflare",
		displayName: "Cloudflare",
		aliases:     []string{"cloudflare api"},
		category:    "edge-platform",
		n8nNode:     "Cloudflare",
		relevance:   "Popular infrastructure platform for DNS, zones, caching, security rules, workers, and edge automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "contentful",
		displayName: "Contentful",
		aliases:     []string{"contentful api", "contentful management api"},
		category:    "cms",
		n8nNode:     "Contentful",
		relevance:   "Popular composable content platform for spaces, entries, assets, environments, and publishing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "customer-io",
		displayName: "Customer.io",
		aliases:     []string{"customer.io", "customer.io api", "customerio"},
		category:    "customer-engagement",
		n8nNode:     "CustomerIo",
		relevance:   "Popular customer engagement platform for messaging, journeys, profiles, events, and data pipeline automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "databricks",
		displayName: "Databricks",
		aliases:     []string{"databricks api", "databricks rest api"},
		category:    "data-platform",
		n8nNode:     "Databricks",
		relevance:   "Popular data platform for SQL warehouses, jobs, model serving, Unity Catalog, vector search, and lakehouse automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "clickup",
		displayName: "ClickUp",
		aliases:     []string{"clickup api", "click up"},
		category:    "project-management",
		n8nNode:     "ClickUp",
		relevance:   "Popular workflow service for tasks, lists, spaces, and team work-management automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "discord",
		displayName: "Discord",
		aliases:     []string{"discord api"},
		category:    "messaging",
		n8nNode:     "Discord",
		relevance:   "Popular workflow service for community messaging, channels, and notification automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "discourse",
		displayName: "Discourse",
		aliases:     []string{"discourse api", "discourse forum api"},
		category:    "community",
		n8nNode:     "Discourse",
		relevance:   "Popular community forum platform for topics, posts, categories, users, groups, tags, badges, and moderation automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "dropbox",
		displayName: "Dropbox",
		aliases:     []string{"dropbox api"},
		category:    "files",
		n8nNode:     "Dropbox",
		relevance:   "Popular workflow service for file storage, transfer, and sharing automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "elastic",
		displayName: "Elastic",
		aliases:     []string{"elastic api", "elasticsearch", "elasticsearch api"},
		category:    "search",
		n8nNode:     "Elastic/Elasticsearch",
		relevance:   "Popular search and analytics platform for indices, documents, search, ingest, and security automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "eventbrite",
		displayName: "Eventbrite",
		aliases:     []string{"eventbrite api"},
		category:    "events",
		n8nNode:     "Eventbrite",
		relevance:   "Popular event platform for events, venues, organizations, attendees, orders, and ticketing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "freshdesk",
		displayName: "Freshdesk",
		aliases:     []string{"freshdesk api"},
		category:    "customer-support",
		n8nNode:     "Freshdesk",
		relevance:   "Popular customer support platform for tickets, contacts, companies, agents, and helpdesk automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "freshservice",
		displayName: "Freshservice",
		aliases:     []string{"freshservice api", "freshservice service desk api"},
		category:    "it-service-management",
		n8nNode:     "Freshservice",
		relevance:   "Popular IT service management platform for tickets, problems, changes, releases, requesters, agents, assets, and service catalog automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "gmail",
		displayName:     "Gmail",
		aliases:         []string{"google mail", "gmail api"},
		category:        "email",
		fixture:         "gmail.json",
		n8nNode:         "Google/Gmail",
		relevance:       "Common workflow service for reading, sending, and routing email messages.",
		machineSpecKind: "google-discovery",
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "google-calendar",
		displayName:     "Google Calendar",
		aliases:         []string{"google calendar api", "calendar api"},
		category:        "scheduling",
		n8nNode:         "Google/Calendar",
		relevance:       "Popular workflow service for calendar events, availability, and scheduling automation.",
		machineSpecKind: "google-discovery",
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "google-drive",
		displayName:     "Google Drive",
		aliases:         []string{"drive", "google drive api"},
		category:        "files",
		fixture:         "google_drive.json",
		n8nNode:         "Google/Drive",
		relevance:       "Common workflow service for file storage, upload, search, and sharing.",
		machineSpecKind: "google-discovery",
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "google-sheets",
		displayName:     "Google Sheets",
		aliases:         []string{"sheets", "google sheets api"},
		category:        "spreadsheet",
		n8nNode:         "Google/Sheet",
		relevance:       "Popular workflow service for spreadsheet reads, writes, and tabular-data automation.",
		machineSpecKind: "google-discovery",
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "grafana",
		displayName: "Grafana",
		aliases:     []string{"grafana api", "grafana http api"},
		category:    "observability",
		n8nNode:     "Grafana",
		relevance:   "Popular observability platform for dashboards, folders, data sources, alerting, service accounts, and monitoring automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "grist",
		displayName: "Grist",
		aliases:     []string{"grist api", "grist rest api", "getgrist"},
		category:    "database",
		n8nNode:     "Grist",
		relevance:   "Popular relational spreadsheet platform for organizations, workspaces, documents, tables, records, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "gong",
		displayName: "Gong",
		aliases:     []string{"gong api", "gong public api"},
		category:    "sales",
		n8nNode:     "Gong",
		relevance:   "Popular revenue intelligence platform for calls, users, conversation analytics, transcripts, CRM data, and call-upload automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "github",
		displayName: "GitHub",
		aliases:     []string{"github api"},
		category:    "developer-tools",
		n8nNode:     "Github",
		relevance:   "Popular workflow service for repositories, issues, pull requests, and developer automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "gitlab",
		displayName: "GitLab",
		aliases:     []string{"gitlab api"},
		category:    "developer-tools",
		n8nNode:     "Gitlab",
		relevance:   "Popular workflow service for repositories, issues, merge requests, and DevOps automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "hubspot",
		displayName: "HubSpot",
		aliases:     []string{"hubspot crm", "hubspot api"},
		category:    "crm",
		fixture:     "hubspot.json",
		n8nNode:     "Hubspot",
		relevance:   "Common workflow service for CRM records, tickets, contacts, and pipeline automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "intercom",
		displayName: "Intercom",
		aliases:     []string{"intercom api", "intercom rest api"},
		category:    "customer-support",
		n8nNode:     "Intercom",
		relevance:   "Popular customer messaging and support platform for contacts, conversations, articles, tickets, and help-center automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "jenkins",
		displayName: "Jenkins",
		aliases:     []string{"jenkins api", "jenkins remote api"},
		category:    "ci-cd",
		n8nNode:     "Jenkins",
		relevance:   "Popular automation server for jobs, builds, queues, nodes, artifacts, and CI/CD automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mailchimp",
		displayName: "Mailchimp",
		aliases:     []string{"mailchimp api", "mailchimp marketing"},
		category:    "email-marketing",
		n8nNode:     "Mailchimp",
		relevance:   "Popular workflow service for audiences, contacts, campaigns, templates, reports, and marketing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mailgun",
		displayName: "Mailgun",
		aliases:     []string{"mailgun api"},
		category:    "email",
		n8nNode:     "Mailgun",
		relevance:   "Popular email platform for sending, domains, routes, suppression lists, and deliverability automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "jira-cloud",
		displayName: "Jira Cloud",
		aliases:     []string{"jira", "atlassian jira", "jira api"},
		category:    "project-management",
		fixture:     "jira.json",
		n8nNode:     "Jira",
		relevance:   "Common workflow service for issue tracking and project automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "linear",
		displayName: "Linear",
		aliases:     []string{"linear api", "linear graphql"},
		category:    "project-management",
		n8nNode:     "Linear",
		relevance:   "Popular workflow service for issues, projects, teams, cycles, comments, and product-development automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "microsoft-graph",
		displayName: "Microsoft Graph",
		aliases:     []string{"microsoft graph api", "graph api", "office 365"},
		category:    "productivity",
		n8nNode:     "Microsoft",
		relevance:   "Popular platform API for Microsoft 365 users, files, mail, calendars, and collaboration automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "monday-com",
		displayName: "Monday.com",
		aliases:     []string{"monday api", "monday.com api", "monday graphql"},
		category:    "project-management",
		n8nNode:     "Monday.com",
		relevance:   "Popular workflow service for boards, items, columns, updates, users, files, and work-management automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "netlify",
		displayName: "Netlify",
		aliases:     []string{"netlify api"},
		category:    "hosting",
		n8nNode:     "Netlify",
		relevance:   "Popular web hosting platform for sites, deploys, forms, DNS, hooks, and build automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "nocodb",
		displayName: "NocoDB",
		aliases:     []string{"nocodb api", "noco db"},
		category:    "database",
		n8nNode:     "NocoDB",
		relevance:   "Popular open-source no-code database platform for base, table, record, attachment, and linked-record automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "notion",
		displayName: "Notion",
		aliases:     []string{"notion api"},
		category:    "knowledge-management",
		n8nNode:     "Notion",
		relevance:   "Popular workflow service for pages, databases, and knowledge-base automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "okta",
		displayName: "Okta",
		aliases:     []string{"okta api", "okta management"},
		category:    "identity",
		n8nNode:     "Okta",
		relevance:   "Popular identity platform for users, groups, applications, events, and organization administration automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "openweathermap",
		displayName: "OpenWeatherMap",
		aliases:     []string{"open weather map", "openweathermap api"},
		category:    "weather",
		fixture:     "openweathermap.json",
		n8nNode:     "OpenWeatherMap",
		relevance:   "Common workflow data source for current weather and forecast enrichment.",
	}),
	workflowCandidate(candidateSeed{
		id:          "pagerduty",
		displayName: "PagerDuty",
		aliases:     []string{"pagerduty api"},
		category:    "incident-management",
		fixture:     "pagerduty.json",
		n8nNode:     "PagerDuty",
		relevance:   "Common workflow service for incident, escalation, and on-call automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "postmark",
		displayName: "Postmark",
		aliases:     []string{"postmark api"},
		category:    "email",
		n8nNode:     "Postmark",
		relevance:   "Popular transactional email platform for messages, templates, servers, bounces, and delivery automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "posthog",
		displayName: "PostHog",
		aliases:     []string{"posthog api", "post hog"},
		category:    "product-analytics",
		n8nNode:     "PostHog",
		relevance:   "Popular product analytics platform for event capture, persons, cohorts, feature flags, insights, dashboards, surveys, and data warehouse automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "paypal",
		displayName: "PayPal",
		aliases:     []string{"paypal api", "paypal checkout"},
		category:    "payments",
		n8nNode:     "PayPal",
		relevance:   "Popular payment platform for checkout orders, captures, authorizations, subscriptions, payouts, and transaction automation.",
		userNeed:    UserOpenAPINeedPossible,
	}),
	workflowCandidate(candidateSeed{
		id:          "pipedrive",
		displayName: "Pipedrive",
		aliases:     []string{"pipedrive api", "pipedrive crm"},
		category:    "crm",
		n8nNode:     "Pipedrive",
		relevance:   "Popular CRM workflow service for deals, persons, organizations, activities, leads, products, and pipeline automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "quickbooks",
		displayName: "QuickBooks",
		aliases:     []string{"quickbooks api", "quickbooks online", "intuit quickbooks"},
		category:    "accounting",
		n8nNode:     "QuickBooks",
		relevance:   "Popular accounting platform for invoices, customers, bills, accounts, payments, and bookkeeping automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "salesforce",
		displayName: "Salesforce",
		aliases:     []string{"salesforce api", "salesforce crm"},
		category:    "crm",
		n8nNode:     "Salesforce",
		relevance:   "Popular CRM platform for leads, accounts, opportunities, and customer automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "seatable",
		displayName: "SeaTable",
		aliases:     []string{"seatable api", "sea table"},
		category:    "database",
		n8nNode:     "SeaTable",
		relevance:   "Popular spreadsheet-database platform for bases, rows, columns, files, links, metadata, and team automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "sendgrid",
		displayName: "SendGrid",
		aliases:     []string{"sendgrid api", "twilio sendgrid"},
		category:    "email",
		n8nNode:     "SendGrid",
		relevance:   "Popular workflow service for transactional email, templates, contacts, suppression lists, and email analytics.",
	}),
	workflowCandidate(candidateSeed{
		id:          "sentry",
		displayName: "Sentry",
		aliases:     []string{"sentry api", "sentry.io"},
		category:    "observability",
		n8nNode:     "SentryIo",
		relevance:   "Popular observability service for issues, events, releases, organizations, teams, and error-monitoring automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "servicenow",
		displayName: "ServiceNow",
		aliases:     []string{"servicenow api", "servicenow rest"},
		category:    "it-service-management",
		n8nNode:     "ServiceNow",
		relevance:   "Popular workflow service for incidents, users, tables, service catalog, change records, and ITSM automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "shopify",
		displayName: "Shopify",
		aliases:     []string{"shopify api"},
		category:    "commerce",
		n8nNode:     "Shopify",
		relevance:   "Popular commerce platform for orders, products, customers, and storefront automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "slack",
		displayName: "Slack",
		aliases:     []string{"slack api"},
		category:    "messaging",
		fixture:     "slack.json",
		n8nNode:     "Slack",
		relevance:   "Common workflow service for messages, channels, and collaboration notifications.",
	}),
	workflowCandidate(candidateSeed{
		id:          "snowflake",
		displayName: "Snowflake",
		aliases:     []string{"snowflake api", "snowflake sql api"},
		category:    "data-platform",
		n8nNode:     "Snowflake",
		relevance:   "Popular data platform for SQL statements, warehouses, databases, schemas, tables, and analytics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "splunk",
		displayName: "Splunk",
		aliases:     []string{"splunk api", "splunk rest api"},
		category:    "observability",
		n8nNode:     "Splunk",
		relevance:   "Popular observability platform for searches, jobs, saved searches, alerts, users, and log analytics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "stripe",
		displayName: "Stripe",
		aliases:     []string{"stripe api"},
		category:    "payments",
		n8nNode:     "Stripe",
		relevance:   "Popular payment platform for customers, charges, invoices, subscriptions, and billing automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "supabase",
		displayName: "Supabase",
		aliases:     []string{"supabase api", "supabase management api"},
		category:    "backend-platform",
		n8nNode:     "Supabase",
		relevance:   "Popular backend platform for projects, databases, auth, storage, edge functions, and PostgREST data APIs.",
	}),
	workflowCandidate(candidateSeed{
		id:          "telegram",
		displayName: "Telegram",
		aliases:     []string{"telegram api", "telegram bot api"},
		category:    "messaging",
		n8nNode:     "Telegram",
		relevance:   "Popular messaging workflow service for bot messages, chats, updates, files, callbacks, and notifications.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "trello",
		displayName: "Trello",
		aliases:     []string{"trello api"},
		category:    "project-management",
		fixture:     "trello.json",
		n8nNode:     "Trello",
		relevance:   "Common workflow service for boards, lists, cards, and task automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "twilio",
		displayName: "Twilio",
		aliases:     []string{"twilio api", "twilio sms"},
		category:    "communications",
		n8nNode:     "Twilio",
		relevance:   "Popular workflow service for SMS, voice, messaging, phone numbers, and communication automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "todoist",
		displayName: "Todoist",
		aliases:     []string{"todoist api"},
		category:    "tasks",
		n8nNode:     "Todoist",
		relevance:   "Popular task-management service for tasks, projects, sections, labels, comments, and productivity automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "typeform",
		displayName: "Typeform",
		aliases:     []string{"typeform api"},
		category:    "forms",
		n8nNode:     "Typeform",
		relevance:   "Popular workflow service for forms, responses, webhooks, workspaces, themes, and survey automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "xero",
		displayName: "Xero",
		aliases:     []string{"xero api", "xero accounting"},
		category:    "accounting",
		n8nNode:     "Xero",
		relevance:   "Popular accounting platform for contacts, invoices, bills, payments, bank transactions, and finance automation.",
		userNeed:    UserOpenAPINeedPossible,
	}),
	workflowCandidate(candidateSeed{
		id:          "zoom",
		displayName: "Zoom",
		aliases:     []string{"zoom api", "zoom meetings"},
		category:    "communications",
		n8nNode:     "Zoom",
		relevance:   "Popular workflow service for meetings, webinars, recordings, users, and account automation.",
		userNeed:    UserOpenAPINeedPossible,
	}),
	workflowCandidate(candidateSeed{
		id:          "webflow",
		displayName: "Webflow",
		aliases:     []string{"webflow api", "webflow data api"},
		category:    "website-builder",
		n8nNode:     "Webflow",
		relevance:   "Popular website platform for sites, CMS collections, items, pages, forms, and web publishing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "zendesk",
		displayName: "Zendesk",
		aliases:     []string{"zendesk api", "zendesk support"},
		category:    "customer-support",
		n8nNode:     "Zendesk",
		relevance:   "Popular workflow service for support tickets, users, organizations, messaging, and customer-service automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "acuity-scheduling",
		displayName: "Acuity Scheduling",
		aliases:     []string{"acuity", "acuity api", "acuity scheduling api"},
		category:    "scheduling",
		n8nNode:     "AcuityScheduling",
		relevance:   "Popular scheduling platform for appointments, availability, calendars, clients, and booking automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "bitly",
		displayName: "Bitly",
		aliases:     []string{"bitly api"},
		category:    "link-management",
		n8nNode:     "Bitly",
		relevance:   "Popular link-management service for shortening links, bitlinks, campaigns, groups, QR codes, and click metrics automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "brevo",
		displayName: "Brevo",
		aliases:     []string{"brevo api", "sendinblue"},
		category:    "email-marketing",
		n8nNode:     "Brevo",
		relevance:   "Popular customer messaging platform for contacts, email campaigns, transactional email, SMS, CRM, and marketing automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "clockify",
		displayName: "Clockify",
		aliases:     []string{"clockify api"},
		category:    "time-tracking",
		n8nNode:     "Clockify",
		relevance:   "Popular time-tracking platform for workspaces, projects, tasks, time entries, clients, and reporting automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "coda",
		displayName: "Coda",
		aliases:     []string{"coda api", "coda docs"},
		category:    "productivity",
		n8nNode:     "Coda",
		relevance:   "Popular docs and database platform for docs, pages, tables, rows, formulas, controls, and workspace automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "deepl",
		displayName: "DeepL",
		aliases:     []string{"deepl api", "deepl translate"},
		category:    "translation",
		n8nNode:     "DeepL",
		relevance:   "Popular language AI service for text translation, document translation, glossaries, usage, and language detection automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "figma",
		displayName: "Figma",
		aliases:     []string{"figma api", "figma rest api"},
		category:    "design",
		n8nNode:     "Figma",
		relevance:   "Popular design collaboration platform for files, comments, components, projects, variables, and webhook automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "ghost",
		displayName: "Ghost",
		aliases:     []string{"ghost api", "ghost admin api", "ghost cms"},
		category:    "cms",
		n8nNode:     "Ghost",
		relevance:   "Popular publishing CMS for posts, pages, tags, members, users, newsletters, and content automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "harvest",
		displayName: "Harvest",
		aliases:     []string{"harvest api", "harvestapp"},
		category:    "time-tracking",
		n8nNode:     "Harvest",
		relevance:   "Popular time-tracking and invoicing platform for users, projects, clients, time entries, expenses, and invoices automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "help-scout",
		displayName: "Help Scout",
		aliases:     []string{"helpscout", "help scout api", "helpscout api"},
		category:    "customer-support",
		n8nNode:     "HelpScout",
		relevance:   "Popular customer support platform for conversations, customers, mailboxes, docs articles, collections, and support workflow automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "iterable",
		displayName: "Iterable",
		aliases:     []string{"iterable api"},
		category:    "customer-engagement",
		n8nNode:     "Iterable",
		relevance:   "Popular customer engagement platform for users, events, campaigns, journeys, lists, templates, and messaging automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mailjet",
		displayName: "Mailjet",
		aliases:     []string{"mailjet api"},
		category:    "email",
		n8nNode:     "Mailjet",
		relevance:   "Popular email API platform for transactional sending, contacts, lists, campaigns, templates, and message statistics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "convertkit",
		displayName: "Kit (ConvertKit)",
		aliases:     []string{"convertkit api", "kit api", "kit email api"},
		category:    "email-marketing",
		n8nNode:     "ConvertKit",
		relevance:   "Popular creator marketing platform for subscribers, tags, forms, broadcasts, sequences, purchases, and webhook automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "copper",
		displayName: "Copper",
		aliases:     []string{"copper api", "copper crm", "copper crm api"},
		category:    "crm",
		n8nNode:     "Copper",
		relevance:   "Popular CRM for leads, people, companies, opportunities, projects, tasks, activities, custom fields, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "coingecko",
		displayName: "CoinGecko",
		aliases:     []string{"coingecko api", "coin gecko", "coingecko market data"},
		category:    "crypto-market-data",
		n8nNode:     "CoinGecko",
		relevance:   "Popular crypto market-data API for prices, coins, exchanges, categories, trending assets, and global market automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "hackernews",
		displayName: "Hacker News",
		aliases:     []string{"hacker news", "hackernews api", "hn api"},
		category:    "news",
		n8nNode:     "HackerNews",
		relevance:   "Popular public news data API for stories, items, users, and near-real-time update automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "marketstack",
		displayName: "Marketstack",
		aliases:     []string{"marketstack api", "market stack"},
		category:    "financial-market-data",
		n8nNode:     "Marketstack",
		relevance:   "Popular stock-market data API for end-of-day, intraday, ticker, exchange, currency, index, and market data automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "nasa",
		displayName: "NASA",
		aliases:     []string{"nasa api", "api.nasa.gov"},
		category:    "public-data",
		n8nNode:     "Nasa",
		relevance:   "Popular public science data APIs for astronomy pictures, Mars rover photos, near-earth objects, EPIC imagery, and NASA datasets.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "onesimpleapi",
		displayName: "OneSimpleApi",
		aliases:     []string{"one simple api", "onesimpleapi api"},
		category:    "utility-api",
		n8nNode:     "OneSimpleApi",
		relevance:   "Popular utility API toolkit for web page metadata, page status, screenshots, PDFs, QR codes, email validation, and URL tools.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "openthesaurus",
		displayName: "OpenThesaurus",
		aliases:     []string{"open thesaurus", "openthesaurus api"},
		category:    "language",
		n8nNode:     "OpenThesaurus",
		relevance:   "Popular public thesaurus API for German synonym lookup, similar-word suggestions, substring matches, JSON, and XML responses.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "quickchart",
		displayName: "QuickChart",
		aliases:     []string{"quickchart api", "quick chart"},
		category:    "data-visualization",
		n8nNode:     "QuickChart",
		relevance:   "Popular image-generation API for Chart.js charts, QR codes, graph visualizations, short URLs, and rendered chart assets.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "reddit",
		displayName: "Reddit",
		aliases:     []string{"reddit api"},
		category:    "social",
		n8nNode:     "Reddit",
		relevance:   "Popular social platform API for subreddits, posts, comments, users, listings, messages, moderation, and content automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "uptimerobot",
		displayName: "UptimeRobot",
		aliases:     []string{"uptime robot", "uptimerobot api", "uptime robot api"},
		category:    "monitoring",
		n8nNode:     "UptimeRobot",
		relevance:   "Popular uptime monitoring service for monitors, incidents, alert contacts, maintenance windows, public status pages, and uptime automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "autopilot",
		displayName: "Autopilot",
		aliases:     []string{"autopilot api", "autopilot journeys", "ortto autopilot"},
		category:    "marketing-automation",
		n8nNode:     "Autopilot",
		relevance:   "Popular legacy marketing automation platform for contacts, lists, journeys, triggers, and unsubscribe synchronization.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "drift",
		displayName: "Drift",
		aliases:     []string{"drift api", "drift conversations"},
		category:    "sales-engagement",
		n8nNode:     "Drift",
		relevance:   "Popular conversational marketing and sales platform for contacts, conversations, users, messages, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "freshworks-crm",
		displayName: "Freshworks CRM",
		aliases:     []string{"freshworks crm", "freshsales api", "freshworks crm api"},
		category:    "crm",
		n8nNode:     "FreshworksCrm",
		relevance:   "Popular CRM platform for contacts, accounts, deals, appointments, tasks, notes, sales activities, and search automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "getresponse",
		displayName: "GetResponse",
		aliases:     []string{"getresponse api", "get response"},
		category:    "email-marketing",
		n8nNode:     "GetResponse",
		relevance:   "Popular email marketing and automation platform for contacts, campaigns, newsletters, forms, tags, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "highlevel",
		displayName: "HighLevel",
		aliases:     []string{"gohighlevel", "go high level", "high level crm", "highlevel api", "leadconnector"},
		category:    "crm",
		n8nNode:     "HighLevel",
		relevance:   "Popular CRM and marketing automation platform for contacts, opportunities, calendars, users, workflows, locations, and marketplace apps.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "keap",
		displayName: "Keap",
		aliases:     []string{"keap api", "keap crm", "infusionsoft api"},
		category:    "crm",
		n8nNode:     "Keap",
		relevance:   "Popular CRM and small-business automation platform for contacts, companies, tags, notes, files, orders, products, and email automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mailerlite",
		displayName: "MailerLite",
		aliases:     []string{"mailerlite api", "mailer lite"},
		category:    "email-marketing",
		n8nNode:     "MailerLite",
		relevance:   "Popular email marketing platform for subscribers, groups, campaigns, automations, fields, segments, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mautic",
		displayName: "Mautic",
		aliases:     []string{"mautic api", "mautic marketing"},
		category:    "marketing-automation",
		n8nNode:     "Mautic",
		relevance:   "Popular open-source marketing automation platform for contacts, companies, segments, campaigns, emails, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "monica-crm",
		displayName: "Monica CRM",
		aliases:     []string{"monica", "monica api", "monica crm api", "monicahq"},
		category:    "crm",
		n8nNode:     "MonicaCrm",
		relevance:   "Popular personal CRM for contacts, activities, notes, calls, reminders, tasks, tags, and relationship automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "salesmate",
		displayName: "Salesmate",
		aliases:     []string{"salesmate api", "salesmate crm"},
		category:    "crm",
		n8nNode:     "Salesmate",
		relevance:   "Popular CRM platform for contacts, companies, deals, activities, notes, products, and sales automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "sendy",
		displayName: "Sendy",
		aliases:     []string{"sendy api"},
		category:    "email-marketing",
		n8nNode:     "Sendy",
		relevance:   "Popular self-hosted email newsletter app for subscribers, lists, brands, campaigns, and bulk-email automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "vero",
		displayName: "Vero",
		aliases:     []string{"vero api", "vero track", "getvero"},
		category:    "customer-engagement",
		n8nNode:     "Vero",
		relevance:   "Popular customer engagement platform for user profiles, events, tags, campaigns, messages, and behavioral email automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "jotform",
		displayName: "JotForm",
		aliases:     []string{"jotform api", "jot form"},
		category:    "forms",
		n8nNode:     "JotForm",
		relevance:   "Popular form builder for forms, submissions, questions, reports, folders, and form webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "formio",
		displayName: "Form.io",
		aliases:     []string{"form.io", "formio", "form io api"},
		category:    "forms",
		n8nNode:     "FormIo",
		relevance:   "Popular form and data-management platform for projects, forms, submissions, roles, and deployment automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "formstack",
		displayName: "Formstack",
		aliases:     []string{"formstack api", "formstack forms"},
		category:    "forms",
		n8nNode:     "Formstack",
		relevance:   "Popular online form platform for forms, submissions, fields, folders, webhooks, and response automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "surveymonkey",
		displayName: "SurveyMonkey",
		aliases:     []string{"survey monkey", "surveymonkey api"},
		category:    "forms",
		n8nNode:     "SurveyMonkey",
		relevance:   "Popular survey platform for surveys, collectors, respondents, responses, webhooks, and analytics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "kobotoolbox",
		displayName: "KoBoToolbox",
		aliases:     []string{"kobo toolbox", "kobotoolbox api", "kobo api"},
		category:    "forms",
		n8nNode:     "KoBoToolbox",
		relevance:   "Popular humanitarian data-collection platform for projects, forms, submissions, exports, files, hooks, and permissions.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "bubble",
		displayName: "Bubble",
		aliases:     []string{"bubble api", "bubble.io", "bubble data api"},
		category:    "app-builder",
		n8nNode:     "Bubble",
		relevance:   "Popular no-code app builder for app-specific data APIs, workflow APIs, object types, and backend workflow automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "cal",
		displayName: "Cal.com",
		aliases:     []string{"cal.com", "cal api", "calcom"},
		category:    "scheduling",
		n8nNode:     "Cal",
		relevance:   "Popular scheduling platform for event types, bookings, calendars, webhooks, organizations, and availability automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "cockpit",
		displayName: "Cockpit",
		aliases:     []string{"cockpit cms", "cockpit api"},
		category:    "cms",
		n8nNode:     "Cockpit",
		relevance:   "Popular headless CMS for collections, singletons, assets, content items, and self-hosted content APIs.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "stackby",
		displayName: "Stackby",
		aliases:     []string{"stackby api", "stackby database"},
		category:    "database",
		n8nNode:     "Stackby",
		relevance:   "Popular no-code database platform for stacks, tables, rows, columns, views, and spreadsheet-style automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "airtop",
		displayName: "Airtop",
		aliases:     []string{"airtop api", "airtop browser"},
		category:    "browser-automation",
		n8nNode:     "Airtop",
		relevance:   "Popular AI browser automation platform for sessions, windows, files, agents, and browser interaction automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "timesaved",
		displayName: "TimeSaved",
		aliases:     []string{"time saved", "track time saved", "saved time"},
		category:    "workflow-metadata",
		n8nNode:     "TimeSaved",
		relevance:   "n8n workflow metadata helper for tracking estimated time saved during workflow execution; not an external provider API.",
		userNeed:    UserOpenAPINeedPossible,
	}),
	workflowCandidate(candidateSeed{
		id:          "filemaker",
		displayName: "FileMaker",
		aliases:     []string{"filemaker data api", "claris filemaker", "filemaker api"},
		category:    "database",
		n8nNode:     "FileMaker",
		relevance:   "Popular low-code database platform for layouts, records, scripts, containers, metadata, and hosted database automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "facebook",
		displayName: "Facebook",
		aliases:     []string{"facebook api", "facebook graph api", "meta graph api"},
		category:    "social",
		n8nNode:     "Facebook",
		relevance:   "Popular social platform for Graph API profile, page, feed, comment, media, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "facebook-lead-ads",
		displayName: "Facebook Lead Ads",
		aliases:     []string{"facebook lead ads api", "meta lead ads", "facebook leads api"},
		category:    "advertising",
		n8nNode:     "FacebookLeadAds",
		relevance:   "Popular advertising lead-capture service for pages, lead forms, lead retrieval, and leadgen webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "linkedin",
		displayName: "LinkedIn",
		aliases:     []string{"linkedin api", "linkedin marketing api"},
		category:    "social",
		n8nNode:     "LinkedIn",
		relevance:   "Popular professional network for member identity, organization pages, posts, lead forms, and marketing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "line",
		displayName: "LINE",
		aliases:     []string{"line api", "line messaging api", "line bot api"},
		category:    "messaging",
		n8nNode:     "Line",
		relevance:   "Popular messaging platform for bot messages, replies, multicast, profiles, webhooks, audiences, and official-account automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "mattermost",
		displayName: "Mattermost",
		aliases:     []string{"mattermost api", "mattermost rest api"},
		category:    "team-chat",
		n8nNode:     "Mattermost",
		relevance:   "Popular team chat platform for users, teams, channels, posts, files, reactions, and webhook automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "messagebird",
		displayName: "MessageBird",
		aliases:     []string{"messagebird api", "bird messaging api"},
		category:    "messaging",
		n8nNode:     "MessageBird",
		relevance:   "Popular communications platform for SMS messages, voice calls, contacts, balance, HLR, and inbound webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "matrix",
		displayName: "Matrix",
		aliases:     []string{"matrix api", "matrix client server api"},
		category:    "messaging",
		n8nNode:     "Matrix",
		relevance:   "Popular open communications protocol for homeserver client-server messaging, rooms, events, presence, and account automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "rocket-chat",
		displayName: "Rocket.Chat",
		aliases:     []string{"rocketchat", "rocket chat api", "rocket.chat api"},
		category:    "team-chat",
		n8nNode:     "Rocketchat",
		relevance:   "Popular team chat platform for authentication, users, rooms, messages, channels, integrations, and workspace automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "twake",
		displayName: "Twake",
		aliases:     []string{"twake api", "twake developers api"},
		category:    "team-collaboration",
		n8nNode:     "Twake",
		relevance:   "Popular open-source collaboration platform for app authentication, messages, channels, drive, and workspace automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "twist",
		displayName: "Twist",
		aliases:     []string{"twist api", "twist v3 api"},
		category:    "team-chat",
		n8nNode:     "Twist",
		relevance:   "Popular asynchronous team communication service for workspaces, channels, threads, comments, messages, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "twitter",
		displayName: "Twitter / X",
		aliases:     []string{"twitter api", "x api", "x twitter api"},
		category:    "social",
		n8nNode:     "Twitter",
		relevance:   "Popular social platform for posts, users, lists, bookmarks, direct messages, searches, and timeline automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "whatsapp",
		displayName: "WhatsApp",
		aliases:     []string{"whatsapp api", "whatsapp cloud api", "whatsapp business api"},
		category:    "messaging",
		n8nNode:     "WhatsApp",
		relevance:   "Popular business messaging platform for Cloud API messages, media, templates, phone numbers, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "magento",
		displayName: "Magento / Adobe Commerce",
		aliases:     []string{"magento api", "adobe commerce api", "magento 2 api"},
		category:    "ecommerce",
		n8nNode:     "Magento",
		relevance:   "Popular ecommerce platform for products, categories, customers, carts, orders, invoices, shipments, and store automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "paddle",
		displayName: "Paddle",
		aliases:     []string{"paddle api", "paddle billing api"},
		category:    "billing",
		n8nNode:     "Paddle",
		relevance:   "Popular merchant-of-record billing platform for products, prices, customers, transactions, subscriptions, adjustments, and events.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "gumroad",
		displayName: "Gumroad",
		aliases:     []string{"gumroad api"},
		category:    "commerce",
		n8nNode:     "Gumroad",
		relevance:   "Popular creator commerce platform for products, sales, subscribers, offers, licenses, and sale webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "invoice-ninja",
		displayName: "Invoice Ninja",
		aliases:     []string{"invoice ninja api", "invoiceninja api"},
		category:    "accounting",
		n8nNode:     "InvoiceNinja",
		relevance:   "Popular invoicing platform for clients, invoices, quotes, payments, products, projects, vendors, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "odoo",
		displayName: "Odoo",
		aliases:     []string{"odoo api", "odoo external api", "odoo xml-rpc api"},
		category:    "erp",
		n8nNode:     "Odoo",
		relevance:   "Popular ERP and CRM platform for model records, sales, accounting, inventory, contacts, and business workflow automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "erpnext",
		displayName: "ERPNext",
		aliases:     []string{"erpnext api", "frappe api", "erpnext rest api"},
		category:    "erp",
		n8nNode:     "ERPNext",
		relevance:   "Popular open-source ERP platform for DocType records, items, customers, suppliers, sales orders, invoices, and stock automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "woocommerce",
		displayName: "WooCommerce",
		aliases:     []string{"woocommerce api", "woocommerce rest api", "wc rest api"},
		category:    "ecommerce",
		n8nNode:     "WooCommerce",
		relevance:   "Popular WordPress ecommerce platform for products, orders, customers, coupons, reports, refunds, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "wise",
		displayName: "Wise",
		aliases:     []string{"wise api", "transferwise api", "wise platform api"},
		category:    "payments",
		n8nNode:     "Wise",
		relevance:   "Popular cross-border payments platform for profiles, quotes, recipients, transfers, balances, statements, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "dhl",
		displayName: "DHL",
		aliases:     []string{"dhl api", "dhl shipment tracking api", "dhl tracking api"},
		category:    "shipping",
		n8nNode:     "Dhl",
		relevance:   "Popular logistics provider for shipment tracking, shipment events, delivery status, and shipping-account automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "onfleet",
		displayName: "Onfleet",
		aliases:     []string{"onfleet api"},
		category:    "delivery",
		n8nNode:     "Onfleet",
		relevance:   "Popular last-mile delivery platform for tasks, workers, teams, hubs, destinations, recipients, admins, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "unleashed-software",
		displayName: "Unleashed Software",
		aliases:     []string{"unleashed api", "unleashed software api"},
		category:    "inventory",
		n8nNode:     "UnleashedSoftware",
		relevance:   "Popular inventory management platform for stock on hand, products, sales orders, purchase orders, customers, and warehouses.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "workable",
		displayName: "Workable",
		aliases:     []string{"workable api", "workable recruiting api"},
		category:    "hr",
		n8nNode:     "Workable",
		relevance:   "Popular recruiting platform for jobs, candidates, applications, members, recruiters, stages, requisitions, and hiring automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "bitwarden",
		displayName: "Bitwarden",
		aliases:     []string{"bitwarden api", "bitwarden public api"},
		category:    "secrets-security",
		n8nNode:     "Bitwarden",
		relevance:   "Popular password-management and secrets platform for organization groups, members, collections, events, and access administration automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "cisco-webex",
		displayName: "Cisco Webex",
		aliases:     []string{"cisco", "cisco api", "cisco webex api", "webex api"},
		category:    "collaboration",
		n8nNode:     "Cisco/Webex",
		relevance:   "Popular collaboration platform for rooms, messages, memberships, people, meetings, recordings, attachment actions, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "cortex",
		displayName: "Cortex",
		aliases:     []string{"cortex api", "thehive cortex api", "strangebee cortex api"},
		category:    "security-automation",
		n8nNode:     "Cortex",
		relevance:   "Popular security automation and analyzer platform for analyzers, responders, jobs, reports, organizations, and observable enrichment workflows.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "home-assistant",
		displayName: "Home Assistant",
		aliases:     []string{"home assistant api", "home assistant rest api", "homeassistant"},
		category:    "home-automation",
		n8nNode:     "HomeAssistant",
		relevance:   "Popular home automation platform for states, services, events, templates, history, and entity automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "misp",
		displayName: "MISP",
		aliases:     []string{"misp api", "misp automation api", "misp threat intelligence"},
		category:    "threat-intelligence",
		n8nNode:     "Misp",
		relevance:   "Popular threat intelligence sharing platform for events, attributes, objects, tags, feeds, warninglists, and organization administration automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "netscaler",
		displayName: "NetScaler ADC",
		aliases:     []string{"citrix adc", "citrix adc api", "netscaler api", "netscaler nitro api"},
		category:    "networking",
		n8nNode:     "Netscaler/ADC",
		relevance:   "Popular application delivery controller platform for NITRO configuration, load-balancing, service, server, and statistics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "rundeck",
		displayName: "Rundeck",
		aliases:     []string{"rundeck api", "runbook automation api"},
		category:    "automation",
		n8nNode:     "Rundeck",
		relevance:   "Popular runbook automation platform for projects, jobs, executions, nodes, webhooks, tokens, and system administration workflows.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "securityscorecard",
		displayName: "SecurityScorecard",
		aliases:     []string{"security scorecard", "securityscorecard api", "security scorecard api"},
		category:    "security-ratings",
		n8nNode:     "SecurityScorecard",
		relevance:   "Popular security ratings platform for companies, scores, factors, issues, portfolios, reports, and vendor risk automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "urlscan",
		displayName: "urlscan.io",
		aliases:     []string{"urlscan api", "urlscan.io api", "urlscanio"},
		category:    "threat-intelligence",
		n8nNode:     "UrlScanIo",
		relevance:   "Popular URL scanning and threat intelligence platform for scan submissions, results, search, quotas, and investigation automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "venafi",
		displayName: "Venafi",
		aliases:     []string{"venafi api", "venafi tls protect api", "venafi web sdk"},
		category:    "certificate-management",
		n8nNode:     "Venafi",
		relevance:   "Popular machine identity and certificate-management platform for certificates, certificate requests, applications, and TLS Protect automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "wekan",
		displayName: "Wekan",
		aliases:     []string{"wekan api", "wekan rest api"},
		category:    "project-management",
		n8nNode:     "Wekan",
		relevance:   "Popular open-source kanban platform for boards, lists, cards, checklists, comments, users, and swimlane automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "zammad",
		displayName: "Zammad",
		aliases:     []string{"zammad api", "zammad helpdesk api"},
		category:    "support",
		n8nNode:     "Zammad",
		relevance:   "Popular help desk platform for tickets, users, organizations, groups, articles, object attributes, and search automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "humantic-ai",
		displayName: "Humantic AI",
		aliases:     []string{"humantic", "humantic ai api", "humanticai"},
		category:    "data-enrichment",
		n8nNode:     "HumanticAI",
		relevance:   "Popular buyer-intelligence and personality-enrichment API for profile creation, profile retrieval, and sales or hiring persona automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "hunter",
		displayName: "Hunter",
		aliases:     []string{"hunter api", "hunter.io", "hunter.io api"},
		category:    "data-enrichment",
		n8nNode:     "Hunter",
		relevance:   "Popular email-finding and verification service for domain search, email finder, verifier, leads, and campaign enrichment automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "jina-ai",
		displayName: "Jina AI",
		aliases:     []string{"jina", "jina ai api", "jina reader", "jina search"},
		category:    "ai-search",
		n8nNode:     "JinaAI",
		relevance:   "Popular AI search foundation platform for reader, search, embeddings, reranking, classification, chat completions, and research workflows.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "lingvanex",
		displayName: "LingvaNex",
		aliases:     []string{"lingvanex api", "lingvanex translation api"},
		category:    "translation",
		n8nNode:     "LingvaNex",
		relevance:   "Popular translation and language service for text translation, language detection, dictionary, and translation automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mistral-ai",
		displayName: "Mistral AI",
		aliases:     []string{"mistral", "mistral ai api", "mistral cloud api"},
		category:    "ai-platform",
		n8nNode:     "MistralAI",
		relevance:   "Popular AI platform for chat completions, embeddings, OCR, files, batch jobs, agents, and model automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "openai",
		displayName: "OpenAI",
		aliases:     []string{"open ai", "openai api", "openai platform"},
		category:    "ai-platform",
		n8nNode:     "OpenAi",
		relevance:   "Popular AI platform for responses, chat, images, audio, embeddings, files, fine-tuning, assistants, and vector-store automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "perplexity",
		displayName: "Perplexity",
		aliases:     []string{"perplexity ai", "perplexity api", "sonar api"},
		category:    "ai-search",
		n8nNode:     "Perplexity",
		relevance:   "Popular AI answer and search platform for Sonar chat completions, Agent responses, search, embeddings, and async research automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "mindee",
		displayName: "Mindee",
		aliases:     []string{"mindee api", "mindee document ai", "mindee ocr"},
		category:    "document-ai",
		n8nNode:     "Mindee",
		relevance:   "Popular document AI platform for receipts, invoices, OCR, extraction models, and document-processing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "peekalink",
		displayName: "Peekalink",
		aliases:     []string{"peekalink api", "link preview api"},
		category:    "link-preview",
		n8nNode:     "Peekalink",
		relevance:   "Popular link-preview API for URL metadata, rich previews, availability checks, and social-card enrichment automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "phantombuster",
		displayName: "Phantombuster",
		aliases:     []string{"phantombuster api", "phantom buster"},
		category:    "automation",
		n8nNode:     "Phantombuster",
		relevance:   "Popular web automation platform for agents, containers, scripts, org storage, launches, and lead automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "uplead",
		displayName: "UpLead",
		aliases:     []string{"uplead api", "up lead"},
		category:    "data-enrichment",
		n8nNode:     "Uplead",
		relevance:   "Popular B2B enrichment service for person and company lookup by email, domain, name, and firmographic automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "dropcontact",
		displayName: "Dropcontact",
		aliases:     []string{"dropcontact api", "drop contact"},
		category:    "data-enrichment",
		n8nNode:     "Dropcontact",
		relevance:   "Popular B2B contact enrichment service for batch email finding, company enrichment, and request-result polling automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mocean",
		displayName: "Mocean",
		aliases:     []string{"mocean api", "moceanapi", "mocean sms"},
		category:    "messaging",
		n8nNode:     "Mocean",
		relevance:   "Popular communications API for SMS, voice text-to-speech calls, delivery callbacks, and account balance checks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "msg91",
		displayName: "MSG91",
		aliases:     []string{"msg91 api", "msg91 sms"},
		category:    "messaging",
		n8nNode:     "Msg91",
		relevance:   "Popular customer engagement and messaging platform for SMS, OTP, voice, WhatsApp, email, and campaign notification automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "plivo",
		displayName: "Plivo",
		aliases:     []string{"plivo api", "plivo messaging", "plivo voice"},
		category:    "messaging",
		n8nNode:     "Plivo",
		relevance:   "Popular communications API for SMS, MMS, WhatsApp, outbound calls, message records, and voice automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "pushbullet",
		displayName: "Pushbullet",
		aliases:     []string{"pushbullet api", "pushbullet push"},
		category:    "notifications",
		n8nNode:     "Pushbullet",
		relevance:   "Popular notification service for pushes, devices, contacts, channels, subscriptions, uploads, and realtime notification automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "pushcut",
		displayName: "Pushcut",
		aliases:     []string{"pushcut api", "pushcut notifications"},
		category:    "notifications",
		n8nNode:     "Pushcut",
		relevance:   "Popular iOS notification and automation service for notifications, webhooks, subscriptions, devices, and server actions.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "pushover",
		displayName: "Pushover",
		aliases:     []string{"pushover api", "pushover notifications"},
		category:    "notifications",
		n8nNode:     "Pushover",
		relevance:   "Popular push notification service for app messages, emergency priorities, receipts, users, groups, and subscription messaging.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "signl4",
		displayName: "SIGNL4",
		aliases:     []string{"signl4 api", "signl4 alerts", "signl4 webhook"},
		category:    "incident-management",
		n8nNode:     "Signl4",
		relevance:   "Popular alerting and incident response service for Signls, teams, duty schedules, categories, alert events, and webhooks.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "sms77",
		displayName: "sms77",
		aliases:     []string{"seven", "seven.io", "sms77 api", "seven api"},
		category:    "messaging",
		n8nNode:     "Sms77",
		relevance:   "Popular SMS and voice messaging platform now branded seven.io, covering SMS, voice, balance, contacts, analytics, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "vonage",
		displayName: "Vonage",
		aliases:     []string{"nexmo", "vonage api", "vonage messages", "vonage sms"},
		category:    "messaging",
		n8nNode:     "Vonage",
		relevance:   "Popular communications API platform for SMS, MMS, WhatsApp, messages, voice, applications, and multichannel notification automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "zulip",
		displayName: "Zulip",
		aliases:     []string{"zulip api", "zulip chat"},
		category:    "team-chat",
		n8nNode:     "Zulip",
		relevance:   "Popular open-source team chat service for streams, topics, messages, users, reactions, files, and chat automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "gotify",
		displayName: "Gotify",
		aliases:     []string{"gotify api", "gotify server", "gotify notifications"},
		category:    "notifications",
		n8nNode:     "Gotify",
		relevance:   "Popular self-hosted push notification server for applications, clients, messages, plugins, and notification automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "emelia",
		displayName: "Emelia",
		aliases:     []string{"emelia api", "emelia graphql", "emelia cold email"},
		category:    "email-marketing",
		n8nNode:     "Emelia",
		relevance:   "Popular outbound sales and email campaign platform for campaigns, contact lists, LinkedIn scraper actions, and campaign activity webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "disqus",
		displayName: "Disqus",
		aliases:     []string{"disqus api", "disqus comments"},
		category:    "community",
		n8nNode:     "Disqus",
		relevance:   "Popular commenting and community platform for forums, threads, posts, categories, moderation, and engagement automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "medium",
		displayName: "Medium",
		aliases:     []string{"medium api", "medium publishing"},
		category:    "publishing",
		n8nNode:     "Medium",
		relevance:   "Popular publishing platform for user profile lookup, posts, and publication publishing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "npm",
		displayName: "npm",
		aliases:     []string{"npm api", "npm registry", "npmjs"},
		category:    "developer-tools",
		n8nNode:     "Npm",
		relevance:   "Popular package registry API for package metadata, search, versions, dist-tags, and package automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "spotify",
		displayName: "Spotify",
		aliases:     []string{"spotify api", "spotify web api"},
		category:    "media",
		n8nNode:     "Spotify",
		relevance:   "Popular music and audio platform API for artists, albums, tracks, playlists, playback, saved library, and search automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "storyblok",
		displayName: "Storyblok",
		aliases:     []string{"storyblok api", "storyblok cms"},
		category:    "cms",
		n8nNode:     "Storyblok",
		relevance:   "Popular headless CMS for content delivery, stories, spaces, components, publishing, and content automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "strapi",
		displayName: "Strapi",
		aliases:     []string{"strapi api", "strapi cms"},
		category:    "cms",
		n8nNode:     "Strapi",
		relevance:   "Popular headless CMS for collection entries, content APIs, authentication, and self-hosted content automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "wordpress",
		displayName: "WordPress",
		aliases:     []string{"wordpress api", "wordpress rest api", "wordpress.com"},
		category:    "cms",
		n8nNode:     "Wordpress",
		relevance:   "Popular publishing and CMS platform for posts, pages, media, users, categories, tags, and site content automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "wufoo",
		displayName: "Wufoo",
		aliases:     []string{"wufoo api", "wufoo forms"},
		category:    "forms",
		n8nNode:     "Wufoo",
		relevance:   "Popular form builder API for forms, entries, reports, comments, files, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "yourls",
		displayName: "YOURLS",
		aliases:     []string{"yourls api", "your own url shortener"},
		category:    "url-shortening",
		n8nNode:     "Yourls",
		relevance:   "Popular self-hosted URL shortener API for shortening, expanding, stats, and link management automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "raindrop",
		displayName: "Raindrop.io",
		aliases:     []string{"raindrop", "raindrop api", "raindrop.io"},
		category:    "bookmarks",
		n8nNode:     "Raindrop",
		relevance:   "Popular bookmark management API for raindrops, collections, tags, filters, highlights, and bookmark automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "toggl",
		displayName: "Toggl Track",
		aliases:     []string{"toggl", "toggl api", "toggl track", "toggl track api"},
		category:    "time-tracking",
		n8nNode:     "Toggl",
		relevance:   "Popular time-tracking API for workspaces, time entries, projects, clients, tasks, tags, reports, and tracking automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "travis-ci",
		displayName: "Travis CI",
		aliases:     []string{"travis", "travis api", "travis ci", "travis ci api"},
		category:    "ci-cd",
		n8nNode:     "TravisCi",
		relevance:   "Popular CI/CD API for repositories, builds, jobs, requests, branches, environment variables, and build automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
}

type candidateSeed struct {
	id              string
	displayName     string
	aliases         []string
	category        string
	fixture         string
	n8nNode         string
	relevance       string
	machineSpecKind string
	machineStatus   SpecStatus
	userNeed        UserOpenAPINeed
}

func workflowCandidate(seed candidateSeed) Candidate {
	machineStatus := seed.machineStatus
	if machineStatus == "" {
		machineStatus = SpecStatusUnknown
	}
	userNeed := seed.userNeed
	if userNeed == "" {
		userNeed = UserOpenAPINeedPossible
	}
	candidate := Candidate{
		ID:                        seed.id,
		DisplayName:               seed.displayName,
		Aliases:                   append([]string(nil), seed.aliases...),
		Category:                  seed.category,
		WorkflowRelevance:         seed.relevance,
		OfficialOpenAPIStatus:     SpecStatusNeedsVerification,
		OfficialMachineSpecStatus: machineStatus,
		OfficialMachineSpecKind:   seed.machineSpecKind,
		UserOpenAPINeed:           userNeed,
		AuthSecurityReview:        AuthSecurityNotReviewed,
	}
	if seed.fixture != "" {
		fixturePath := tryN8nSpecRoot + seed.fixture
		candidate.LocalOpenAPIFixture = fixturePath
		candidate.Evidence = append(candidate.Evidence, CandidateEvidence{
			Source: EvidenceTryN8nLocalFixture,
			Use:    EvidenceUseSeedFixture,
			Ref:    fixturePath,
			Note:   "Local OpenUdon advisory fixture; not treated as an official provider source.",
		})
	}
	if seed.n8nNode != "" {
		candidate.Evidence = append(candidate.Evidence, CandidateEvidence{
			Source: EvidenceN8nNodeDirectory,
			Use:    EvidenceUsePriority,
			Ref:    n8nNodeRoot + seed.n8nNode,
			Note:   "n8n built-in node presence is a prioritization signal only, not runtime compatibility evidence.",
		})
	}
	return candidate
}
