package catalog

const (
	tryN8nSpecRoot = "../try-n8n/reducibility/specs/"
	n8nNodeRoot    = "../n8n/packages/nodes-base/nodes/"
)

var builtInCandidates = []Candidate{
	workflowCandidate(candidateSeed{
		id:          "activecampaign",
		displayName: "ActiveCampaign",
		aliases:     []string{"activecampaign api", "active campaign"},
		category:    "email-marketing",
		n8nNode:     "ActiveCampaign",
		relevance:   "Popular marketing automation platform for contacts, campaigns, automations, deals, and email workflow automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "action-network",
		displayName: "Action Network",
		aliases:     []string{"action network api", "actionnetwork", "osdi api"},
		category:    "advocacy",
		n8nNode:     "ActionNetwork",
		relevance:   "Popular organizing platform for activists, petitions, events, forms, tags, campaigns, and nonprofit advocacy automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "adalo",
		displayName: "Adalo",
		aliases:     []string{"adalo api", "adalo collections api"},
		category:    "app-builder",
		n8nNode:     "Adalo",
		relevance:   "Popular no-code app builder for application collections, records, and push notification automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "affinity",
		displayName: "Affinity",
		aliases:     []string{"affinity api", "affinity crm api"},
		category:    "crm",
		n8nNode:     "Affinity",
		relevance:   "Popular relationship intelligence CRM for lists, people, organizations, opportunities, interactions, notes, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "agile-crm",
		displayName: "Agile CRM",
		aliases:     []string{"agile crm", "agilecrm", "agilecrm api"},
		category:    "crm",
		n8nNode:     "AgileCrm",
		relevance:   "Popular CRM and marketing automation service for contacts, companies, deals, tasks, events, campaigns, and help desk records.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "asana",
		displayName: "Asana",
		aliases:     []string{"asana api"},
		category:    "project-management",
		n8nNode:     "Asana",
		relevance:   "Popular workflow service for task, project, and work-management automation.",
	}),
	workflowCandidate(candidateSeed{
		id:              "aws-s3",
		displayName:     "AWS S3",
		aliases:         []string{"amazon s3", "aws s3 api", "s3"},
		category:        "cloud-storage",
		n8nNode:         "Aws/S3",
		relevance:       "Popular infrastructure service for object storage, buckets, object metadata, and file automation.",
		machineSpecKind: string(SpecKindSmithyJSON),
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "aws-sns",
		displayName:     "AWS SNS",
		aliases:         []string{"amazon sns", "aws sns api", "sns"},
		category:        "messaging",
		n8nNode:         "Aws/AwsSns",
		relevance:       "Popular infrastructure service for topics, subscriptions, publish operations, SMS, and notification automation.",
		machineSpecKind: string(SpecKindSmithyJSON),
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "aws-lambda",
		displayName:     "AWS Lambda",
		aliases:         []string{"amazon lambda", "aws lambda api", "lambda"},
		category:        "serverless-compute",
		n8nNode:         "Aws/AwsLambda",
		relevance:       "Popular infrastructure service for functions, invocations, event source mappings, aliases, and serverless automation.",
		machineSpecKind: string(SpecKindSmithyJSON),
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "airtable",
		displayName: "Airtable",
		aliases:     []string{"airtable api"},
		category:    "database",
		fixture:     "airtable.json",
		n8nNode:     "Airtable",
		relevance:   "Common workflow source and destination for records in bases and tables.",
	}),
	workflowCandidate(candidateSeed{
		id:          "bamboohr",
		displayName: "BambooHR",
		aliases:     []string{"bamboohr api", "bamboo hr"},
		category:    "hr",
		n8nNode:     "BambooHr",
		relevance:   "Popular HR platform for employee records, reports, time off, and people operations automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "box",
		displayName: "Box",
		aliases:     []string{"box api"},
		category:    "files",
		n8nNode:     "Box",
		relevance:   "Popular workflow service for file storage, sharing, and content-management automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "bannerbear",
		displayName: "Bannerbear",
		aliases:     []string{"bannerbear api", "bannerbear image api"},
		category:    "media-generation",
		n8nNode:     "Bannerbear",
		relevance:   "Popular media automation service for generated images, videos, PDFs, screenshots, templates, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "baserow",
		displayName: "Baserow",
		aliases:     []string{"baserow api", "baserow database api"},
		category:    "database",
		n8nNode:     "Baserow",
		relevance:   "Popular open-source database platform for workspaces, databases, tables, fields, rows, views, and automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "beeminder",
		displayName: "Beeminder",
		aliases:     []string{"beeminder api"},
		category:    "productivity",
		n8nNode:     "Beeminder",
		relevance:   "Popular goal tracking and commitment platform for users, goals, datapoints, charges, and reminder automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "bitbucket",
		displayName: "Bitbucket",
		aliases:     []string{"bitbucket api", "bitbucket cloud"},
		category:    "developer-tools",
		n8nNode:     "Bitbucket",
		relevance:   "Popular developer platform for repositories, pull requests, pipelines, workspaces, and source automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "brandfetch",
		displayName: "Brandfetch",
		aliases:     []string{"brandfetch api", "brand api", "brandfetch brand api"},
		category:    "brand-data",
		n8nNode:     "Brandfetch",
		relevance:   "Popular brand-data API for logos, colors, fonts, images, firmographic information, and personalization automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "calendly",
		displayName: "Calendly",
		aliases:     []string{"calendly api"},
		category:    "scheduling",
		n8nNode:     "Calendly",
		relevance:   "Popular workflow service for scheduling events, invitees, and booking automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "chargebee",
		displayName: "Chargebee",
		aliases:     []string{"chargebee api"},
		category:    "billing",
		n8nNode:     "Chargebee",
		relevance:   "Popular subscription billing platform for customers, subscriptions, invoices, payments, and revenue automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "circleci",
		displayName: "CircleCI",
		aliases:     []string{"circleci api", "circleci v2"},
		category:    "ci-cd",
		n8nNode:     "CircleCi",
		relevance:   "Popular workflow service for pipelines, workflows, jobs, artifacts, contexts, and CI/CD automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "clearbit",
		displayName: "Clearbit",
		aliases:     []string{"clearbit api", "clearbit enrichment api", "clearbit prospector"},
		category:    "data-enrichment",
		n8nNode:     "Clearbit",
		relevance:   "Popular B2B data enrichment platform for person, company, prospecting, reveal, and legacy lookup automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "cloudflare",
		displayName: "Cloudflare",
		aliases:     []string{"cloudflare api"},
		category:    "edge-platform",
		n8nNode:     "Cloudflare",
		relevance:   "Popular infrastructure platform for DNS, zones, caching, security rules, workers, and edge automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "contentful",
		displayName: "Contentful",
		aliases:     []string{"contentful api", "contentful management api"},
		category:    "cms",
		n8nNode:     "Contentful",
		relevance:   "Popular composable content platform for spaces, entries, assets, environments, and publishing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "customer-io",
		displayName: "Customer.io",
		aliases:     []string{"customer.io", "customer.io api", "customerio"},
		category:    "customer-engagement",
		n8nNode:     "CustomerIo",
		relevance:   "Popular customer engagement platform for messaging, journeys, profiles, events, and data pipeline automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "databricks",
		displayName: "Databricks",
		aliases:     []string{"databricks api", "databricks rest api"},
		category:    "data-platform",
		n8nNode:     "Databricks",
		relevance:   "Popular data platform for SQL warehouses, jobs, model serving, Unity Catalog, vector search, and lakehouse automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "clickup",
		displayName: "ClickUp",
		aliases:     []string{"clickup api", "click up"},
		category:    "project-management",
		n8nNode:     "ClickUp",
		relevance:   "Popular workflow service for tasks, lists, spaces, and team work-management automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "discord",
		displayName: "Discord",
		aliases:     []string{"discord api"},
		category:    "messaging",
		n8nNode:     "Discord",
		relevance:   "Popular workflow service for community messaging, channels, and notification automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "discourse",
		displayName: "Discourse",
		aliases:     []string{"discourse api", "discourse forum api"},
		category:    "community",
		n8nNode:     "Discourse",
		relevance:   "Popular community forum platform for topics, posts, categories, users, groups, tags, badges, and moderation automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "dropbox",
		displayName: "Dropbox",
		aliases:     []string{"dropbox api"},
		category:    "files",
		n8nNode:     "Dropbox",
		relevance:   "Popular workflow service for file storage, transfer, and sharing automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "elastic",
		displayName: "Elastic",
		aliases:     []string{"elastic api", "elasticsearch", "elasticsearch api"},
		category:    "search",
		n8nNode:     "Elastic/Elasticsearch",
		relevance:   "Popular search and analytics platform for indices, documents, search, ingest, and security automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "eventbrite",
		displayName: "Eventbrite",
		aliases:     []string{"eventbrite api"},
		category:    "events",
		n8nNode:     "Eventbrite",
		relevance:   "Popular event platform for events, venues, organizations, attendees, orders, and ticketing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "freshdesk",
		displayName: "Freshdesk",
		aliases:     []string{"freshdesk api"},
		category:    "customer-support",
		n8nNode:     "Freshdesk",
		relevance:   "Popular customer support platform for tickets, contacts, companies, agents, and helpdesk automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "freshservice",
		displayName: "Freshservice",
		aliases:     []string{"freshservice api", "freshservice service desk api"},
		category:    "it-service-management",
		n8nNode:     "Freshservice",
		relevance:   "Popular IT service management platform for tickets, problems, changes, releases, requesters, agents, assets, and service catalog automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "gmail",
		displayName:     "Gmail",
		aliases:         []string{"google mail", "gmail api"},
		category:        "email",
		fixture:         "gmail.json",
		n8nNode:         "Google/Gmail",
		relevance:       "Common workflow service for reading, sending, and routing email messages.",
		machineSpecKind: "google-discovery",
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "google-calendar",
		displayName:     "Google Calendar",
		aliases:         []string{"google calendar api", "calendar api"},
		category:        "scheduling",
		n8nNode:         "Google/Calendar",
		relevance:       "Popular workflow service for calendar events, availability, and scheduling automation.",
		machineSpecKind: "google-discovery",
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "google-drive",
		displayName:     "Google Drive",
		aliases:         []string{"drive", "google drive api"},
		category:        "files",
		fixture:         "google_drive.json",
		n8nNode:         "Google/Drive",
		relevance:       "Common workflow service for file storage, upload, search, and sharing.",
		machineSpecKind: "google-discovery",
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:              "google-sheets",
		displayName:     "Google Sheets",
		aliases:         []string{"sheets", "google sheets api"},
		category:        "spreadsheet",
		n8nNode:         "Google/Sheet",
		relevance:       "Popular workflow service for spreadsheet reads, writes, and tabular-data automation.",
		machineSpecKind: "google-discovery",
		machineStatus:   SpecStatusNeedsVerification,
		userNeed:        UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "grafana",
		displayName: "Grafana",
		aliases:     []string{"grafana api", "grafana http api"},
		category:    "observability",
		n8nNode:     "Grafana",
		relevance:   "Popular observability platform for dashboards, folders, data sources, alerting, service accounts, and monitoring automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "grist",
		displayName: "Grist",
		aliases:     []string{"grist api", "grist rest api", "getgrist"},
		category:    "database",
		n8nNode:     "Grist",
		relevance:   "Popular relational spreadsheet platform for organizations, workspaces, documents, tables, records, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "gong",
		displayName: "Gong",
		aliases:     []string{"gong api", "gong public api"},
		category:    "sales",
		n8nNode:     "Gong",
		relevance:   "Popular revenue intelligence platform for calls, users, conversation analytics, transcripts, CRM data, and call-upload automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "github",
		displayName: "GitHub",
		aliases:     []string{"github api"},
		category:    "developer-tools",
		n8nNode:     "Github",
		relevance:   "Popular workflow service for repositories, issues, pull requests, and developer automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "gitlab",
		displayName: "GitLab",
		aliases:     []string{"gitlab api"},
		category:    "developer-tools",
		n8nNode:     "Gitlab",
		relevance:   "Popular workflow service for repositories, issues, merge requests, and DevOps automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "hubspot",
		displayName: "HubSpot",
		aliases:     []string{"hubspot crm", "hubspot api"},
		category:    "crm",
		fixture:     "hubspot.json",
		n8nNode:     "Hubspot",
		relevance:   "Common workflow service for CRM records, tickets, contacts, and pipeline automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "intercom",
		displayName: "Intercom",
		aliases:     []string{"intercom api", "intercom rest api"},
		category:    "customer-support",
		n8nNode:     "Intercom",
		relevance:   "Popular customer messaging and support platform for contacts, conversations, articles, tickets, and help-center automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "jenkins",
		displayName: "Jenkins",
		aliases:     []string{"jenkins api", "jenkins remote api"},
		category:    "ci-cd",
		n8nNode:     "Jenkins",
		relevance:   "Popular automation server for jobs, builds, queues, nodes, artifacts, and CI/CD automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mailchimp",
		displayName: "Mailchimp",
		aliases:     []string{"mailchimp api", "mailchimp marketing"},
		category:    "email-marketing",
		n8nNode:     "Mailchimp",
		relevance:   "Popular workflow service for audiences, contacts, campaigns, templates, reports, and marketing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mailgun",
		displayName: "Mailgun",
		aliases:     []string{"mailgun api"},
		category:    "email",
		n8nNode:     "Mailgun",
		relevance:   "Popular email platform for sending, domains, routes, suppression lists, and deliverability automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "jira-cloud",
		displayName: "Jira Cloud",
		aliases:     []string{"jira", "atlassian jira", "jira api"},
		category:    "project-management",
		fixture:     "jira.json",
		n8nNode:     "Jira",
		relevance:   "Common workflow service for issue tracking and project automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "linear",
		displayName: "Linear",
		aliases:     []string{"linear api", "linear graphql"},
		category:    "project-management",
		n8nNode:     "Linear",
		relevance:   "Popular workflow service for issues, projects, teams, cycles, comments, and product-development automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "microsoft-graph",
		displayName: "Microsoft Graph",
		aliases:     []string{"microsoft graph api", "graph api", "office 365"},
		category:    "productivity",
		n8nNode:     "Microsoft",
		relevance:   "Popular platform API for Microsoft 365 users, files, mail, calendars, and collaboration automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "monday-com",
		displayName: "Monday.com",
		aliases:     []string{"monday api", "monday.com api", "monday graphql"},
		category:    "project-management",
		n8nNode:     "Monday.com",
		relevance:   "Popular workflow service for boards, items, columns, updates, users, files, and work-management automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "netlify",
		displayName: "Netlify",
		aliases:     []string{"netlify api"},
		category:    "hosting",
		n8nNode:     "Netlify",
		relevance:   "Popular web hosting platform for sites, deploys, forms, DNS, hooks, and build automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "nocodb",
		displayName: "NocoDB",
		aliases:     []string{"nocodb api", "noco db"},
		category:    "database",
		n8nNode:     "NocoDB",
		relevance:   "Popular open-source no-code database platform for base, table, record, attachment, and linked-record automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "notion",
		displayName: "Notion",
		aliases:     []string{"notion api"},
		category:    "knowledge-management",
		n8nNode:     "Notion",
		relevance:   "Popular workflow service for pages, databases, and knowledge-base automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "okta",
		displayName: "Okta",
		aliases:     []string{"okta api", "okta management"},
		category:    "identity",
		n8nNode:     "Okta",
		relevance:   "Popular identity platform for users, groups, applications, events, and organization administration automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "openweathermap",
		displayName: "OpenWeatherMap",
		aliases:     []string{"open weather map", "openweathermap api"},
		category:    "weather",
		fixture:     "openweathermap.json",
		n8nNode:     "OpenWeatherMap",
		relevance:   "Common workflow data source for current weather and forecast enrichment.",
	}),
	workflowCandidate(candidateSeed{
		id:          "pagerduty",
		displayName: "PagerDuty",
		aliases:     []string{"pagerduty api"},
		category:    "incident-management",
		fixture:     "pagerduty.json",
		n8nNode:     "PagerDuty",
		relevance:   "Common workflow service for incident, escalation, and on-call automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "postmark",
		displayName: "Postmark",
		aliases:     []string{"postmark api"},
		category:    "email",
		n8nNode:     "Postmark",
		relevance:   "Popular transactional email platform for messages, templates, servers, bounces, and delivery automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "posthog",
		displayName: "PostHog",
		aliases:     []string{"posthog api", "post hog"},
		category:    "product-analytics",
		n8nNode:     "PostHog",
		relevance:   "Popular product analytics platform for event capture, persons, cohorts, feature flags, insights, dashboards, surveys, and data warehouse automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "paypal",
		displayName: "PayPal",
		aliases:     []string{"paypal api", "paypal checkout"},
		category:    "payments",
		n8nNode:     "PayPal",
		relevance:   "Popular payment platform for checkout orders, captures, authorizations, subscriptions, payouts, and transaction automation.",
		userNeed:    UserOpenAPINeedPossible,
	}),
	workflowCandidate(candidateSeed{
		id:          "pipedrive",
		displayName: "Pipedrive",
		aliases:     []string{"pipedrive api", "pipedrive crm"},
		category:    "crm",
		n8nNode:     "Pipedrive",
		relevance:   "Popular CRM workflow service for deals, persons, organizations, activities, leads, products, and pipeline automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "quickbooks",
		displayName: "QuickBooks",
		aliases:     []string{"quickbooks api", "quickbooks online", "intuit quickbooks"},
		category:    "accounting",
		n8nNode:     "QuickBooks",
		relevance:   "Popular accounting platform for invoices, customers, bills, accounts, payments, and bookkeeping automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "salesforce",
		displayName: "Salesforce",
		aliases:     []string{"salesforce api", "salesforce crm"},
		category:    "crm",
		n8nNode:     "Salesforce",
		relevance:   "Popular CRM platform for leads, accounts, opportunities, and customer automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "seatable",
		displayName: "SeaTable",
		aliases:     []string{"seatable api", "sea table"},
		category:    "database",
		n8nNode:     "SeaTable",
		relevance:   "Popular spreadsheet-database platform for bases, rows, columns, files, links, metadata, and team automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "sendgrid",
		displayName: "SendGrid",
		aliases:     []string{"sendgrid api", "twilio sendgrid"},
		category:    "email",
		n8nNode:     "SendGrid",
		relevance:   "Popular workflow service for transactional email, templates, contacts, suppression lists, and email analytics.",
	}),
	workflowCandidate(candidateSeed{
		id:          "sentry",
		displayName: "Sentry",
		aliases:     []string{"sentry api", "sentry.io"},
		category:    "observability",
		n8nNode:     "SentryIo",
		relevance:   "Popular observability service for issues, events, releases, organizations, teams, and error-monitoring automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "servicenow",
		displayName: "ServiceNow",
		aliases:     []string{"servicenow api", "servicenow rest"},
		category:    "it-service-management",
		n8nNode:     "ServiceNow",
		relevance:   "Popular workflow service for incidents, users, tables, service catalog, change records, and ITSM automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "shopify",
		displayName: "Shopify",
		aliases:     []string{"shopify api"},
		category:    "commerce",
		n8nNode:     "Shopify",
		relevance:   "Popular commerce platform for orders, products, customers, and storefront automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "slack",
		displayName: "Slack",
		aliases:     []string{"slack api"},
		category:    "messaging",
		fixture:     "slack.json",
		n8nNode:     "Slack",
		relevance:   "Common workflow service for messages, channels, and collaboration notifications.",
	}),
	workflowCandidate(candidateSeed{
		id:          "snowflake",
		displayName: "Snowflake",
		aliases:     []string{"snowflake api", "snowflake sql api"},
		category:    "data-platform",
		n8nNode:     "Snowflake",
		relevance:   "Popular data platform for SQL statements, warehouses, databases, schemas, tables, and analytics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "splunk",
		displayName: "Splunk",
		aliases:     []string{"splunk api", "splunk rest api"},
		category:    "observability",
		n8nNode:     "Splunk",
		relevance:   "Popular observability platform for searches, jobs, saved searches, alerts, users, and log analytics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "stripe",
		displayName: "Stripe",
		aliases:     []string{"stripe api"},
		category:    "payments",
		n8nNode:     "Stripe",
		relevance:   "Popular payment platform for customers, charges, invoices, subscriptions, and billing automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "supabase",
		displayName: "Supabase",
		aliases:     []string{"supabase api", "supabase management api"},
		category:    "backend-platform",
		n8nNode:     "Supabase",
		relevance:   "Popular backend platform for projects, databases, auth, storage, edge functions, and PostgREST data APIs.",
	}),
	workflowCandidate(candidateSeed{
		id:          "telegram",
		displayName: "Telegram",
		aliases:     []string{"telegram api", "telegram bot api"},
		category:    "messaging",
		n8nNode:     "Telegram",
		relevance:   "Popular messaging workflow service for bot messages, chats, updates, files, callbacks, and notifications.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "trello",
		displayName: "Trello",
		aliases:     []string{"trello api"},
		category:    "project-management",
		fixture:     "trello.json",
		n8nNode:     "Trello",
		relevance:   "Common workflow service for boards, lists, cards, and task automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "twilio",
		displayName: "Twilio",
		aliases:     []string{"twilio api", "twilio sms"},
		category:    "communications",
		n8nNode:     "Twilio",
		relevance:   "Popular workflow service for SMS, voice, messaging, phone numbers, and communication automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "todoist",
		displayName: "Todoist",
		aliases:     []string{"todoist api"},
		category:    "tasks",
		n8nNode:     "Todoist",
		relevance:   "Popular task-management service for tasks, projects, sections, labels, comments, and productivity automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "typeform",
		displayName: "Typeform",
		aliases:     []string{"typeform api"},
		category:    "forms",
		n8nNode:     "Typeform",
		relevance:   "Popular workflow service for forms, responses, webhooks, workspaces, themes, and survey automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "xero",
		displayName: "Xero",
		aliases:     []string{"xero api", "xero accounting"},
		category:    "accounting",
		n8nNode:     "Xero",
		relevance:   "Popular accounting platform for contacts, invoices, bills, payments, bank transactions, and finance automation.",
		userNeed:    UserOpenAPINeedPossible,
	}),
	workflowCandidate(candidateSeed{
		id:          "zoom",
		displayName: "Zoom",
		aliases:     []string{"zoom api", "zoom meetings"},
		category:    "communications",
		n8nNode:     "Zoom",
		relevance:   "Popular workflow service for meetings, webinars, recordings, users, and account automation.",
		userNeed:    UserOpenAPINeedPossible,
	}),
	workflowCandidate(candidateSeed{
		id:          "webflow",
		displayName: "Webflow",
		aliases:     []string{"webflow api", "webflow data api"},
		category:    "website-builder",
		n8nNode:     "Webflow",
		relevance:   "Popular website platform for sites, CMS collections, items, pages, forms, and web publishing automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "zendesk",
		displayName: "Zendesk",
		aliases:     []string{"zendesk api", "zendesk support"},
		category:    "customer-support",
		n8nNode:     "Zendesk",
		relevance:   "Popular workflow service for support tickets, users, organizations, messaging, and customer-service automation.",
	}),
	workflowCandidate(candidateSeed{
		id:          "acuity-scheduling",
		displayName: "Acuity Scheduling",
		aliases:     []string{"acuity", "acuity api", "acuity scheduling api"},
		category:    "scheduling",
		n8nNode:     "AcuityScheduling",
		relevance:   "Popular scheduling platform for appointments, availability, calendars, clients, and booking automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "bitly",
		displayName: "Bitly",
		aliases:     []string{"bitly api"},
		category:    "link-management",
		n8nNode:     "Bitly",
		relevance:   "Popular link-management service for shortening links, bitlinks, campaigns, groups, QR codes, and click metrics automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "brevo",
		displayName: "Brevo",
		aliases:     []string{"brevo api", "sendinblue"},
		category:    "email-marketing",
		n8nNode:     "Brevo",
		relevance:   "Popular customer messaging platform for contacts, email campaigns, transactional email, SMS, CRM, and marketing automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "clockify",
		displayName: "Clockify",
		aliases:     []string{"clockify api"},
		category:    "time-tracking",
		n8nNode:     "Clockify",
		relevance:   "Popular time-tracking platform for workspaces, projects, tasks, time entries, clients, and reporting automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "coda",
		displayName: "Coda",
		aliases:     []string{"coda api", "coda docs"},
		category:    "productivity",
		n8nNode:     "Coda",
		relevance:   "Popular docs and database platform for docs, pages, tables, rows, formulas, controls, and workspace automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "deepl",
		displayName: "DeepL",
		aliases:     []string{"deepl api", "deepl translate"},
		category:    "translation",
		n8nNode:     "DeepL",
		relevance:   "Popular language AI service for text translation, document translation, glossaries, usage, and language detection automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "figma",
		displayName: "Figma",
		aliases:     []string{"figma api", "figma rest api"},
		category:    "design",
		n8nNode:     "Figma",
		relevance:   "Popular design collaboration platform for files, comments, components, projects, variables, and webhook automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "ghost",
		displayName: "Ghost",
		aliases:     []string{"ghost api", "ghost admin api", "ghost cms"},
		category:    "cms",
		n8nNode:     "Ghost",
		relevance:   "Popular publishing CMS for posts, pages, tags, members, users, newsletters, and content automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "harvest",
		displayName: "Harvest",
		aliases:     []string{"harvest api", "harvestapp"},
		category:    "time-tracking",
		n8nNode:     "Harvest",
		relevance:   "Popular time-tracking and invoicing platform for users, projects, clients, time entries, expenses, and invoices automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "help-scout",
		displayName: "Help Scout",
		aliases:     []string{"helpscout", "help scout api", "helpscout api"},
		category:    "customer-support",
		n8nNode:     "HelpScout",
		relevance:   "Popular customer support platform for conversations, customers, mailboxes, docs articles, collections, and support workflow automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "iterable",
		displayName: "Iterable",
		aliases:     []string{"iterable api"},
		category:    "customer-engagement",
		n8nNode:     "Iterable",
		relevance:   "Popular customer engagement platform for users, events, campaigns, journeys, lists, templates, and messaging automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mailjet",
		displayName: "Mailjet",
		aliases:     []string{"mailjet api"},
		category:    "email",
		n8nNode:     "Mailjet",
		relevance:   "Popular email API platform for transactional sending, contacts, lists, campaigns, templates, and message statistics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "convertkit",
		displayName: "Kit (ConvertKit)",
		aliases:     []string{"convertkit api", "kit api", "kit email api"},
		category:    "email-marketing",
		n8nNode:     "ConvertKit",
		relevance:   "Popular creator marketing platform for subscribers, tags, forms, broadcasts, sequences, purchases, and webhook automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "copper",
		displayName: "Copper",
		aliases:     []string{"copper api", "copper crm", "copper crm api"},
		category:    "crm",
		n8nNode:     "Copper",
		relevance:   "Popular CRM for leads, people, companies, opportunities, projects, tasks, activities, custom fields, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "coingecko",
		displayName: "CoinGecko",
		aliases:     []string{"coingecko api", "coin gecko", "coingecko market data"},
		category:    "crypto-market-data",
		n8nNode:     "CoinGecko",
		relevance:   "Popular crypto market-data API for prices, coins, exchanges, categories, trending assets, and global market automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "hackernews",
		displayName: "Hacker News",
		aliases:     []string{"hacker news", "hackernews api", "hn api"},
		category:    "news",
		n8nNode:     "HackerNews",
		relevance:   "Popular public news data API for stories, items, users, and near-real-time update automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "marketstack",
		displayName: "Marketstack",
		aliases:     []string{"marketstack api", "market stack"},
		category:    "financial-market-data",
		n8nNode:     "Marketstack",
		relevance:   "Popular stock-market data API for end-of-day, intraday, ticker, exchange, currency, index, and market data automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "nasa",
		displayName: "NASA",
		aliases:     []string{"nasa api", "api.nasa.gov"},
		category:    "public-data",
		n8nNode:     "Nasa",
		relevance:   "Popular public science data APIs for astronomy pictures, Mars rover photos, near-earth objects, EPIC imagery, and NASA datasets.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "onesimpleapi",
		displayName: "OneSimpleApi",
		aliases:     []string{"one simple api", "onesimpleapi api"},
		category:    "utility-api",
		n8nNode:     "OneSimpleApi",
		relevance:   "Popular utility API toolkit for web page metadata, page status, screenshots, PDFs, QR codes, email validation, and URL tools.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "openthesaurus",
		displayName: "OpenThesaurus",
		aliases:     []string{"open thesaurus", "openthesaurus api"},
		category:    "language",
		n8nNode:     "OpenThesaurus",
		relevance:   "Popular public thesaurus API for German synonym lookup, similar-word suggestions, substring matches, JSON, and XML responses.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "quickchart",
		displayName: "QuickChart",
		aliases:     []string{"quickchart api", "quick chart"},
		category:    "data-visualization",
		n8nNode:     "QuickChart",
		relevance:   "Popular image-generation API for Chart.js charts, QR codes, graph visualizations, short URLs, and rendered chart assets.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "reddit",
		displayName: "Reddit",
		aliases:     []string{"reddit api"},
		category:    "social",
		n8nNode:     "Reddit",
		relevance:   "Popular social platform API for subreddits, posts, comments, users, listings, messages, moderation, and content automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "uptimerobot",
		displayName: "UptimeRobot",
		aliases:     []string{"uptime robot", "uptimerobot api", "uptime robot api"},
		category:    "monitoring",
		n8nNode:     "UptimeRobot",
		relevance:   "Popular uptime monitoring service for monitors, incidents, alert contacts, maintenance windows, public status pages, and uptime automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "autopilot",
		displayName: "Autopilot",
		aliases:     []string{"autopilot api", "autopilot journeys", "ortto autopilot"},
		category:    "marketing-automation",
		n8nNode:     "Autopilot",
		relevance:   "Popular legacy marketing automation platform for contacts, lists, journeys, triggers, and unsubscribe synchronization.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "drift",
		displayName: "Drift",
		aliases:     []string{"drift api", "drift conversations"},
		category:    "sales-engagement",
		n8nNode:     "Drift",
		relevance:   "Popular conversational marketing and sales platform for contacts, conversations, users, messages, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "freshworks-crm",
		displayName: "Freshworks CRM",
		aliases:     []string{"freshworks crm", "freshsales api", "freshworks crm api"},
		category:    "crm",
		n8nNode:     "FreshworksCrm",
		relevance:   "Popular CRM platform for contacts, accounts, deals, appointments, tasks, notes, sales activities, and search automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "getresponse",
		displayName: "GetResponse",
		aliases:     []string{"getresponse api", "get response"},
		category:    "email-marketing",
		n8nNode:     "GetResponse",
		relevance:   "Popular email marketing and automation platform for contacts, campaigns, newsletters, forms, tags, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "highlevel",
		displayName: "HighLevel",
		aliases:     []string{"gohighlevel", "go high level", "high level crm", "highlevel api", "leadconnector"},
		category:    "crm",
		n8nNode:     "HighLevel",
		relevance:   "Popular CRM and marketing automation platform for contacts, opportunities, calendars, users, workflows, locations, and marketplace apps.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "keap",
		displayName: "Keap",
		aliases:     []string{"keap api", "keap crm", "infusionsoft api"},
		category:    "crm",
		n8nNode:     "Keap",
		relevance:   "Popular CRM and small-business automation platform for contacts, companies, tags, notes, files, orders, products, and email automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mailerlite",
		displayName: "MailerLite",
		aliases:     []string{"mailerlite api", "mailer lite"},
		category:    "email-marketing",
		n8nNode:     "MailerLite",
		relevance:   "Popular email marketing platform for subscribers, groups, campaigns, automations, fields, segments, and webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "mautic",
		displayName: "Mautic",
		aliases:     []string{"mautic api", "mautic marketing"},
		category:    "marketing-automation",
		n8nNode:     "Mautic",
		relevance:   "Popular open-source marketing automation platform for contacts, companies, segments, campaigns, emails, and webhooks.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "monica-crm",
		displayName: "Monica CRM",
		aliases:     []string{"monica", "monica api", "monica crm api", "monicahq"},
		category:    "crm",
		n8nNode:     "MonicaCrm",
		relevance:   "Popular personal CRM for contacts, activities, notes, calls, reminders, tasks, tags, and relationship automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "salesmate",
		displayName: "Salesmate",
		aliases:     []string{"salesmate api", "salesmate crm"},
		category:    "crm",
		n8nNode:     "Salesmate",
		relevance:   "Popular CRM platform for contacts, companies, deals, activities, notes, products, and sales automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "sendy",
		displayName: "Sendy",
		aliases:     []string{"sendy api"},
		category:    "email-marketing",
		n8nNode:     "Sendy",
		relevance:   "Popular self-hosted email newsletter app for subscribers, lists, brands, campaigns, and bulk-email automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "vero",
		displayName: "Vero",
		aliases:     []string{"vero api", "vero track", "getvero"},
		category:    "customer-engagement",
		n8nNode:     "Vero",
		relevance:   "Popular customer engagement platform for user profiles, events, tags, campaigns, messages, and behavioral email automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "jotform",
		displayName: "JotForm",
		aliases:     []string{"jotform api", "jot form"},
		category:    "forms",
		n8nNode:     "JotForm",
		relevance:   "Popular form builder for forms, submissions, questions, reports, folders, and form webhook automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "formio",
		displayName: "Form.io",
		aliases:     []string{"form.io", "formio", "form io api"},
		category:    "forms",
		n8nNode:     "FormIo",
		relevance:   "Popular form and data-management platform for projects, forms, submissions, roles, and deployment automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "formstack",
		displayName: "Formstack",
		aliases:     []string{"formstack api", "formstack forms"},
		category:    "forms",
		n8nNode:     "Formstack",
		relevance:   "Popular online form platform for forms, submissions, fields, folders, webhooks, and response automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "surveymonkey",
		displayName: "SurveyMonkey",
		aliases:     []string{"survey monkey", "surveymonkey api"},
		category:    "forms",
		n8nNode:     "SurveyMonkey",
		relevance:   "Popular survey platform for surveys, collectors, respondents, responses, webhooks, and analytics automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "kobotoolbox",
		displayName: "KoBoToolbox",
		aliases:     []string{"kobo toolbox", "kobotoolbox api", "kobo api"},
		category:    "forms",
		n8nNode:     "KoBoToolbox",
		relevance:   "Popular humanitarian data-collection platform for projects, forms, submissions, exports, files, hooks, and permissions.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "bubble",
		displayName: "Bubble",
		aliases:     []string{"bubble api", "bubble.io", "bubble data api"},
		category:    "app-builder",
		n8nNode:     "Bubble",
		relevance:   "Popular no-code app builder for app-specific data APIs, workflow APIs, object types, and backend workflow automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "cal",
		displayName: "Cal.com",
		aliases:     []string{"cal.com", "cal api", "calcom"},
		category:    "scheduling",
		n8nNode:     "Cal",
		relevance:   "Popular scheduling platform for event types, bookings, calendars, webhooks, organizations, and availability automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "cockpit",
		displayName: "Cockpit",
		aliases:     []string{"cockpit cms", "cockpit api"},
		category:    "cms",
		n8nNode:     "Cockpit",
		relevance:   "Popular headless CMS for collections, singletons, assets, content items, and self-hosted content APIs.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "stackby",
		displayName: "Stackby",
		aliases:     []string{"stackby api", "stackby database"},
		category:    "database",
		n8nNode:     "Stackby",
		relevance:   "Popular no-code database platform for stacks, tables, rows, columns, views, and spreadsheet-style automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
	workflowCandidate(candidateSeed{
		id:          "airtop",
		displayName: "Airtop",
		aliases:     []string{"airtop api", "airtop browser"},
		category:    "browser-automation",
		n8nNode:     "Airtop",
		relevance:   "Popular AI browser automation platform for sessions, windows, files, agents, and browser interaction automation.",
		userNeed:    UserOpenAPINeedNotExpected,
	}),
	workflowCandidate(candidateSeed{
		id:          "timesaved",
		displayName: "TimeSaved",
		aliases:     []string{"time saved", "track time saved", "saved time"},
		category:    "workflow-metadata",
		n8nNode:     "TimeSaved",
		relevance:   "n8n workflow metadata helper for tracking estimated time saved during workflow execution; not an external provider API.",
		userNeed:    UserOpenAPINeedPossible,
	}),
	workflowCandidate(candidateSeed{
		id:          "filemaker",
		displayName: "FileMaker",
		aliases:     []string{"filemaker data api", "claris filemaker", "filemaker api"},
		category:    "database",
		n8nNode:     "FileMaker",
		relevance:   "Popular low-code database platform for layouts, records, scripts, containers, metadata, and hosted database automation.",
		userNeed:    UserOpenAPINeedLikely,
	}),
}

type candidateSeed struct {
	id              string
	displayName     string
	aliases         []string
	category        string
	fixture         string
	n8nNode         string
	relevance       string
	machineSpecKind string
	machineStatus   SpecStatus
	userNeed        UserOpenAPINeed
}

func workflowCandidate(seed candidateSeed) Candidate {
	machineStatus := seed.machineStatus
	if machineStatus == "" {
		machineStatus = SpecStatusUnknown
	}
	userNeed := seed.userNeed
	if userNeed == "" {
		userNeed = UserOpenAPINeedPossible
	}
	candidate := Candidate{
		ID:                        seed.id,
		DisplayName:               seed.displayName,
		Aliases:                   append([]string(nil), seed.aliases...),
		Category:                  seed.category,
		WorkflowRelevance:         seed.relevance,
		OfficialOpenAPIStatus:     SpecStatusNeedsVerification,
		OfficialMachineSpecStatus: machineStatus,
		OfficialMachineSpecKind:   seed.machineSpecKind,
		UserOpenAPINeed:           userNeed,
		AuthSecurityReview:        AuthSecurityNotReviewed,
	}
	if seed.fixture != "" {
		fixturePath := tryN8nSpecRoot + seed.fixture
		candidate.LocalOpenAPIFixture = fixturePath
		candidate.Evidence = append(candidate.Evidence, CandidateEvidence{
			Source: EvidenceTryN8nLocalFixture,
			Use:    EvidenceUseSeedFixture,
			Ref:    fixturePath,
			Note:   "Local OpenUdon advisory fixture; not treated as an official provider source.",
		})
	}
	if seed.n8nNode != "" {
		candidate.Evidence = append(candidate.Evidence, CandidateEvidence{
			Source: EvidenceN8nNodeDirectory,
			Use:    EvidenceUsePriority,
			Ref:    n8nNodeRoot + seed.n8nNode,
			Note:   "n8n built-in node presence is a prioritization signal only, not runtime compatibility evidence.",
		})
	}
	return candidate
}
