package catalog

const verifiedAt20260518 = "2026-05-18"

var builtInProviders = []Provider{
	providerCatalogEntry(providerSeed{
		id:                  "asana",
		displayName:         "Asana",
		aliases:             []string{"asana api"},
		category:            "project-management",
		relevance:           "Popular workflow service for task, project, and work-management automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "asana-openapi-v1",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "1.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:e698f9acf281833c71add9261f0f49f296da6003 etag:"60f0c277b59cdbc22c8e6e2aea2cfe2f61471fd4c2f7fa4bc3c41918f722bbec"`,
				LicenseNote:     "Asana OpenAPI document declares Apache 2.0 license metadata; provider documentation terms still apply to docs content.",
				SourceNote:      "Official Asana OpenAPI repository REST API specification.",
			},
			humanDocsRef("asana-api-docs", "https://developers.asana.com/docs/api-features", "Official Asana API documentation."),
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "airtable",
		displayName:         "Airtable",
		aliases:             []string{"airtable api"},
		category:            "database",
		relevance:           "Common workflow source and destination for records in bases and tables.",
		openAPIAvailability: SpecAvailabilityUnknown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("airtable-web-api-docs", "https://airtable.com/developers/web/api/introduction", "Official Airtable Web API documentation. No official OpenAPI document is recorded in this catalog entry yet."),
		},
		quirks: []string{"Base-specific Airtable schemas can vary by workspace and base; user-provided OpenAPI may be needed for precise field shapes."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "box",
		displayName:         "Box",
		aliases:             []string{"box api"},
		category:            "files",
		relevance:           "Popular workflow service for file storage, sharing, and content-management automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "box-platform-openapi-v3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/box/box-openapi/main/openapi.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "2024.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:f5fd732661ae7a6d066c71869a59d967e712ec46 etag:"ffe8e248eb770ca594c22fb94de1d5c2918967c51c206f967c3f5bbf1915c9be"`,
				LicenseNote:     "Box OpenAPI repository is licensed under Apache 2.0.",
				SourceNote:      "Official Box OpenAPI repository Platform API specification.",
			},
			humanDocsRef("box-api-docs", "https://developer.box.com/reference", "Official Box API reference documentation."),
		},
		quirks: []string{"Box introduced versioned public API specs in 2025; this catalog entry points at the compatibility openapi.json until version-specific imports are selected."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "calendly",
		displayName:         "Calendly",
		aliases:             []string{"calendly api"},
		category:            "scheduling",
		relevance:           "Popular workflow service for scheduling links, event types, scheduled events, invitees, and webhook automation.",
		openAPIAvailability: SpecAvailabilityUnknown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("calendly-public-api-docs", "https://developer.calendly.com/api-docs", "Official Calendly API reference. The portal points to Stoplight documentation, but this catalog entry records no downloadable official OpenAPI document."),
			humanDocsRef("calendly-getting-started", "https://developer.calendly.com/getting-started", "Official Calendly getting started documentation for API v2, Embed API, Webhook API, and authentication choices."),
		},
		quirks: []string{"Calendly's public API reference is hosted through Stoplight; routine export URL probes did not return a downloadable official OpenAPI document during M6 review."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "clickup",
		displayName:         "ClickUp",
		aliases:             []string{"clickup api"},
		category:            "project-management",
		relevance:           "Popular workflow service for tasks, lists, spaces, comments, time tracking, and webhook automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "clickup-api-v2-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://developer.clickup.com/openapi/clickup-api-v2-reference.json",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "2.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `etag:W/"7c42a-uezcTrdSAe2vPdIl5385zM6B37g" last-modified:"2026-04-13T18:48:51.118Z"`,
				LicenseNote:     "ClickUp developer documentation terms apply.",
				SourceNote:      "Official ClickUp ReadMe-hosted OpenAPI document for the API v2 reference.",
			},
			humanDocsRef("clickup-api-docs", "https://developer.clickup.com/docs/open-api-spec", "Official ClickUp OpenAPI specification documentation."),
			humanDocsRef("clickup-auth-docs", "https://developer.clickup.com/docs/authentication", "Official ClickUp authentication documentation."),
		},
		quirks: []string{"The OpenAPI document is version 3.1.0 and includes API v2 plus some API v3 endpoints; importers should preserve the source version and validate 3.1 compatibility."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "discord",
		displayName:         "Discord",
		aliases:             []string{"discord api"},
		category:            "messaging",
		relevance:           "Popular workflow service for channels, messages, guilds, users, webhooks, and bot automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "discord-api-v10-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "10",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:ac55939ed657bbb4b69cbe02e24abffc79223026 etag:"524df2b9a91744f69dda95bed995bed224bbdf8eea58581bf455c9deb2976bde"`,
				LicenseNote:     "Discord OpenAPI spec repository is licensed under MIT.",
				SourceNote:      "Official Discord OpenAPI specification repository standard v10 public API spec.",
			},
			humanDocsRef("discord-api-spec-readme", "https://github.com/discord/discord-api-spec", "Official Discord OpenAPI specification repository README."),
			humanDocsRef("discord-developer-docs", "https://discord.com/developers/docs/reference", "Official Discord Developer documentation."),
		},
		quirks: []string{"Discord labels the OpenAPI repository as a public preview subject to breaking changes and says to follow human docs if the spec and docs disagree."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "dropbox",
		displayName:         "Dropbox",
		aliases:             []string{"dropbox api"},
		category:            "files",
		relevance:           "Popular workflow service for file storage, upload, sharing, account, and team automation.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "dropbox-api-stone-spec",
				Kind:            SpecKindDropboxStone,
				URL:             "https://github.com/dropbox/dropbox-api-spec",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:6c68656caafdff65a30943fe186a1800b9f35bbc etag:"a8a20516da94ccdb9646bf2f346d0c72594c9bb333945d37deda7711e73a6701"`,
				LicenseNote:     "Dropbox API spec repository is licensed under MIT.",
				SourceNote:      "Official Dropbox API v2 Stone specification repository; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("dropbox-http-docs", "https://www.dropbox.com/developers/documentation/http/documentation", "Official Dropbox HTTP API documentation."),
			humanDocsRef("dropbox-oauth-guide", "https://developers.dropbox.com/oauth-guide", "Official Dropbox OAuth guide."),
		},
		quirks: []string{
			"Dropbox publishes its official API model as Stone files for SDK generation rather than OpenAPI; OpenAPI-only workflows need conversion or a user-supplied document.",
			"Dropbox API v2 uses RPC-style POST routes and separate content endpoints on content.dropboxapi.com for upload and download operations.",
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "github",
		displayName:         "GitHub",
		aliases:             []string{"github api", "github rest api"},
		category:            "developer-tools",
		relevance:           "Popular workflow service for repositories, issues, pull requests, releases, actions, and organization automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "github-rest-api-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "1.1.4",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:f5d3342150d3748e7307c81639635706f8338a12 etag:"aa909fe310291cfb22d6a2df6e77404d3eac954d13c9c590ebf19f12fc4f23dd"`,
				LicenseNote:     "github/rest-api-description is licensed under MIT.",
				SourceNote:      "Official GitHub REST API OpenAPI description bundled artifact for api.github.com.",
			},
			humanDocsRef("github-rest-docs", "https://docs.github.com/rest", "Official GitHub REST API documentation."),
			humanDocsRef("github-rest-auth-docs", "https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api", "Official GitHub REST API authentication documentation."),
		},
		quirks: []string{
			"GitHub's official OpenAPI description omits security schemes and security requirements; use catalog security overlay metadata when importing it.",
			"The stable 3.0 bundled description is preferred for broad tool compatibility; the repository also publishes 3.1 descriptions under descriptions-next with breaking-change caveats.",
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "gitlab",
		displayName:         "GitLab",
		aliases:             []string{"gitlab api", "gitlab rest api"},
		category:            "developer-tools",
		relevance:           "Popular workflow service for repositories, merge requests, issues, CI/CD, packages, and group automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "gitlab-openapi-v2",
				Kind:            SpecKindOpenAPI,
				URL:             "https://gitlab.com/gitlab-org/gitlab/-/raw/master/doc/api/openapi/openapi_v2.yaml",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "Swagger 2.0 / GitLab API v4",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:3ef57e7c312105c20fce8b97e5ddc4c60f2d23ed etag:"e323de391385feb39b68ed1d45e56fde" sha256:a492e61c70ffee4ce3b9770e77c9b2187bd9b6b81317fe826355583aae618cf6`,
				LicenseNote:     "GitLab doc/ content is licensed under Creative Commons CC BY-SA 4.0; GitLab repository license applies to generated source artifacts.",
				SourceNote:      "Official GitLab REST API Swagger/OpenAPI v2 YAML generated from the GitLab project.",
			},
			humanDocsRef("gitlab-openapi-docs", "https://docs.gitlab.com/api/openapi/openapi_interactive/", "Official GitLab interactive OpenAPI documentation."),
			humanDocsRef("gitlab-rest-auth-docs", "https://docs.gitlab.com/api/rest/authentication/", "Official GitLab REST API authentication documentation."),
		},
		quirks: []string{
			"GitLab docs state that only some API endpoints are documented with the OpenAPI spec, so user-provided OpenAPI may still be useful for uncovered workflow surfaces.",
			"The official YAML is Swagger 2.0 and includes token security definitions but no root security requirement.",
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "gmail",
		displayName:         "Gmail",
		aliases:             []string{"google mail", "gmail api"},
		category:            "email",
		relevance:           "Common workflow service for reading, sending, and routing email messages.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "gmail-discovery-v1",
				Kind:            SpecKindGoogleDiscovery,
				URL:             "https://gmail.googleapis.com/$discovery/rest?version=v1",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v1",
				VerifiedAt:      verifiedAt20260518,
				LicenseNote:     "Google Developers Site Policies apply to documentation and code samples.",
				SourceNote:      "Official Gmail API Discovery document; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("gmail-rest-docs", "https://developers.google.com/workspace/gmail/api/reference/rest", "Official Gmail API REST reference."),
		},
		quirks: []string{"Google Discovery documents are not OpenAPI and need conversion or a user-supplied OpenAPI document for OpenAPI-only workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "google-calendar",
		displayName:         "Google Calendar",
		aliases:             []string{"calendar", "google calendar api"},
		category:            "scheduling",
		relevance:           "Popular workflow service for calendar lists, calendars, events, invitations, and scheduling automation.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "calendar-discovery-v3",
				Kind:            SpecKindGoogleDiscovery,
				URL:             "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v3",
				VerifiedAt:      verifiedAt20260518,
				Revision:        "revision:20260510",
				LicenseNote:     "Google Developers Site Policies apply to documentation and code samples.",
				SourceNote:      "Official Google Calendar API Discovery document; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("calendar-rest-docs", "https://developers.google.com/workspace/calendar/api/v3/reference", "Official Google Calendar API v3 REST reference."),
			humanDocsRef("calendar-auth-scopes", "https://developers.google.com/workspace/calendar/api/auth", "Official Google Calendar API OAuth scope documentation."),
		},
		quirks: []string{"Google Discovery documents are not OpenAPI and need conversion or a user-supplied OpenAPI document for OpenAPI-only workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "google-drive",
		displayName:         "Google Drive",
		aliases:             []string{"drive", "google drive api"},
		category:            "files",
		relevance:           "Common workflow service for file storage, upload, search, and sharing.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "drive-discovery-v3",
				Kind:            SpecKindGoogleDiscovery,
				URL:             "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v3",
				VerifiedAt:      verifiedAt20260518,
				LicenseNote:     "Google Developers Site Policies apply to documentation and code samples.",
				SourceNote:      "Official Google Drive API Discovery document; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("drive-rest-docs", "https://developers.google.com/drive/api/reference/rest/v3", "Official Google Drive API v3 REST reference."),
		},
		quirks: []string{"Google Discovery documents are not OpenAPI and need conversion or a user-supplied OpenAPI document for OpenAPI-only workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "hubspot",
		displayName:         "HubSpot",
		aliases:             []string{"hubspot crm", "hubspot api"},
		category:            "crm",
		relevance:           "Common workflow service for CRM records, tickets, contacts, and pipeline automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "hubspot-public-api-spec-index",
				Kind:            SpecKindOpenAPIIndex,
				URL:             "https://api.hubapi.com/public/api/spec/v1/specs",
				SourceAuthority: SourceAuthorityOfficialProvider,
				VerifiedAt:      verifiedAt20260518,
				LicenseNote:     "HubSpot public API spec repository notes proprietary specifications and directs external developers to official API documentation.",
				SourceNote:      "Official HubSpot public API spec index endpoint; references multiple OpenAPI documents rather than one monolithic spec.",
			},
			humanDocsRef("hubspot-api-docs", "https://developers.hubspot.com/docs/reference/api", "Official HubSpot API reference documentation."),
		},
		quirks: []string{"HubSpot specs are split across API groups and versions; callers should select a specific spec from the index before import."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "jira-cloud",
		displayName:         "Jira Cloud",
		aliases:             []string{"jira", "atlassian jira", "jira api"},
		category:            "project-management",
		relevance:           "Common workflow service for issue tracking and project automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "jira-cloud-platform-openapi-v3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://dac-static.atlassian.com/cloud/jira/platform/swagger-v3.v3.json",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v3",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `etag:"e6c0034518a2ce0a4005e9f04d23a0d8"`,
				LicenseNote:     "Atlassian developer documentation terms apply.",
				SourceNote:      "Atlassian-hosted Jira Cloud platform OpenAPI document.",
			},
			humanDocsRef("jira-cloud-rest-docs", "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/", "Official Jira Cloud platform REST API documentation."),
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "openweathermap",
		displayName:         "OpenWeatherMap",
		aliases:             []string{"open weather map", "openweathermap api"},
		category:            "weather",
		relevance:           "Common workflow data source for current weather and forecast enrichment.",
		openAPIAvailability: SpecAvailabilityUnknown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("openweathermap-api-docs", "https://openweathermap.org/api", "Official OpenWeather API documentation. No official OpenAPI document is recorded in this catalog entry yet."),
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "pagerduty",
		displayName:         "PagerDuty",
		aliases:             []string{"pagerduty api"},
		category:            "incident-management",
		relevance:           "Common workflow service for incident, escalation, and on-call automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "pagerduty-rest-openapi-v3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				VerifiedAt:      verifiedAt20260518,
				Revision:        "repo:fbfcadd0ec95e0e08fdb0fe013baa0b713fa13ab blob:b0cb8abda0635d34f10be108694b929afd2ac463",
				LicenseNote:     "No release license is recorded in this catalog entry; review repository terms before vendoring.",
				SourceNote:      "Official PagerDuty API schema repository OpenAPI document for REST APIs.",
			},
			humanDocsRef("pagerduty-api-docs", "https://developer.pagerduty.com/api-reference/", "Official PagerDuty API reference documentation."),
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "slack",
		displayName:         "Slack",
		aliases:             []string{"slack api"},
		category:            "messaging",
		relevance:           "Common workflow service for messages, channels, and collaboration notifications.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "slack-web-openapi-v2",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2_without_examples.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "OpenAPI 2.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        "repo:bc08db49625630e3585bf2f1322128ea04f2a7f3 blob:f7b1affd1fb34f9473cd87980428883019b29c07",
				LicenseNote:     "Repository license applies; repository is archived and read-only.",
				SourceNote:      "Official Slack API specs repository Web API OpenAPI document; repository was archived by its owner in 2024.",
			},
			humanDocsRef("slack-web-api-docs", "https://docs.slack.dev/apis/web-api", "Official Slack Web API documentation."),
		},
		quirks: []string{"The official Slack OpenAPI repository is archived, so freshness should be checked against current Slack docs before import."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "trello",
		displayName:         "Trello",
		aliases:             []string{"trello api"},
		category:            "project-management",
		relevance:           "Common workflow service for boards, lists, cards, and task automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "trello-cloud-openapi-v3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://dac-static.atlassian.com/cloud/trello/swagger.v3.json",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v3",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `etag:"c4c69e7449085c4ef83e72a4b0344dfa"`,
				LicenseNote:     "Atlassian developer documentation terms apply.",
				SourceNote:      "Atlassian-hosted Trello Cloud OpenAPI document.",
			},
			humanDocsRef("trello-rest-docs", "https://developer.atlassian.com/cloud/trello/rest/", "Official Trello REST API documentation."),
		},
		quirks: []string{"Trello authentication and token flows may require supplemental security review before downstream use."},
	}),
}

type providerSeed struct {
	id                  string
	displayName         string
	aliases             []string
	category            string
	relevance           string
	openAPIAvailability SpecAvailability
	machineAvailability SpecAvailability
	userNeed            UserOpenAPINeed
	specs               []SpecReference
	quirks              []string
}

func providerCatalogEntry(seed providerSeed) Provider {
	return Provider{
		ID:                              seed.id,
		DisplayName:                     seed.displayName,
		Aliases:                         append([]string(nil), seed.aliases...),
		Category:                        seed.category,
		WorkflowRelevance:               seed.relevance,
		SourceHints:                     []string{"promoted-from-m2-candidate"},
		ReviewState:                     ProviderReviewedCatalogEntry,
		CandidateID:                     seed.id,
		OfficialOpenAPIAvailability:     seed.openAPIAvailability,
		OfficialMachineSpecAvailability: seed.machineAvailability,
		UserOpenAPINeed:                 seed.userNeed,
		SpecReferences:                  append([]SpecReference(nil), seed.specs...),
		Quirks:                          append([]string(nil), seed.quirks...),
	}
}

func humanDocsRef(id, url, note string) SpecReference {
	return SpecReference{
		ID:              id,
		Kind:            SpecKindHumanDocs,
		URL:             url,
		SourceAuthority: SourceAuthorityOfficialDocs,
		VerifiedAt:      verifiedAt20260518,
		LicenseNote:     "Provider documentation terms apply.",
		SourceNote:      note,
	}
}
