package catalog

const verifiedAt20260518 = "2026-05-18"

var builtInProviders = []Provider{
	providerCatalogEntry(providerSeed{
		id:                  "asana",
		displayName:         "Asana",
		aliases:             []string{"asana api"},
		category:            "project-management",
		relevance:           "Popular workflow service for task, project, and work-management automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "asana-openapi-v1",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "1.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:e698f9acf281833c71add9261f0f49f296da6003 etag:"60f0c277b59cdbc22c8e6e2aea2cfe2f61471fd4c2f7fa4bc3c41918f722bbec"`,
				LicenseNote:     "Asana OpenAPI document declares Apache 2.0 license metadata; provider documentation terms still apply to docs content.",
				SourceNote:      "Official Asana OpenAPI repository REST API specification.",
			},
			humanDocsRef("asana-api-docs", "https://developers.asana.com/docs/api-features", "Official Asana API documentation."),
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "airtable",
		displayName:         "Airtable",
		aliases:             []string{"airtable api"},
		category:            "database",
		relevance:           "Common workflow source and destination for records in bases and tables.",
		openAPIAvailability: SpecAvailabilityUnknown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("airtable-web-api-docs", "https://airtable.com/developers/web/api/introduction", "Official Airtable Web API documentation. No official OpenAPI document is recorded in this catalog entry yet."),
		},
		quirks: []string{"Base-specific Airtable schemas can vary by workspace and base; user-provided OpenAPI may be needed for precise field shapes."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "box",
		displayName:         "Box",
		aliases:             []string{"box api"},
		category:            "files",
		relevance:           "Popular workflow service for file storage, sharing, and content-management automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "box-platform-openapi-v3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/box/box-openapi/main/openapi.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "2024.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:f5fd732661ae7a6d066c71869a59d967e712ec46 etag:"ffe8e248eb770ca594c22fb94de1d5c2918967c51c206f967c3f5bbf1915c9be"`,
				LicenseNote:     "Box OpenAPI repository is licensed under Apache 2.0.",
				SourceNote:      "Official Box OpenAPI repository Platform API specification.",
			},
			humanDocsRef("box-api-docs", "https://developer.box.com/reference", "Official Box API reference documentation."),
		},
		quirks: []string{"Box introduced versioned public API specs in 2025; this catalog entry points at the compatibility openapi.json until version-specific imports are selected."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "calendly",
		displayName:         "Calendly",
		aliases:             []string{"calendly api"},
		category:            "scheduling",
		relevance:           "Popular workflow service for scheduling links, event types, scheduled events, invitees, and webhook automation.",
		openAPIAvailability: SpecAvailabilityUnknown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("calendly-public-api-docs", "https://developer.calendly.com/api-docs", "Official Calendly API reference. The portal points to Stoplight documentation, but this catalog entry records no downloadable official OpenAPI document."),
			humanDocsRef("calendly-getting-started", "https://developer.calendly.com/getting-started", "Official Calendly getting started documentation for API v2, Embed API, Webhook API, and authentication choices."),
		},
		quirks: []string{"Calendly's public API reference is hosted through Stoplight; routine export URL probes did not return a downloadable official OpenAPI document during M6 review."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "clickup",
		displayName:         "ClickUp",
		aliases:             []string{"clickup api"},
		category:            "project-management",
		relevance:           "Popular workflow service for tasks, lists, spaces, comments, time tracking, and webhook automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "clickup-api-v2-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://developer.clickup.com/openapi/clickup-api-v2-reference.json",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "2.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `etag:W/"7c42a-uezcTrdSAe2vPdIl5385zM6B37g" last-modified:"2026-04-13T18:48:51.118Z"`,
				LicenseNote:     "ClickUp developer documentation terms apply.",
				SourceNote:      "Official ClickUp ReadMe-hosted OpenAPI document for the API v2 reference.",
			},
			humanDocsRef("clickup-api-docs", "https://developer.clickup.com/docs/open-api-spec", "Official ClickUp OpenAPI specification documentation."),
			humanDocsRef("clickup-auth-docs", "https://developer.clickup.com/docs/authentication", "Official ClickUp authentication documentation."),
		},
		quirks: []string{"The OpenAPI document is version 3.1.0 and includes API v2 plus some API v3 endpoints; importers should preserve the source version and validate 3.1 compatibility."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "discord",
		displayName:         "Discord",
		aliases:             []string{"discord api"},
		category:            "messaging",
		relevance:           "Popular workflow service for channels, messages, guilds, users, webhooks, and bot automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "discord-api-v10-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "10",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:ac55939ed657bbb4b69cbe02e24abffc79223026 etag:"524df2b9a91744f69dda95bed995bed224bbdf8eea58581bf455c9deb2976bde"`,
				LicenseNote:     "Discord OpenAPI spec repository is licensed under MIT.",
				SourceNote:      "Official Discord OpenAPI specification repository standard v10 public API spec.",
			},
			humanDocsRef("discord-api-spec-readme", "https://github.com/discord/discord-api-spec", "Official Discord OpenAPI specification repository README."),
			humanDocsRef("discord-developer-docs", "https://discord.com/developers/docs/reference", "Official Discord Developer documentation."),
		},
		quirks: []string{"Discord labels the OpenAPI repository as a public preview subject to breaking changes and says to follow human docs if the spec and docs disagree."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "dropbox",
		displayName:         "Dropbox",
		aliases:             []string{"dropbox api"},
		category:            "files",
		relevance:           "Popular workflow service for file storage, upload, sharing, account, and team automation.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "dropbox-api-stone-spec",
				Kind:            SpecKindDropboxStone,
				URL:             "https://github.com/dropbox/dropbox-api-spec",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:6c68656caafdff65a30943fe186a1800b9f35bbc etag:"a8a20516da94ccdb9646bf2f346d0c72594c9bb333945d37deda7711e73a6701"`,
				LicenseNote:     "Dropbox API spec repository is licensed under MIT.",
				SourceNote:      "Official Dropbox API v2 Stone specification repository; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("dropbox-http-docs", "https://www.dropbox.com/developers/documentation/http/documentation", "Official Dropbox HTTP API documentation."),
			humanDocsRef("dropbox-oauth-guide", "https://developers.dropbox.com/oauth-guide", "Official Dropbox OAuth guide."),
		},
		quirks: []string{
			"Dropbox publishes its official API model as Stone files for SDK generation rather than OpenAPI; OpenAPI-only workflows need conversion or a user-supplied document.",
			"Dropbox API v2 uses RPC-style POST routes and separate content endpoints on content.dropboxapi.com for upload and download operations.",
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "github",
		displayName:         "GitHub",
		aliases:             []string{"github api", "github rest api"},
		category:            "developer-tools",
		relevance:           "Popular workflow service for repositories, issues, pull requests, releases, actions, and organization automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "github-rest-api-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "1.1.4",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:f5d3342150d3748e7307c81639635706f8338a12 etag:"aa909fe310291cfb22d6a2df6e77404d3eac954d13c9c590ebf19f12fc4f23dd"`,
				LicenseNote:     "github/rest-api-description is licensed under MIT.",
				SourceNote:      "Official GitHub REST API OpenAPI description bundled artifact for api.github.com.",
			},
			humanDocsRef("github-rest-docs", "https://docs.github.com/rest", "Official GitHub REST API documentation."),
			humanDocsRef("github-rest-auth-docs", "https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api", "Official GitHub REST API authentication documentation."),
		},
		quirks: []string{
			"GitHub's official OpenAPI description omits security schemes and security requirements; use catalog security overlay metadata when importing it.",
			"The stable 3.0 bundled description is preferred for broad tool compatibility; the repository also publishes 3.1 descriptions under descriptions-next with breaking-change caveats.",
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "gitlab",
		displayName:         "GitLab",
		aliases:             []string{"gitlab api", "gitlab rest api"},
		category:            "developer-tools",
		relevance:           "Popular workflow service for repositories, merge requests, issues, CI/CD, packages, and group automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "gitlab-openapi-v2",
				Kind:            SpecKindOpenAPI,
				URL:             "https://gitlab.com/gitlab-org/gitlab/-/raw/master/doc/api/openapi/openapi_v2.yaml",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "Swagger 2.0 / GitLab API v4",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:3ef57e7c312105c20fce8b97e5ddc4c60f2d23ed etag:"e323de391385feb39b68ed1d45e56fde" sha256:a492e61c70ffee4ce3b9770e77c9b2187bd9b6b81317fe826355583aae618cf6`,
				LicenseNote:     "GitLab doc/ content is licensed under Creative Commons CC BY-SA 4.0; GitLab repository license applies to generated source artifacts.",
				SourceNote:      "Official GitLab REST API Swagger/OpenAPI v2 YAML generated from the GitLab project.",
			},
			humanDocsRef("gitlab-openapi-docs", "https://docs.gitlab.com/api/openapi/openapi_interactive/", "Official GitLab interactive OpenAPI documentation."),
			humanDocsRef("gitlab-rest-auth-docs", "https://docs.gitlab.com/api/rest/authentication/", "Official GitLab REST API authentication documentation."),
		},
		quirks: []string{
			"GitLab docs state that only some API endpoints are documented with the OpenAPI spec, so user-provided OpenAPI may still be useful for uncovered workflow surfaces.",
			"The official YAML is Swagger 2.0 and includes token security definitions but no root security requirement.",
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "gmail",
		displayName:         "Gmail",
		aliases:             []string{"google mail", "gmail api"},
		category:            "email",
		relevance:           "Common workflow service for reading, sending, and routing email messages.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "gmail-discovery-v1",
				Kind:            SpecKindGoogleDiscovery,
				URL:             "https://gmail.googleapis.com/$discovery/rest?version=v1",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v1",
				VerifiedAt:      verifiedAt20260518,
				LicenseNote:     "Google Developers Site Policies apply to documentation and code samples.",
				SourceNote:      "Official Gmail API Discovery document; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("gmail-rest-docs", "https://developers.google.com/workspace/gmail/api/reference/rest", "Official Gmail API REST reference."),
		},
		quirks: []string{"Google Discovery documents are not OpenAPI and need conversion or a user-supplied OpenAPI document for OpenAPI-only workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "google-calendar",
		displayName:         "Google Calendar",
		aliases:             []string{"calendar", "google calendar api"},
		category:            "scheduling",
		relevance:           "Popular workflow service for calendar lists, calendars, events, invitations, and scheduling automation.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "calendar-discovery-v3",
				Kind:            SpecKindGoogleDiscovery,
				URL:             "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v3",
				VerifiedAt:      verifiedAt20260518,
				Revision:        "revision:20260510",
				LicenseNote:     "Google Developers Site Policies apply to documentation and code samples.",
				SourceNote:      "Official Google Calendar API Discovery document; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("calendar-rest-docs", "https://developers.google.com/workspace/calendar/api/v3/reference", "Official Google Calendar API v3 REST reference."),
			humanDocsRef("calendar-auth-scopes", "https://developers.google.com/workspace/calendar/api/auth", "Official Google Calendar API OAuth scope documentation."),
		},
		quirks: []string{"Google Discovery documents are not OpenAPI and need conversion or a user-supplied OpenAPI document for OpenAPI-only workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "google-drive",
		displayName:         "Google Drive",
		aliases:             []string{"drive", "google drive api"},
		category:            "files",
		relevance:           "Common workflow service for file storage, upload, search, and sharing.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "drive-discovery-v3",
				Kind:            SpecKindGoogleDiscovery,
				URL:             "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v3",
				VerifiedAt:      verifiedAt20260518,
				LicenseNote:     "Google Developers Site Policies apply to documentation and code samples.",
				SourceNote:      "Official Google Drive API Discovery document; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("drive-rest-docs", "https://developers.google.com/drive/api/reference/rest/v3", "Official Google Drive API v3 REST reference."),
		},
		quirks: []string{"Google Discovery documents are not OpenAPI and need conversion or a user-supplied OpenAPI document for OpenAPI-only workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "google-sheets",
		displayName:         "Google Sheets",
		aliases:             []string{"sheets", "google sheets api"},
		category:            "spreadsheet",
		relevance:           "Popular workflow service for spreadsheet reads, writes, appends, and batch updates.",
		openAPIAvailability: SpecAvailabilityUnavailable,
		machineAvailability: SpecAvailabilityKnown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			{
				ID:              "sheets-discovery-v4",
				Kind:            SpecKindGoogleDiscovery,
				URL:             "https://sheets.googleapis.com/$discovery/rest?version=v4",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v4",
				VerifiedAt:      verifiedAt20260518,
				Revision:        "revision:20260511",
				LicenseNote:     "Google Developers Site Policies apply to documentation and code samples.",
				SourceNote:      "Official Google Sheets API Discovery document; it is machine-readable but not OpenAPI.",
			},
			humanDocsRef("sheets-rest-docs", "https://developers.google.com/workspace/sheets/api/reference/rest", "Official Google Sheets API v4 REST reference."),
			humanDocsRef("sheets-auth-scopes", "https://developers.google.com/workspace/sheets/api/scopes", "Official Google Sheets API OAuth scope documentation."),
		},
		quirks: []string{"Google Discovery documents are not OpenAPI and need conversion or a user-supplied OpenAPI document for OpenAPI-only workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "hubspot",
		displayName:         "HubSpot",
		aliases:             []string{"hubspot crm", "hubspot api"},
		category:            "crm",
		relevance:           "Common workflow service for CRM records, tickets, contacts, and pipeline automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "hubspot-public-api-spec-index",
				Kind:            SpecKindOpenAPIIndex,
				URL:             "https://api.hubapi.com/public/api/spec/v1/specs",
				SourceAuthority: SourceAuthorityOfficialProvider,
				VerifiedAt:      verifiedAt20260518,
				LicenseNote:     "HubSpot public API spec repository notes proprietary specifications and directs external developers to official API documentation.",
				SourceNote:      "Official HubSpot public API spec index endpoint; references multiple OpenAPI documents rather than one monolithic spec.",
			},
			humanDocsRef("hubspot-api-docs", "https://developers.hubspot.com/docs/reference/api", "Official HubSpot API reference documentation."),
		},
		quirks: []string{"HubSpot specs are split across API groups and versions; callers should select a specific spec from the index before import."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "jira-cloud",
		displayName:         "Jira Cloud",
		aliases:             []string{"jira", "atlassian jira", "jira api"},
		category:            "project-management",
		relevance:           "Common workflow service for issue tracking and project automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "jira-cloud-platform-openapi-v3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://dac-static.atlassian.com/cloud/jira/platform/swagger-v3.v3.json",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v3",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `etag:"e6c0034518a2ce0a4005e9f04d23a0d8"`,
				LicenseNote:     "Atlassian developer documentation terms apply.",
				SourceNote:      "Atlassian-hosted Jira Cloud platform OpenAPI document.",
			},
			humanDocsRef("jira-cloud-rest-docs", "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/", "Official Jira Cloud platform REST API documentation."),
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "mailchimp",
		displayName:         "Mailchimp",
		aliases:             []string{"mailchimp api", "mailchimp marketing"},
		category:            "email-marketing",
		relevance:           "Popular workflow service for audiences, contacts, campaigns, templates, reports, and marketing automation.",
		openAPIAvailability: SpecAvailabilityNeedsVerification,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("mailchimp-marketing-api-docs", "https://mailchimp.com/developer/marketing/api/", "Official Mailchimp Marketing API reference documentation. Mailchimp states the API uses OpenAPI for endpoint descriptions, but this catalog entry records no stable public downloadable OpenAPI document yet."),
			humanDocsRef("mailchimp-marketing-fundamentals", "https://mailchimp.com/developer/marketing/docs/fundamentals/", "Official Mailchimp Marketing API fundamentals documentation."),
			humanDocsRef("mailchimp-marketing-auth-docs", "https://mailchimp.com/developer/marketing/guides/quick-start/", "Official Mailchimp Marketing API quick start and authentication documentation."),
		},
		quirks: []string{"Mailchimp documentation says the Marketing API uses OpenAPI endpoint descriptions, but a stable public downloadable OpenAPI document is not recorded in this catalog entry."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "microsoft-graph",
		displayName:         "Microsoft Graph",
		aliases:             []string{"graph", "microsoft graph api", "ms graph"},
		category:            "productivity",
		relevance:           "Popular workflow platform for Microsoft 365 users, mail, calendar, files, groups, Teams, and directory automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "microsoft-graph-v1-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "v1.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:ecfbb0d49b8bf7f7cb13310726a5feb3697dd42f etag:"cd695e01b812ea837a64b212571aaa4c55bbb82b2afff6459226cb22dfddc0ac"`,
				LicenseNote:     "Microsoft Graph metadata repository license applies.",
				SourceNote:      "Official Microsoft Graph metadata repository OpenAPI v1.0 document.",
			},
			humanDocsRef("microsoft-graph-docs", "https://learn.microsoft.com/en-us/graph/overview", "Official Microsoft Graph documentation."),
			humanDocsRef("microsoft-graph-auth-docs", "https://learn.microsoft.com/en-us/graph/auth/auth-concepts", "Official Microsoft Graph authentication and authorization documentation."),
		},
		quirks: []string{"The Microsoft Graph v1.0 OpenAPI document is very large and lacks OpenAPI security schemes; importers should use catalog auth overlay metadata and preserve source path-backed caching."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "notion",
		displayName:         "Notion",
		aliases:             []string{"notion api"},
		category:            "knowledge-management",
		relevance:           "Popular workflow service for pages, databases, blocks, comments, users, and workspace content automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "notion-api-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://developers.notion.com/openapi.json",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "1.0.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `etag:"29e9233867e3c30bebacfc8eeadcdf13" last-modified:"Fri, 15 May 2026 19:55:18 GMT" served-version:"29e9233867e3c30bebacfc8eeadcdf13"`,
				LicenseNote:     "Notion developer documentation terms apply.",
				SourceNote:      "Official Notion API OpenAPI document hosted by Notion developer documentation.",
			},
			humanDocsRef("notion-api-docs", "https://developers.notion.com/reference/intro", "Official Notion API reference introduction."),
			humanDocsRef("notion-auth-docs", "https://developers.notion.com/reference/authentication", "Official Notion API authentication documentation."),
		},
		quirks: []string{"Notion API requests require a Notion-Version header; the official OpenAPI should be checked for the desired Notion API version before downstream use."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "okta",
		displayName:         "Okta",
		aliases:             []string{"okta api", "okta management"},
		category:            "identity",
		relevance:           "Popular identity platform for users, groups, applications, events, and organization administration automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "okta-management-minimal-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/okta/okta-management-openapi-spec/master/dist/current/management-minimal.yaml",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "2026.03.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:fd9b9f83033648bd98bb6ba4a4b70a75b761eebc etag:"3cd725c9f3a8cfdac6839525111bbf2f5894473e22ce498f2348fb0afe7fa7c6"`,
				LicenseNote:     "Okta Management OpenAPI document declares Apache 2.0 license metadata; Okta developer documentation terms still apply to docs content.",
				SourceNote:      "Official Okta Management OpenAPI repository current minimal OpenAPI v3 specification.",
			},
			humanDocsRef("okta-management-openapi-repo", "https://github.com/okta/okta-management-openapi-spec", "Official Okta Management OpenAPI specification repository."),
			humanDocsRef("okta-management-api-docs", "https://developer.okta.com/docs/api/openapi/okta-management/guides/overview/", "Official Okta Management API documentation and authentication overview."),
		},
		quirks: []string{"Okta publishes a large current OpenAPI tree plus historical release snapshots; this catalog entry records the current minimal Management API artifact for broad importer compatibility."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "openweathermap",
		displayName:         "OpenWeatherMap",
		aliases:             []string{"open weather map", "openweathermap api"},
		category:            "weather",
		relevance:           "Common workflow data source for current weather and forecast enrichment.",
		openAPIAvailability: SpecAvailabilityUnknown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("openweathermap-api-docs", "https://openweathermap.org/api", "Official OpenWeather API documentation. No official OpenAPI document is recorded in this catalog entry yet."),
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "pagerduty",
		displayName:         "PagerDuty",
		aliases:             []string{"pagerduty api"},
		category:            "incident-management",
		relevance:           "Common workflow service for incident, escalation, and on-call automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "pagerduty-rest-openapi-v3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				VerifiedAt:      verifiedAt20260518,
				Revision:        "repo:fbfcadd0ec95e0e08fdb0fe013baa0b713fa13ab blob:b0cb8abda0635d34f10be108694b929afd2ac463",
				LicenseNote:     "No release license is recorded in this catalog entry; review repository terms before vendoring.",
				SourceNote:      "Official PagerDuty API schema repository OpenAPI document for REST APIs.",
			},
			humanDocsRef("pagerduty-api-docs", "https://developer.pagerduty.com/api-reference/", "Official PagerDuty API reference documentation."),
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "paypal",
		displayName:         "PayPal",
		aliases:             []string{"paypal api", "paypal checkout"},
		category:            "payments",
		relevance:           "Popular payment platform for checkout orders, captures, authorizations, subscriptions, payouts, and transaction automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "paypal-checkout-orders-v2-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/paypal/paypal-rest-api-specifications/main/openapi/checkout_orders_v2.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "2.32",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:90e8041ffe02d80c452d2b476bedd59a8d219bdc etag:"f213ea3dbb242ec9e6823e5f3e4f744960027a28c81c21eb9f224677067dcf43"`,
				LicenseNote:     "PayPal REST API specifications repository is licensed under Apache 2.0.",
				SourceNote:      "Official PayPal REST API specifications repository OpenAPI document for Checkout Orders v2.",
			},
			humanDocsRef("paypal-rest-api-specs-repo", "https://github.com/paypal/paypal-rest-api-specifications", "Official PayPal REST API specifications repository."),
			humanDocsRef("paypal-orders-api-docs", "https://developer.paypal.com/api/rest/reference/orders/v2/", "Official PayPal Orders v2 API reference documentation."),
		},
		quirks: []string{"PayPal publishes split OpenAPI documents by API family; this entry starts with Checkout Orders v2 because it covers common checkout workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "salesforce",
		displayName:         "Salesforce",
		aliases:             []string{"salesforce api", "salesforce rest api"},
		category:            "crm",
		relevance:           "Popular workflow service for CRM records, SOQL queries, search, and automation around accounts, contacts, leads, and opportunities.",
		openAPIAvailability: SpecAvailabilityNeedsVerification,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("salesforce-rest-docs", "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest.htm", "Official Salesforce REST API Developer Guide."),
			humanDocsRef("salesforce-rest-auth-docs", "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/quickstart_oauth.htm", "Official Salesforce REST API OAuth quick start documentation."),
			humanDocsRef("salesforce-openapi-generation-notes", "https://help.salesforce.com/s/articleView?id=release-notes.rn_api_rest.htm&language=en_US&release=236&type=5", "Official Salesforce release note describing beta OpenAPI 3.0 spec generation for Salesforce Platform REST API."),
		},
		quirks: []string{"Salesforce REST API OpenAPI generation is org/configuration dependent in current official docs; no stable public downloadable core REST OpenAPI document is recorded in this catalog entry."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "sendgrid",
		displayName:         "SendGrid",
		aliases:             []string{"sendgrid api", "twilio sendgrid"},
		category:            "email",
		relevance:           "Popular workflow service for transactional email, templates, contacts, suppression lists, and email analytics.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "sendgrid-mail-v3-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/twilio/sendgrid-oai/main/spec/json/tsg_mail_v3.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "1.0.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:fb95a935c87b79f7f982ac34bd37adab1f697dbc etag:"66d1536502d0ae3c780a9809059de874e3986cd61e9c65703b19d6761a4dc328"`,
				LicenseNote:     "Twilio SendGrid Mail OpenAPI document declares MIT license metadata; Twilio SendGrid documentation terms still apply to docs content.",
				SourceNote:      "Official Twilio SendGrid OpenAPI repository JSON specification for the Mail v3 API surface.",
			},
			humanDocsRef("sendgrid-oai-repo", "https://github.com/twilio/sendgrid-oai", "Official Twilio SendGrid OpenAPI specification repository."),
			humanDocsRef("sendgrid-api-reference", "https://www.twilio.com/docs/sendgrid/api-reference", "Official Twilio SendGrid API reference documentation."),
			humanDocsRef("sendgrid-auth-docs", "https://www.twilio.com/docs/sendgrid/for-developers/sending-email/authentication/", "Official Twilio SendGrid authentication documentation."),
		},
		quirks: []string{"Twilio SendGrid publishes split OpenAPI files by product area; this entry starts with the Mail v3 spec used by common transactional email workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "servicenow",
		displayName:         "ServiceNow",
		aliases:             []string{"servicenow api", "servicenow rest"},
		category:            "it-service-management",
		relevance:           "Popular workflow service for incidents, users, tables, service catalog, change records, and ITSM automation.",
		openAPIAvailability: SpecAvailabilityNeedsVerification,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("servicenow-rest-api-docs", "https://www.servicenow.com/docs/r/api-reference/rest-api-explorer/c_RESTAPI.html", "Official ServiceNow REST API documentation. ServiceNow documents instance-side REST API Explorer export to OpenAPI, but this catalog entry records no stable public downloadable OpenAPI document."),
			humanDocsRef("servicenow-openapi-export-docs", "https://www.servicenow.com/docs/r/api-reference/rest-api-explorer/export-openapi-specification.html", "Official ServiceNow documentation for exporting a REST API as an OpenAPI specification from a ServiceNow instance."),
		},
		quirks: []string{
			"ServiceNow REST API Explorer exports are instance- and API-selection-specific and require appropriate roles, so catalog users likely need a user-provided export for precise table and custom API shapes.",
			"ServiceNow warns that REST API Explorer can interact with the current instance; catalog tooling must treat exported specs as untrusted metadata and never execute API operations.",
		},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "shopify",
		displayName:         "Shopify",
		aliases:             []string{"shopify api", "shopify admin api"},
		category:            "commerce",
		relevance:           "Popular workflow service for products, orders, customers, inventory, and commerce automation.",
		openAPIAvailability: SpecAvailabilityUnknown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedLikely,
		specs: []SpecReference{
			humanDocsRef("shopify-admin-rest-docs", "https://shopify.dev/docs/api/admin-rest", "Official Shopify REST Admin API reference."),
			humanDocsRef("shopify-admin-rest-auth-docs", "https://shopify.dev/api/admin-rest/usage/access-scopes", "Official Shopify REST Admin API access scope documentation."),
			humanDocsRef("shopify-admin-rest-versioning", "https://shopify.dev/docs/api/admin-rest/usage/versioning", "Official Shopify REST Admin API versioning documentation."),
		},
		quirks: []string{"Shopify's REST Admin API is versioned in endpoint URLs and public docs emphasize access scopes; no stable public downloadable OpenAPI document is recorded in this catalog entry."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "slack",
		displayName:         "Slack",
		aliases:             []string{"slack api"},
		category:            "messaging",
		relevance:           "Common workflow service for messages, channels, and collaboration notifications.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "slack-web-openapi-v2",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2_without_examples.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "OpenAPI 2.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        "repo:bc08db49625630e3585bf2f1322128ea04f2a7f3 blob:f7b1affd1fb34f9473cd87980428883019b29c07",
				LicenseNote:     "Repository license applies; repository is archived and read-only.",
				SourceNote:      "Official Slack API specs repository Web API OpenAPI document; repository was archived by its owner in 2024.",
			},
			humanDocsRef("slack-web-api-docs", "https://docs.slack.dev/apis/web-api", "Official Slack Web API documentation."),
		},
		quirks: []string{"The official Slack OpenAPI repository is archived, so freshness should be checked against current Slack docs before import."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "stripe",
		displayName:         "Stripe",
		aliases:             []string{"stripe api"},
		category:            "payments",
		relevance:           "Popular workflow service for payments, customers, subscriptions, invoices, checkout, events, and billing automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "stripe-latest-openapi-spec3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/stripe/openapi/master/latest/openapi.spec3.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "2026-04-22.dahlia",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:c29a3d372d2cdd1085a6d1cc18bd968a84129c7b etag:"9fcfad85998e57740095245e3c28175d56684340bbddfa08de65199319ebdb07"`,
				LicenseNote:     "Stripe OpenAPI repository license applies.",
				SourceNote:      "Official Stripe OpenAPI repository latest generally available public specification.",
			},
			humanDocsRef("stripe-openapi-readme", "https://github.com/stripe/openapi", "Official Stripe OpenAPI repository README."),
			humanDocsRef("stripe-api-docs", "https://docs.stripe.com/api", "Official Stripe API reference documentation."),
		},
		quirks: []string{"Stripe's repository marks latest/openapi.spec3.json as the recommended GA public spec; openapi/spec3.json is legacy v1-only and should not be preferred for new imports."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "trello",
		displayName:         "Trello",
		aliases:             []string{"trello api"},
		category:            "project-management",
		relevance:           "Common workflow service for boards, lists, cards, and task automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "trello-cloud-openapi-v3",
				Kind:            SpecKindOpenAPI,
				URL:             "https://dac-static.atlassian.com/cloud/trello/swagger.v3.json",
				SourceAuthority: SourceAuthorityOfficialProvider,
				Version:         "v3",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `etag:"c4c69e7449085c4ef83e72a4b0344dfa"`,
				LicenseNote:     "Atlassian developer documentation terms apply.",
				SourceNote:      "Atlassian-hosted Trello Cloud OpenAPI document.",
			},
			humanDocsRef("trello-rest-docs", "https://developer.atlassian.com/cloud/trello/rest/", "Official Trello REST API documentation."),
		},
		quirks: []string{"Trello authentication and token flows may require supplemental security review before downstream use."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "twilio",
		displayName:         "Twilio",
		aliases:             []string{"twilio api", "twilio sms"},
		category:            "communications",
		relevance:           "Popular workflow service for SMS, voice, messaging, phone numbers, and communication automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedNotExpected,
		specs: []SpecReference{
			{
				ID:              "twilio-api-v2010-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "1.0.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:7efd1f014b839ba7ac23cf52a28a87e618e7b220 etag:"421708402a0f348997708407095971d22301961bfcab8d1df9f678cd82fee5eb"`,
				LicenseNote:     "Twilio OpenAPI document declares Apache 2.0 license metadata; Twilio documentation terms still apply to docs content.",
				SourceNote:      "Official Twilio OpenAPI repository JSON specification for the public Twilio REST API v2010 surface.",
			},
			humanDocsRef("twilio-oai-repo", "https://github.com/twilio/twilio-oai", "Official Twilio OpenAPI specification repository."),
			humanDocsRef("twilio-api-request-docs", "https://www.twilio.com/docs/usage/requests-to-twilio", "Official Twilio API request and authentication documentation."),
		},
		quirks: []string{"Twilio publishes many product-specific OpenAPI files; this entry starts with the core API v2010 spec used by common SMS and voice workflows."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "xero",
		displayName:         "Xero",
		aliases:             []string{"xero api", "xero accounting"},
		category:            "accounting",
		relevance:           "Popular accounting platform for contacts, invoices, bills, payments, bank transactions, and finance automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "xero-accounting-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero_accounting.yaml",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "14.0.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:812087190bac1adce52ddc3a661a90cd5aa89d9c etag:"2d1952b42299411af225c6e4fcd355d1fe30f238e2e55c5eca6cb93530c26c1f"`,
				LicenseNote:     "Xero OpenAPI repository is licensed under MIT.",
				SourceNote:      "Official Xero OpenAPI repository Accounting API OpenAPI document.",
			},
			humanDocsRef("xero-openapi-repo", "https://github.com/XeroAPI/Xero-OpenAPI", "Official Xero OpenAPI descriptions repository."),
			humanDocsRef("xero-api-docs", "https://developer.xero.com/documentation/api/accounting/overview", "Official Xero Accounting API documentation."),
		},
		quirks: []string{"Xero publishes split OpenAPI files by API family; this entry starts with Accounting because it covers common workflow automation around invoices, contacts, accounts, and payments."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "zoom",
		displayName:         "Zoom",
		aliases:             []string{"zoom api", "zoom meetings"},
		category:            "communications",
		relevance:           "Popular workflow service for meetings, webinars, recordings, users, and account automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "zoom-api-v2-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/zoom/api/master/openapi.v2.json",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "2.0.0",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:442998230a148f403c3d1de1fe7aa54937354fa9 etag:"5eb36d317bd21b9e2c38bb211e5c6c8e4a75c6a874e78f56cbb59dd5620d3eab"`,
				LicenseNote:     "Zoom API repository is licensed under Apache 2.0.",
				SourceNote:      "Official Zoom API repository Swagger 2.0 document for API v2.",
			},
			humanDocsRef("zoom-meetings-api-docs", "https://developers.zoom.us/docs/api/meetings/", "Official Zoom Meetings API documentation rendered from OpenAPI 3.1.1 endpoint metadata."),
			humanDocsRef("zoom-oauth-docs", "https://developers.zoom.us/docs/integrations/oauth/", "Official Zoom OAuth documentation."),
		},
		quirks: []string{"The official GitHub Swagger 2.0 document carries older query-token security metadata, while current Zoom developer docs render OpenAPI 3.1.1 pages with OAuth scopes; consumers should treat auth as advisory-reviewed."},
	}),
	providerCatalogEntry(providerSeed{
		id:                  "zendesk",
		displayName:         "Zendesk",
		aliases:             []string{"zendesk api", "zendesk support"},
		category:            "customer-support",
		relevance:           "Popular workflow service for support tickets, users, organizations, messaging, and customer-service automation.",
		openAPIAvailability: SpecAvailabilityKnown,
		machineAvailability: SpecAvailabilityUnknown,
		userNeed:            UserOpenAPINeedPossible,
		specs: []SpecReference{
			{
				ID:              "zendesk-sunshine-conversations-openapi",
				Kind:            SpecKindOpenAPI,
				URL:             "https://raw.githubusercontent.com/zendesk/sunshine-conversations-api-spec/master/openapi.yaml",
				SourceAuthority: SourceAuthorityOfficialGitHub,
				Version:         "17.10.2",
				VerifiedAt:      verifiedAt20260518,
				Revision:        `repo:d5a86eab72b6c8f907724fa46f48372461dd7da2 etag:"79c7c9fa7dc292c5cb24d9f6f54894cc7a83dcc53806906bcf550db5bb00b1fa"`,
				LicenseNote:     "No repository license is recorded in this catalog entry; Zendesk developer terms apply to documentation and generated clients.",
				SourceNote:      "Official Zendesk Sunshine Conversations OpenAPI specification for the v2 messaging API; Zendesk states it is used to generate the hosted API reference.",
			},
			humanDocsRef("zendesk-sunshine-openapi-docs", "https://developer.zendesk.com/documentation/conversations/references/openapi-specification/", "Official Zendesk Messaging OpenAPI specification documentation."),
			humanDocsRef("zendesk-support-api-docs", "https://developer.zendesk.com/api-reference/ticketing/introduction/", "Official Zendesk Support API reference documentation."),
			humanDocsRef("zendesk-security-auth-docs", "https://developer.zendesk.com/api-reference/introduction/security-and-auth/", "Official Zendesk API security and authentication documentation."),
		},
		quirks: []string{
			"The official OpenAPI document covers Sunshine Conversations / Zendesk Messaging v2, not the full Zendesk Support and Ticketing API surface.",
			"Support API workflows may still need a user-supplied OpenAPI document or docs-derived advisory overlay for precise endpoint coverage.",
		},
	}),
}

type providerSeed struct {
	id                  string
	displayName         string
	aliases             []string
	category            string
	relevance           string
	openAPIAvailability SpecAvailability
	machineAvailability SpecAvailability
	userNeed            UserOpenAPINeed
	specs               []SpecReference
	quirks              []string
}

func providerCatalogEntry(seed providerSeed) Provider {
	return Provider{
		ID:                              seed.id,
		DisplayName:                     seed.displayName,
		Aliases:                         append([]string(nil), seed.aliases...),
		Category:                        seed.category,
		WorkflowRelevance:               seed.relevance,
		SourceHints:                     []string{"promoted-from-m2-candidate"},
		ReviewState:                     ProviderReviewedCatalogEntry,
		CandidateID:                     seed.id,
		OfficialOpenAPIAvailability:     seed.openAPIAvailability,
		OfficialMachineSpecAvailability: seed.machineAvailability,
		UserOpenAPINeed:                 seed.userNeed,
		SpecReferences:                  append([]SpecReference(nil), seed.specs...),
		Quirks:                          append([]string(nil), seed.quirks...),
	}
}

func humanDocsRef(id, url, note string) SpecReference {
	return SpecReference{
		ID:              id,
		Kind:            SpecKindHumanDocs,
		URL:             url,
		SourceAuthority: SourceAuthorityOfficialDocs,
		VerifiedAt:      verifiedAt20260518,
		LicenseNote:     "Provider documentation terms apply.",
		SourceNote:      note,
	}
}
