//go:build ignore

package main

import (
	"context"
	"fmt"
	"os"
	"time"

	apitools "github.com/OpenUdon/apitools"
	"github.com/OpenUdon/apitools/sqlitecache"
)

const cachePath = "catalog-openapi-cache/cache.sqlite"

type specArtifact struct {
	providerID string
	artifactID string
	kind       string
	url        string
	path       string
	title      string
	openapi    string
	swagger    string
	status     string
}

type overlayArtifact struct {
	providerID  string
	artifactID  string
	path        string
	builderPath string
	sourceURL   string
	metadata    map[string]string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	ctx := context.Background()
	cache, err := sqlitecache.Open(cachePath)
	if err != nil {
		return err
	}
	defer cache.Close()

	for _, spec := range specArtifacts {
		if err := registerSpec(ctx, cache, spec); err != nil {
			return err
		}
	}
	for _, overlay := range overlayArtifacts {
		metadata := map[string]string{
			"official_openapi":  "false",
			"derived_from_docs": "true",
		}
		for key, value := range overlay.metadata {
			metadata[key] = value
		}
		if err := cache.StoreCatalogArtifact(ctx, sqlitecache.CatalogArtifact{
			ProviderID:  overlay.providerID,
			ArtifactID:  overlay.artifactID,
			Kind:        "advisory-overlay",
			Path:        overlay.path,
			SourceURL:   overlay.sourceURL,
			OverlayPath: overlay.path,
			BuilderPath: overlay.builderPath,
			Metadata:    metadata,
		}); err != nil {
			return err
		}
	}
	return nil
}

func registerSpec(ctx context.Context, cache *sqlitecache.Cache, artifact specArtifact) error {
	cached, ok, err := cache.LoadSpec(ctx, artifact.url, 100*365*24*time.Hour)
	if err != nil {
		return err
	}
	metadata := cached.Metadata
	finalURL := cached.FinalURL
	if !ok {
		finalURL = artifact.url
	}
	if metadata.Title == "" {
		metadata.Title = artifact.title
	}
	if metadata.OpenAPI == "" {
		metadata.OpenAPI = artifact.openapi
	}
	if metadata.Swagger == "" {
		metadata.Swagger = artifact.swagger
	}
	if finalURL == "" {
		finalURL = artifact.url
	}
	if err := cache.StoreSpec(ctx, apitools.CachedSpec{
		OriginalURL: artifact.url,
		FinalURL:    finalURL,
		ContentPath: artifact.path,
		Metadata:    metadata,
	}); err != nil {
		return err
	}
	artifactMetadata := map[string]string{
		"official": "true",
		"kind":     artifact.kind,
	}
	if artifact.status != "" {
		artifactMetadata["validation_status"] = artifact.status
	}
	return cache.StoreCatalogArtifact(ctx, sqlitecache.CatalogArtifact{
		ProviderID: artifact.providerID,
		ArtifactID: artifact.artifactID,
		Kind:       artifact.kind,
		Path:       artifact.path,
		SourceURL:  artifact.url,
		Metadata:   artifactMetadata,
	})
}

var specArtifacts = []specArtifact{
	{
		providerID: "asana",
		artifactID: "asana-openapi-v1",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml",
		path:       "openapi/asana-openapi-v1.yaml",
		title:      "Asana",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshInvalid,
	},
	{
		providerID: "azure-cosmos-db",
		artifactID: "azure-cosmos-db-resource-manager-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/DocumentDB/stable/2025-10-15/cosmos-db.json",
		path:       "openapi/azure-cosmos-db-resource-manager-openapi.json",
		title:      "Cosmos DB",
		swagger:    "2.0",
	},
	{
		providerID: "azure-storage",
		artifactID: "azure-blob-storage-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/storage/data-plane/Microsoft.BlobStorage/stable/2025-11-05/blob.json",
		path:       "openapi/azure-blob-storage-openapi.json",
		title:      "Azure Blob Storage",
		swagger:    "2.0",
	},
	{
		providerID: "asyncapi-examples",
		artifactID: "asyncapi-gemini-websocket",
		kind:       "asyncapi",
		url:        "https://raw.githubusercontent.com/asyncapi/spec/master/examples/websocket-gemini-asyncapi.yml",
		path:       "asyncapi/asyncapi-gemini-websocket.yml",
		title:      "Gemini Market Data Websocket API",
		status:     apitools.CatalogRefreshValidStructured,
	},
	{
		providerID: "asyncapi-examples",
		artifactID: "asyncapi-slack-rtm",
		kind:       "asyncapi",
		url:        "https://raw.githubusercontent.com/asyncapi/spec/master/examples/slack-rtm-asyncapi.yml",
		path:       "asyncapi/asyncapi-slack-rtm.yml",
		title:      "Slack Real Time Messaging API",
		status:     apitools.CatalogRefreshValidStructured,
	},
	{
		providerID: "asyncapi-examples",
		artifactID: "asyncapi-streetlights-mqtt",
		kind:       "asyncapi",
		url:        "https://raw.githubusercontent.com/asyncapi/spec/master/examples/streetlights-mqtt-asyncapi.yml",
		path:       "asyncapi/asyncapi-streetlights-mqtt.yml",
		title:      "Streetlights MQTT API",
		status:     apitools.CatalogRefreshValidStructured,
	},
	{
		providerID: "aws-lambda",
		artifactID: "aws-lambda-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/lambda/service/2015-03-31/lambda-2015-03-31.json",
		path:       "aws-smithy/aws-lambda-smithy-model.json",
		title:      "AWS Lambda Smithy Model",
	},
	{
		providerID: "aws-acm",
		artifactID: "aws-acm-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/acm/service/2015-12-08/acm-2015-12-08.json",
		path:       "aws-smithy/aws-acm-smithy-model.json",
		title:      "AWS Certificate Manager Smithy Model",
	},
	{
		providerID: "aws-cognito",
		artifactID: "aws-cognito-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/cognito-identity-provider/service/2016-04-18/cognito-identity-provider-2016-04-18.json",
		path:       "aws-smithy/aws-cognito-smithy-model.json",
		title:      "AWS Cognito Identity Provider Smithy Model",
	},
	{
		providerID: "aws-comprehend",
		artifactID: "aws-comprehend-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/comprehend/service/2017-11-27/comprehend-2017-11-27.json",
		path:       "aws-smithy/aws-comprehend-smithy-model.json",
		title:      "Amazon Comprehend Smithy Model",
	},
	{
		providerID: "aws-dynamodb",
		artifactID: "aws-dynamodb-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/dynamodb/service/2012-08-10/dynamodb-2012-08-10.json",
		path:       "aws-smithy/aws-dynamodb-smithy-model.json",
		title:      "Amazon DynamoDB Smithy Model",
	},
	{
		providerID: "aws-elb",
		artifactID: "aws-elb-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/elastic-load-balancing/service/2012-06-01/elastic-load-balancing-2012-06-01.json",
		path:       "aws-smithy/aws-elb-smithy-model.json",
		title:      "Elastic Load Balancing Smithy Model",
	},
	{
		providerID: "aws-elbv2",
		artifactID: "aws-elbv2-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/elastic-load-balancing-v2/service/2015-12-01/elastic-load-balancing-v2-2015-12-01.json",
		path:       "aws-smithy/aws-elbv2-smithy-model.json",
		title:      "Elastic Load Balancing v2 Smithy Model",
	},
	{
		providerID: "aws-iam",
		artifactID: "aws-iam-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/iam/service/2010-05-08/iam-2010-05-08.json",
		path:       "aws-smithy/aws-iam-smithy-model.json",
		title:      "AWS IAM Smithy Model",
	},
	{
		providerID: "aws-rekognition",
		artifactID: "aws-rekognition-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/rekognition/service/2016-06-27/rekognition-2016-06-27.json",
		path:       "aws-smithy/aws-rekognition-smithy-model.json",
		title:      "Amazon Rekognition Smithy Model",
	},
	{
		providerID: "aws-ses",
		artifactID: "aws-ses-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/ses/service/2010-12-01/ses-2010-12-01.json",
		path:       "aws-smithy/aws-ses-smithy-model.json",
		title:      "Amazon SES Smithy Model",
	},
	{
		providerID: "aws-s3",
		artifactID: "aws-s3-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/s3/service/2006-03-01/s3-2006-03-01.json",
		path:       "aws-smithy/aws-s3-smithy-model.json",
		title:      "Amazon S3 Smithy Model",
	},
	{
		providerID: "aws-sns",
		artifactID: "aws-sns-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/sns/service/2010-03-31/sns-2010-03-31.json",
		path:       "aws-smithy/aws-sns-smithy-model.json",
		title:      "Amazon SNS Smithy Model",
	},
	{
		providerID: "aws-sqs",
		artifactID: "aws-sqs-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/sqs/service/2012-11-05/sqs-2012-11-05.json",
		path:       "aws-smithy/aws-sqs-smithy-model.json",
		title:      "Amazon SQS Smithy Model",
	},
	{
		providerID: "aws-textract",
		artifactID: "aws-textract-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/textract/service/2018-06-27/textract-2018-06-27.json",
		path:       "aws-smithy/aws-textract-smithy-model.json",
		title:      "Amazon Textract Smithy Model",
	},
	{
		providerID: "aws-transcribe",
		artifactID: "aws-transcribe-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/transcribe/service/2017-10-26/transcribe-2017-10-26.json",
		path:       "aws-smithy/aws-transcribe-smithy-model.json",
		title:      "Amazon Transcribe Smithy Model",
	},
	{
		providerID: "aws-api-gateway",
		artifactID: "aws-api-gateway-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/api-gateway/service/2015-07-09/api-gateway-2015-07-09.json",
		path:       "aws-smithy/aws-api-gateway-smithy-model.json",
		title:      "Amazon API Gateway Smithy Model",
	},
	{
		providerID: "aws-athena",
		artifactID: "aws-athena-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/athena/service/2017-05-18/athena-2017-05-18.json",
		path:       "aws-smithy/aws-athena-smithy-model.json",
		title:      "Amazon Athena Smithy Model",
	},
	{
		providerID: "aws-bedrock",
		artifactID: "aws-bedrock-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/bedrock/service/2023-04-20/bedrock-2023-04-20.json",
		path:       "aws-smithy/aws-bedrock-smithy-model.json",
		title:      "Amazon Bedrock Smithy Model",
	},
	{
		providerID: "aws-cloudwatch",
		artifactID: "aws-cloudwatch-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/cloudwatch/service/2010-08-01/cloudwatch-2010-08-01.json",
		path:       "aws-smithy/aws-cloudwatch-smithy-model.json",
		title:      "Amazon CloudWatch Smithy Model",
	},
	{
		providerID: "aws-ec2",
		artifactID: "aws-ec2-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/ec2/service/2016-11-15/ec2-2016-11-15.json",
		path:       "aws-smithy/aws-ec2-smithy-model.json",
		title:      "Amazon EC2 Smithy Model",
	},
	{
		providerID: "aws-glue",
		artifactID: "aws-glue-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/glue/service/2017-03-31/glue-2017-03-31.json",
		path:       "aws-smithy/aws-glue-smithy-model.json",
		title:      "AWS Glue Smithy Model",
	},
	{
		providerID: "aws-guardduty",
		artifactID: "aws-guardduty-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/guardduty/service/2017-11-28/guardduty-2017-11-28.json",
		path:       "aws-smithy/aws-guardduty-smithy-model.json",
		title:      "Amazon GuardDuty Smithy Model",
	},
	{
		providerID: "aws-inspector2",
		artifactID: "aws-inspector2-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/inspector2/service/2020-06-08/inspector2-2020-06-08.json",
		path:       "aws-smithy/aws-inspector2-smithy-model.json",
		title:      "Amazon Inspector2 Smithy Model",
	},
	{
		providerID: "aws-kinesis",
		artifactID: "aws-kinesis-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/kinesis/service/2013-12-02/kinesis-2013-12-02.json",
		path:       "aws-smithy/aws-kinesis-smithy-model.json",
		title:      "Amazon Kinesis Smithy Model",
	},
	{
		providerID: "aws-kms",
		artifactID: "aws-kms-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/kms/service/2014-11-01/kms-2014-11-01.json",
		path:       "aws-smithy/aws-kms-smithy-model.json",
		title:      "AWS KMS Smithy Model",
	},
	{
		providerID: "aws-rds",
		artifactID: "aws-rds-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/rds/service/2014-10-31/rds-2014-10-31.json",
		path:       "aws-smithy/aws-rds-smithy-model.json",
		title:      "Amazon RDS Smithy Model",
	},
	{
		providerID: "aws-sagemaker",
		artifactID: "aws-sagemaker-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/sagemaker/service/2017-07-24/sagemaker-2017-07-24.json",
		path:       "aws-smithy/aws-sagemaker-smithy-model.json",
		title:      "Amazon SageMaker Smithy Model",
	},
	{
		providerID: "aws-secrets-manager",
		artifactID: "aws-secrets-manager-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/secrets-manager/service/2017-10-17/secrets-manager-2017-10-17.json",
		path:       "aws-smithy/aws-secrets-manager-smithy-model.json",
		title:      "AWS Secrets Manager Smithy Model",
	},
	{
		providerID: "aws-securityhub",
		artifactID: "aws-securityhub-smithy-model",
		kind:       "smithy-json",
		url:        "https://raw.githubusercontent.com/aws/api-models-aws/main/models/securityhub/service/2018-10-26/securityhub-2018-10-26.json",
		path:       "aws-smithy/aws-securityhub-smithy-model.json",
		title:      "AWS Security Hub Smithy Model",
	},
	{
		providerID: "bitbucket",
		artifactID: "bitbucket-cloud-swagger-v2",
		kind:       "openapi",
		url:        "https://api.bitbucket.org/swagger.json",
		path:       "openapi/bitbucket-cloud-swagger-v2.json",
		title:      "Bitbucket API",
		swagger:    "2.0",
		status:     apitools.CatalogRefreshParseableSwaggerInvalid,
	},
	{
		providerID: "bitly",
		artifactID: "bitly-api-v4-openapi",
		kind:       "openapi",
		url:        "https://dev.bitly.com/v4/v4.json",
		path:       "openapi/bitly-api-v4-openapi.json",
		title:      "Bitly API",
		openapi:    "3.0.0",
	},
	{
		providerID: "box",
		artifactID: "box-platform-openapi-v3",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/box/box-openapi/main/openapi.json",
		path:       "openapi/box-platform-openapi-v3.json",
		title:      "Box Platform API",
		openapi:    "3.0.2",
		status:     apitools.CatalogRefreshInvalid,
	},
	{
		providerID: "baserow",
		artifactID: "baserow-api-openapi",
		kind:       "openapi",
		url:        "https://api.baserow.io/api/schema.json",
		path:       "openapi/baserow-api-openapi.json",
		title:      "Baserow API spec",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshInvalid,
	},
	{
		providerID: "brandfetch",
		artifactID: "brandfetch-brand-api-openapi",
		kind:       "openapi",
		url:        "https://docs.brandfetch.com/openapi.json",
		path:       "openapi/brandfetch-brand-api-openapi.json",
		title:      "Brandfetch API",
		openapi:    "3.0.1",
	},
	{
		providerID: "clickup",
		artifactID: "clickup-api-v2-openapi",
		kind:       "openapi",
		url:        "https://developer.clickup.com/openapi/clickup-api-v2-reference.json",
		path:       "openapi/clickup-api-v2-reference.json",
		title:      "ClickUp API v2 Reference",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshInvalid,
	},
	{
		providerID: "circleci",
		artifactID: "circleci-api-v2-openapi",
		kind:       "openapi",
		url:        "https://circleci.com/api/v2/openapi.json",
		path:       "openapi/circleci-api-v2-openapi.json",
		title:      "CircleCI API",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshInvalid,
	},
	{
		providerID: "cloudflare",
		artifactID: "cloudflare-api-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml",
		path:       "openapi/cloudflare-api-openapi.yaml",
		title:      "Cloudflare API",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "chargebee",
		artifactID: "chargebee-api-v2-pc-v2-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/chargebee/openapi/main/spec/chargebee_api_v2_pc_v2_spec.json",
		path:       "openapi/chargebee-api-v2-pc-v2-openapi.json",
		title:      "Chargebee API",
		openapi:    "3.1.0",
	},
	{
		providerID: "brevo",
		artifactID: "brevo-api-v3-openapi",
		kind:       "openapi",
		url:        "https://api.brevo.com/v3/swagger_definition_v3.yml",
		path:       "openapi/brevo-api-v3-openapi.yml",
		title:      "Brevo API",
		openapi:    "3.0.1",
	},
	{
		providerID: "coda",
		artifactID: "coda-api-v1-openapi",
		kind:       "openapi",
		url:        "https://coda.io/apis/v1/openapi.json",
		path:       "openapi/coda-api-v1-openapi.json",
		title:      "Coda API",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "convertkit",
		artifactID: "kit-api-v4-openapi",
		kind:       "openapi",
		url:        "https://developers.kit.com/api-reference/v4.json",
		path:       "openapi/kit-api-v4-openapi.json",
		title:      "Kit API",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "customer-io",
		artifactID: "customer-io-journeys-app-openapi",
		kind:       "openapi",
		url:        "https://docs.customer.io/files/journeys-app.json",
		path:       "openapi/customer-io-journeys-app-openapi.json",
		title:      "Journeys App API",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "customer-io",
		artifactID: "customer-io-journeys-track-openapi",
		kind:       "openapi",
		url:        "https://docs.customer.io/files/journeys-track.json",
		path:       "openapi/customer-io-journeys-track-openapi.json",
		title:      "Journeys Track API",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "customer-io",
		artifactID: "customer-io-pipelines-openapi",
		kind:       "openapi",
		url:        "https://docs.customer.io/files/pipelines.json",
		path:       "openapi/customer-io-pipelines-openapi.json",
		title:      "Pipelines API",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "deepl",
		artifactID: "deepl-api-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/DeepLcom/openapi/main/openapi.yaml",
		path:       "openapi/deepl-api-openapi.yaml",
		title:      "DeepL API Documentation",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "discord",
		artifactID: "discord-api-v10-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/discord/discord-api-spec/main/specs/openapi.json",
		path:       "openapi/discord-api-v10-openapi.json",
		title:      "Discord HTTP API (Preview)",
		openapi:    "3.1.0",
	},
	{
		providerID: "discourse",
		artifactID: "discourse-api-openapi",
		kind:       "openapi",
		url:        "https://docs.discourse.org/openapi.json",
		path:       "openapi/discourse-api-openapi.json",
		title:      "Discourse API Documentation",
		openapi:    "3.1.0",
	},
	{
		providerID: "figma",
		artifactID: "figma-rest-api-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/figma/rest-api-spec/main/openapi/openapi.yaml",
		path:       "openapi/figma-rest-api-openapi.yaml",
		title:      "Figma API",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "grafana",
		artifactID: "grafana-http-api-openapi-v3",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/grafana/grafana/main/public/openapi3.json",
		path:       "openapi/grafana-http-api-openapi-v3.json",
		title:      "Grafana HTTP API.",
		openapi:    "3.0.3",
	},
	{
		providerID: "dropbox",
		artifactID: "dropbox-api-stone-spec",
		kind:       "dropbox-stone",
		url:        "https://github.com/dropbox/dropbox-api-spec/archive/refs/heads/main.tar.gz",
		path:       "openapi/dropbox-api-spec-main.tar.gz",
		title:      "Dropbox API Stone Spec",
	},
	{
		providerID: "github",
		artifactID: "github-rest-api-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
		path:       "openapi/github-rest-api-openapi.json",
		title:      "GitHub v3 REST API",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "elastic",
		artifactID: "elastic-elasticsearch-openapi",
		kind:       "openapi",
		url:        "https://www.elastic.co/docs/api/doc/elasticsearch.json",
		path:       "openapi/elastic-elasticsearch-openapi.json",
		title:      "Elasticsearch API",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "highlevel",
		artifactID: "highlevel-calendars-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/GoHighLevel/highlevel-api-docs/main/apps/calendars.json",
		path:       "openapi/highlevel-calendars-openapi.json",
		title:      "Calendars API",
		openapi:    "3.0.0",
	},
	{
		providerID: "highlevel",
		artifactID: "highlevel-contacts-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/GoHighLevel/highlevel-api-docs/main/apps/contacts.json",
		path:       "openapi/highlevel-contacts-openapi.json",
		title:      "Contacts API",
		openapi:    "3.0.0",
	},
	{
		providerID: "highlevel",
		artifactID: "highlevel-oauth-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/GoHighLevel/highlevel-api-docs/main/apps/oauth.json",
		path:       "openapi/highlevel-oauth-openapi.json",
		title:      "OAuth 2.0",
		openapi:    "3.0.0",
	},
	{
		providerID: "highlevel",
		artifactID: "highlevel-opportunities-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/GoHighLevel/highlevel-api-docs/main/apps/opportunities.json",
		path:       "openapi/highlevel-opportunities-openapi.json",
		title:      "Opportunities API",
		openapi:    "3.0.0",
	},
	{
		providerID: "highlevel",
		artifactID: "highlevel-users-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/GoHighLevel/highlevel-api-docs/main/apps/users.json",
		path:       "openapi/highlevel-users-openapi.json",
		title:      "Users API",
		openapi:    "3.0.0",
	},
	{
		providerID: "kobotoolbox",
		artifactID: "kobotoolbox-api-v2-openapi",
		kind:       "openapi",
		url:        "https://kf.kobotoolbox.org/api/v2/schema/",
		path:       "openapi/kobotoolbox-api-v2-openapi.yaml",
		title:      "KoboToolbox Primary API",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "cal",
		artifactID: "cal-api-v2-openapi",
		kind:       "openapi",
		url:        "https://cal.com/docs/api-reference/v2/openapi.json",
		path:       "openapi/cal-api-v2-openapi.json",
		title:      "Cal.com API v2",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "airtop",
		artifactID: "airtop-api-openapi",
		kind:       "openapi",
		url:        "https://docs.airtop.ai/openapi.json",
		path:       "openapi/airtop-api-openapi.json",
		title:      "Airtop API",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "gitlab",
		artifactID: "gitlab-openapi-v2",
		kind:       "swagger",
		url:        "https://gitlab.com/gitlab-org/gitlab/-/raw/master/doc/api/openapi/openapi_v2.yaml",
		path:       "openapi/gitlab-openapi-v2.yaml",
		title:      "GitLab API",
		swagger:    "2.0",
	},
	{
		providerID: "gmail",
		artifactID: "gmail-discovery-v1",
		kind:       "google-discovery",
		url:        "https://gmail.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/gmail-discovery-v1.json",
	},
	{
		providerID: "google-admin",
		artifactID: "admin-directory-discovery-v1",
		kind:       "google-discovery",
		url:        "https://admin.googleapis.com/$discovery/rest?version=directory_v1",
		path:       "google-discovery/google-admin-directory-discovery-v1.json",
		title:      "Admin SDK API",
	},
	{
		providerID: "google-analytics",
		artifactID: "analyticsdata-discovery-v1beta",
		kind:       "google-discovery",
		url:        "https://analyticsdata.googleapis.com/$discovery/rest?version=v1beta",
		path:       "google-discovery/google-analyticsdata-discovery-v1beta.json",
		title:      "Google Analytics Data API",
	},
	{
		providerID: "google-bigquery",
		artifactID: "bigquery-discovery-v2",
		kind:       "google-discovery",
		url:        "https://bigquery.googleapis.com/$discovery/rest?version=v2",
		path:       "google-discovery/google-bigquery-discovery-v2.json",
		title:      "BigQuery API",
	},
	{
		providerID: "google-books",
		artifactID: "books-discovery-v1",
		kind:       "google-discovery",
		url:        "https://books.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-books-discovery-v1.json",
		title:      "Books API",
	},
	{
		providerID: "google-business-profile",
		artifactID: "businessinformation-discovery-v1",
		kind:       "google-discovery",
		url:        "https://mybusinessbusinessinformation.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-businessprofile-discovery-v1.json",
		title:      "My Business Business Information API",
	},
	{
		providerID: "google-business-profile",
		artifactID: "businessprofile-accountmanagement-discovery-v1",
		kind:       "google-discovery",
		url:        "https://mybusinessaccountmanagement.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-businessprofile-accountmanagement-discovery-v1.json",
		title:      "My Business Account Management API",
	},
	{
		providerID: "google-calendar",
		artifactID: "calendar-discovery-v3",
		kind:       "google-discovery",
		url:        "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest",
		path:       "google-discovery/google-calendar-discovery-v3.json",
		title:      "Calendar API",
	},
	{
		providerID: "google-chat",
		artifactID: "chat-discovery-v1",
		kind:       "google-discovery",
		url:        "https://chat.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-chat-discovery-v1.json",
		title:      "Google Chat API",
	},
	{
		providerID: "google-cloud-language",
		artifactID: "language-discovery-v1",
		kind:       "google-discovery",
		url:        "https://language.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-cloud-language-discovery-v1.json",
		title:      "Cloud Natural Language API",
	},
	{
		providerID: "google-cloud-storage",
		artifactID: "storage-discovery-v1",
		kind:       "google-discovery",
		url:        "https://storage.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-cloud-storage-discovery-v1.json",
		title:      "Cloud Storage JSON API",
	},
	{
		providerID: "google-contacts",
		artifactID: "people-discovery-v1",
		kind:       "google-discovery",
		url:        "https://people.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-people-discovery-v1.json",
		title:      "People API",
	},
	{
		providerID: "google-docs",
		artifactID: "docs-discovery-v1",
		kind:       "google-discovery",
		url:        "https://docs.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-docs-discovery-v1.json",
		title:      "Google Docs API",
	},
	{
		providerID: "google-firebase-realtime-database",
		artifactID: "firebasedatabase-discovery-v1beta",
		kind:       "google-discovery",
		url:        "https://firebasedatabase.googleapis.com/$discovery/rest?version=v1beta",
		path:       "google-discovery/google-firebasedatabase-discovery-v1beta.json",
		title:      "Firebase Realtime Database Management API",
	},
	{
		providerID: "google-drive",
		artifactID: "drive-discovery-v3",
		kind:       "google-discovery",
		url:        "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
		path:       "google-discovery/drive-discovery-v3.json",
	},
	{
		providerID: "google-firestore",
		artifactID: "firestore-discovery-v1",
		kind:       "google-discovery",
		url:        "https://firestore.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-firestore-discovery-v1.json",
		title:      "Cloud Firestore API",
	},
	{
		providerID: "google-perspective",
		artifactID: "commentanalyzer-discovery-v1alpha1",
		kind:       "google-discovery",
		url:        "https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1",
		path:       "google-discovery/google-commentanalyzer-discovery-v1alpha1.json",
		title:      "Perspective Comment Analyzer API",
	},
	{
		providerID: "google-sheets",
		artifactID: "sheets-discovery-v4",
		kind:       "google-discovery",
		url:        "https://sheets.googleapis.com/$discovery/rest?version=v4",
		path:       "google-discovery/google-sheets-discovery-v4.json",
		title:      "Google Sheets API",
	},
	{
		providerID: "google-slides",
		artifactID: "slides-discovery-v1",
		kind:       "google-discovery",
		url:        "https://slides.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-slides-discovery-v1.json",
		title:      "Google Slides API",
	},
	{
		providerID: "google-tasks",
		artifactID: "tasks-discovery-v1",
		kind:       "google-discovery",
		url:        "https://tasks.googleapis.com/$discovery/rest?version=v1",
		path:       "google-discovery/google-tasks-discovery-v1.json",
		title:      "Google Tasks API",
	},
	{
		providerID: "google-translate",
		artifactID: "translate-discovery-v2",
		kind:       "google-discovery",
		url:        "https://www.googleapis.com/discovery/v1/apis/translate/v2/rest",
		path:       "google-discovery/google-translate-discovery-v2.json",
		title:      "Google Cloud Translation API",
	},
	{
		providerID: "google-youtube",
		artifactID: "youtube-discovery-v3",
		kind:       "google-discovery",
		url:        "https://youtube.googleapis.com/$discovery/rest?version=v3",
		path:       "google-discovery/google-youtube-discovery-v3.json",
		title:      "YouTube Data API v3",
	},
	{
		providerID: "hubspot",
		artifactID: "hubspot-public-api-spec-index",
		kind:       "openapi-index",
		url:        "https://api.hubapi.com/public/api/spec/v1/specs",
		path:       "openapi/hubspot-public-api-spec-index.json",
	},
	{
		providerID: "intercom",
		artifactID: "intercom-api-v2-15-openapi",
		kind:       "openapi",
		url:        "https://developers.intercom.com/_bundle/docs/references/%402.15/rest-api/api.intercom.io.json?download=",
		path:       "openapi/intercom-api-v2-15-openapi.json",
		title:      "Intercom API",
		openapi:    "3.0.1",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "mailgun",
		artifactID: "mailgun-send-api-openapi",
		kind:       "openapi",
		url:        "https://documentation.mailgun.com/_bundle/docs/mailgun/api-reference/send/mailgun.json",
		path:       "openapi/mailgun-send-api-openapi.json",
		title:      "Mailgun API",
		openapi:    "3.1.0",
	},
	{
		providerID: "marketstack",
		artifactID: "marketstack-api-v2-openapi",
		kind:       "openapi",
		url:        "https://api.swaggerhub.com/apis/apilayer-863/MarketstackAPIv2/2.0.0/swagger.json",
		path:       "openapi/marketstack-api-v2-openapi.json",
		title:      "Marketstack API v2",
		openapi:    "3.0.3",
	},
	{
		providerID: "jira-cloud",
		artifactID: "jira-cloud-platform-openapi-v3",
		kind:       "openapi",
		url:        "https://dac-static.atlassian.com/cloud/jira/platform/swagger-v3.v3.json",
		path:       "openapi/jira-cloud-platform-openapi-v3.json",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "microsoft-graph",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "microsoft-entra",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "microsoft-excel",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "microsoft-graph-security",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "microsoft-onedrive",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "microsoft-outlook",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "microsoft-sharepoint",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "microsoft-teams",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "microsoft-todo",
		artifactID: "microsoft-graph-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml",
		path:       "openapi/microsoft-graph-v1-openapi.yaml",
		title:      "OData Service for namespace microsoft.graph",
		openapi:    "3.0.4",
	},
	{
		providerID: "netlify",
		artifactID: "netlify-api-openapi",
		kind:       "openapi",
		url:        "https://open-api.netlify.com/openapi.json",
		path:       "openapi/netlify-api-openapi.json",
		title:      "Netlify's API documentation",
		openapi:    "3.0.0",
	},
	{
		providerID: "nocodb",
		artifactID: "nocodb-api-v2-openapi",
		kind:       "openapi",
		url:        "https://nocodb.com/apis/v2/swagger-v2.json",
		path:       "openapi/nocodb-api-v2-openapi.json",
		title:      "NocoDB v2",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "nocodb",
		artifactID: "nocodb-api-v3-openapi",
		kind:       "openapi",
		url:        "https://nocodb.com/apis/v3/swagger-v3.json",
		path:       "openapi/nocodb-api-v3-openapi.json",
		title:      "NocoDB v3",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "notion",
		artifactID: "notion-api-openapi",
		kind:       "openapi",
		url:        "https://developers.notion.com/openapi.json",
		path:       "openapi/notion-api-openapi.json",
		title:      "Notion API",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "okta",
		artifactID: "okta-management-minimal-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/okta/okta-management-openapi-spec/master/dist/current/management-minimal.yaml",
		path:       "openapi/okta-management-minimal-openapi.yaml",
		title:      "Okta Admin Management API",
		openapi:    "3.0.3",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "pagerduty",
		artifactID: "pagerduty-rest-openapi-v3",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/PagerDuty/api-schema/main/reference/REST/openapiv3.json",
		path:       "openapi/pagerduty-rest-openapi-v3.json",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "paypal",
		artifactID: "paypal-checkout-orders-v2-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/paypal/paypal-rest-api-specifications/main/openapi/checkout_orders_v2.json",
		path:       "openapi/paypal-checkout-orders-v2-openapi.json",
		title:      "Orders",
		openapi:    "3.0.4",
	},
	{
		providerID: "paddle",
		artifactID: "paddle-api-v1-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/PaddleHQ/paddle-openapi/main/v1/openapi.yaml",
		path:       "openapi/paddle-api-v1-openapi.yaml",
		title:      "Paddle API",
		openapi:    "3.1.0",
	},
	{
		providerID: "pipedrive",
		artifactID: "pipedrive-api-v2-openapi",
		kind:       "openapi",
		url:        "https://developers.pipedrive.com/docs/api/v1/openapi-v2.yaml",
		path:       "openapi/pipedrive-api-v2-openapi.yaml",
		title:      "Pipedrive API v2",
		openapi:    "3.0.1",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "posthog",
		artifactID: "posthog-api-openapi",
		kind:       "openapi",
		url:        "https://us.posthog.com/api/schema/",
		path:       "openapi/posthog-api-openapi.yaml",
		title:      "PostHog API",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "seatable",
		artifactID: "seatable-authentication-v6-2-openapi",
		kind:       "openapi",
		url:        "https://api.seatable.com/openapi/69d4dc0c1422831f8d6fbb8e",
		path:       "openapi/seatable-authentication-v6-2-openapi.json",
		title:      "Authentication",
		openapi:    "3.0.0",
	},
	{
		providerID: "seatable",
		artifactID: "seatable-user-v6-2-openapi",
		kind:       "openapi",
		url:        "https://api.seatable.com/openapi/69d4dc0c1422831f8d6fbb93",
		path:       "openapi/seatable-user-v6-2-openapi.json",
		title:      "Account Operations - User",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "seatable",
		artifactID: "seatable-base-v6-2-openapi",
		kind:       "openapi",
		url:        "https://api.seatable.com/openapi/69d4dc0c1422831f8d6fbb96",
		path:       "openapi/seatable-base-v6-2-openapi.json",
		title:      "Base Operations",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "seatable",
		artifactID: "seatable-file-v6-2-openapi",
		kind:       "openapi",
		url:        "https://api.seatable.com/openapi/69d4dc0c1422831f8d6fbb95",
		path:       "openapi/seatable-file-v6-2-openapi.json",
		title:      "File Operations",
		openapi:    "3.0.0",
	},
	{
		providerID: "sendgrid",
		artifactID: "sendgrid-mail-v3-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/twilio/sendgrid-oai/main/spec/json/tsg_mail_v3.json",
		path:       "openapi/sendgrid-mail-v3-openapi.json",
		title:      "Twilio SendGrid Mail API",
		openapi:    "3.1.0",
	},
	{
		providerID: "slack",
		artifactID: "slack-web-openapi-v2",
		kind:       "swagger",
		url:        "https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2_without_examples.json",
		path:       "openapi/slack-web-openapi-v2.json",
		status:     apitools.CatalogRefreshParseableSwaggerInvalid,
	},
	{
		providerID: "snowflake",
		artifactID: "snowflake-sql-api-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/snowflakedb/snowflake-rest-api-specs/main/specifications/sqlapi.yaml",
		path:       "openapi/snowflake-sql-api-openapi.yaml",
		title:      "Snowflake SQL API",
		openapi:    "3.0.0",
	},
	{
		providerID: "stripe",
		artifactID: "stripe-latest-openapi-spec3",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/stripe/openapi/master/latest/openapi.spec3.json",
		path:       "openapi/stripe-latest-openapi-spec3.json",
		title:      "Stripe API",
		openapi:    "3.0.0",
	},
	{
		providerID: "supabase",
		artifactID: "supabase-management-api-openapi",
		kind:       "openapi",
		url:        "https://api.supabase.com/api/v1-json",
		path:       "openapi/supabase-management-api-openapi.json",
		title:      "Supabase API (v1)",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "trello",
		artifactID: "trello-cloud-openapi-v3",
		kind:       "openapi",
		url:        "https://dac-static.atlassian.com/cloud/trello/swagger.v3.json",
		path:       "openapi/trello-cloud-openapi-v3.json",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "uptimerobot",
		artifactID: "uptimerobot-api-v3-openapi",
		kind:       "openapi",
		url:        "https://cdn.uptimerobot.com/api/openapi.yaml",
		path:       "openapi/uptimerobot-api-v3-openapi.yaml",
		title:      "UptimeRobot REST API",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "twilio",
		artifactID: "twilio-api-v2010-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json",
		path:       "openapi/twilio-api-v2010-openapi.json",
		title:      "Twilio - Api",
		openapi:    "3.0.1",
	},
	{
		providerID: "xero",
		artifactID: "xero-accounting-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero_accounting.yaml",
		path:       "openapi/xero-accounting-openapi.yaml",
		title:      "Xero Accounting API",
		openapi:    "3.0.0",
	},
	{
		providerID: "zoom",
		artifactID: "zoom-api-v2-openapi",
		kind:       "swagger",
		url:        "https://raw.githubusercontent.com/zoom/api/master/openapi.v2.json",
		path:       "openapi/zoom-api-v2-openapi.json",
		title:      "Zoom API",
		swagger:    "2.0",
	},
	{
		providerID: "zendesk",
		artifactID: "zendesk-sunshine-conversations-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/zendesk/sunshine-conversations-api-spec/master/openapi.yaml",
		path:       "openapi/zendesk-sunshine-conversations-openapi.yaml",
		title:      "Sunshine Conversations API",
		openapi:    "3.0.2",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "line",
		artifactID: "line-messaging-api-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/line/line-openapi/main/messaging-api.yml",
		path:       "openapi/line-messaging-api-openapi.yml",
		title:      "LINE Messaging API",
		openapi:    "3.0.0",
	},
	{
		providerID: "mattermost",
		artifactID: "mattermost-api-v4-openapi",
		kind:       "openapi",
		url:        "https://developers.mattermost.com/mattermost-openapi-v4.yaml",
		path:       "openapi/mattermost-api-v4-openapi.yaml",
		title:      "Mattermost Web Services API",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "matrix",
		artifactID: "matrix-client-server-api-openapi",
		kind:       "openapi",
		url:        "https://spec.matrix.org/latest/client-server-api/api.json",
		path:       "openapi/matrix-client-server-api-openapi.json",
		title:      "Matrix Client-Server API",
		openapi:    "3.1.0",
	},
	{
		providerID: "rocket-chat",
		artifactID: "rocket-chat-authentication-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/main/authentication.yaml",
		path:       "openapi/rocket-chat-authentication-openapi.yaml",
		title:      "Authentication",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "rocket-chat",
		artifactID: "rocket-chat-messaging-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/RocketChat/Rocket.Chat-Open-API/main/messaging.yaml",
		path:       "openapi/rocket-chat-messaging-openapi.yaml",
		title:      "Messaging",
		openapi:    "3.0.0",
	},
	{
		providerID: "twitter",
		artifactID: "twitter-api-v2-openapi",
		kind:       "openapi",
		url:        "https://api.twitter.com/2/openapi.json",
		path:       "openapi/twitter-api-v2-openapi.json",
		title:      "X API v2",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
	{
		providerID: "misp",
		artifactID: "misp-automation-api-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/MISP/MISP/2.4/app/webroot/doc/openapi.yaml",
		path:       "openapi/misp-automation-api-openapi.yaml",
		title:      "MISP Automation API",
		openapi:    "3.0.0",
	},
	{
		providerID: "rundeck",
		artifactID: "rundeck-api-openapi",
		kind:       "openapi",
		url:        "https://docs.rundeck.com/docs/files/rundeck-api.yml",
		path:       "openapi/rundeck-api-openapi.yml",
		title:      "Rundeck / Runbook Automation API",
		openapi:    "3.0.1",
	},
	{
		providerID: "securityscorecard",
		artifactID: "securityscorecard-api-docs-swagger-v2",
		kind:       "openapi",
		url:        "https://api.securityscorecard.io/api-docs",
		path:       "openapi/securityscorecard-api-docs-swagger-v2.json",
		title:      "SecurityScorecard API",
		swagger:    "2.0",
	},
	{
		providerID: "urlscan",
		artifactID: "urlscan-openapi",
		kind:       "openapi",
		url:        "https://docs.urlscan.io/_bundle/apis/urlscan-openapi.json?download",
		path:       "openapi/urlscan-openapi.json",
		title:      "urlscan.io APIs",
		openapi:    "3.0.0",
	},
	{
		providerID: "jina-ai",
		artifactID: "jina-ai-search-foundation-openapi",
		kind:       "openapi",
		url:        "https://api.jina.ai/openapi.json",
		path:       "openapi/jina-ai-search-foundation-openapi.json",
		title:      "Jina Search Foundation API",
		openapi:    "3.1.0",
	},
	{
		providerID: "jina-ai",
		artifactID: "jina-reader-openapi",
		kind:       "openapi",
		url:        "https://r.jina.ai/openapi.json",
		path:       "openapi/jina-reader-openapi.json",
		title:      "Jina Reader API",
		openapi:    "3.0.0",
	},
	{
		providerID: "jina-ai",
		artifactID: "jina-search-openapi",
		kind:       "openapi",
		url:        "https://s.jina.ai/openapi.json",
		path:       "openapi/jina-search-openapi.json",
		title:      "Jina Search API",
		openapi:    "3.0.0",
	},
	{
		providerID: "openai",
		artifactID: "openai-api-openapi",
		kind:       "openapi",
		url:        "https://app.stainless.com/api/spec/documented/openai/openapi.documented.yml",
		path:       "openapi/openai-api-openapi.documented.yml",
		title:      "OpenAI API",
		openapi:    "3.1.0",
	},
	{
		providerID: "perplexity",
		artifactID: "perplexity-api-openapi",
		kind:       "openapi",
		url:        "https://docs.perplexity.ai/openapi.json",
		path:       "openapi/perplexity-api-openapi.json",
		title:      "Perplexity AI API",
		openapi:    "3.1.0",
	},
	{
		providerID: "peekalink",
		artifactID: "peekalink-api-openapi",
		kind:       "openapi",
		url:        "https://api.peekalink.io/mintlify",
		path:       "openapi/peekalink-api-openapi.json",
		title:      "Peekalink",
		openapi:    "3.0.3",
	},
	{
		providerID: "signl4",
		artifactID: "signl4-api-v1-openapi",
		kind:       "openapi",
		url:        "https://connect.signl4.com/api/docs/v1/swagger.json",
		path:       "openapi/signl4-api-v1-openapi.json",
		title:      "SIGNL4 API V1",
		openapi:    "3.0.4",
	},
	{
		providerID: "vonage",
		artifactID: "vonage-messages-api-openapi",
		kind:       "openapi",
		url:        "https://developer.vonage.com/api/v1/developer/api/file/messages?format=yml&vendorId=vonage",
		path:       "openapi/vonage-messages-api-openapi.yml",
		title:      "Messages API",
		openapi:    "3.0.3",
	},
	{
		providerID: "zulip",
		artifactID: "zulip-rest-api-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/zulip/zulip/main/zerver/openapi/zulip.yaml",
		path:       "openapi/zulip-rest-api-openapi.yaml",
		title:      "Zulip REST API",
		openapi:    "3.0.1",
	},
	{
		providerID: "gotify",
		artifactID: "gotify-server-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/gotify/server/master/docs/spec.json",
		path:       "openapi/gotify-server-openapi.json",
		title:      "Gotify REST-API.",
		swagger:    "2.0",
	},
	{
		providerID: "spotify",
		artifactID: "spotify-web-api-openapi",
		kind:       "openapi",
		url:        "https://developer.spotify.com/reference/web-api/open-api-schema.yaml",
		path:       "openapi/spotify-web-api-openapi.yaml",
		title:      "Spotify Web API",
		openapi:    "3.0.3",
	},
	{
		providerID: "toggl",
		artifactID: "toggl-track-api-swagger",
		kind:       "openapi",
		url:        "https://engineering.toggl.com/assets/files/api-e95bb70f0fdd53fbd754f1dcf1041a9f.json",
		path:       "openapi/toggl-track-api-swagger.json",
		title:      "Toggl API",
		swagger:    "2.0",
	},
	{
		providerID: "oura",
		artifactID: "oura-api-v2-openapi",
		kind:       "openapi",
		url:        "https://cloud.ouraring.com/v2/static/json/openapi-1.29.json",
		path:       "openapi/oura-api-v2-openapi.json",
		title:      "Oura API",
		openapi:    "3.1.0",
	},
	{
		providerID: "syncromsp",
		artifactID: "syncromsp-api-openapi",
		kind:       "openapi",
		url:        "https://api-docs.syncromsp.com/swagger.json",
		path:       "openapi/syncromsp-api-openapi.json",
		title:      "Syncro",
		openapi:    "3.0.0",
		status:     apitools.CatalogRefreshInvalid,
	},
	{
		providerID: "thehive",
		artifactID: "thehive-api-v4-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/TheHive-Project/api-docs/master/thehive.yaml",
		path:       "openapi/thehive-api-v4-openapi.yaml",
		title:      "TheHive",
		openapi:    "3.0.0",
	},
	{
		providerID: "thehive-project",
		artifactID: "thehive-project-api-v5-openapi",
		kind:       "openapi",
		url:        "https://docs.strangebee.com/thehive/api-docs/docs.yaml",
		path:       "openapi/thehive-project-api-v5-openapi.yaml",
		title:      "TheHive",
		openapi:    "3.1.0",
	},
	{
		providerID: "egoi",
		artifactID: "egoi-marketing-api-v3-openapi",
		kind:       "openapi",
		url:        "https://api.egoiapp.com/openapi",
		path:       "openapi/egoi-marketing-api-v3-openapi.json",
		title:      "Marketing API",
		openapi:    "3.0.0",
	},
	{
		providerID: "mailcheck",
		artifactID: "mailcheck-api-openapi",
		kind:       "openapi",
		url:        "https://app.mailcheck.co/openapi.json",
		path:       "openapi/mailcheck-api-openapi.json",
		title:      "mailcheck",
		openapi:    "3.0.3",
	},
	{
		providerID: "nextcloud",
		artifactID: "nextcloud-server-openapi",
		kind:       "openapi",
		url:        "https://docs.nextcloud.com/server/latest/developer_manual/_static/openapi.json",
		path:       "openapi/nextcloud-server-openapi.json",
		title:      "nextcloud",
		openapi:    "3.0.3",
	},
	{
		providerID: "nvidia-dsx-air",
		artifactID: "nvidia-dsx-air-openapi",
		kind:       "openapi",
		url:        "https://dsx-air.nvidia.com/api/schema/",
		path:       "openapi/nvidia-dsx-air-openapi.yaml",
		title:      "NVIDIA Air API",
		openapi:    "3.0.3",
	},
	{
		providerID: "strava",
		artifactID: "strava-api-v3-swagger",
		kind:       "openapi",
		url:        "https://developers.strava.com/swagger/swagger.json",
		path:       "openapi/strava-api-v3-swagger.json",
		title:      "Strava API v3",
		swagger:    "2.0",
	},
	{
		providerID: "zoho",
		artifactID: "zoho-crm-v8-apis-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/zoho/crm-oas/main/v8.0/apis.json",
		path:       "openapi/zoho-crm-v8-apis-openapi.json",
		title:      "Available Apis",
		openapi:    "3.1.0",
	},
	{
		providerID: "zoho",
		artifactID: "zoho-crm-v8-records-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/zoho/crm-oas/main/v8.0/record.json",
		path:       "openapi/zoho-crm-v8-records-openapi.json",
		title:      "Records",
		openapi:    "3.1.0",
	},
	{
		providerID: "zoho",
		artifactID: "zoho-crm-v8-modules-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/zoho/crm-oas/main/v8.0/modules.json",
		path:       "openapi/zoho-crm-v8-modules-openapi.json",
		title:      "Modules",
		openapi:    "3.1.0",
	},
	{
		providerID: "zoho",
		artifactID: "zoho-crm-v8-fields-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/zoho/crm-oas/main/v8.0/fields.json",
		path:       "openapi/zoho-crm-v8-fields-openapi.json",
		title:      "Fields API",
		openapi:    "3.1.0",
	},
	{
		providerID: "zoho",
		artifactID: "zoho-crm-v8-users-openapi",
		kind:       "openapi",
		url:        "https://raw.githubusercontent.com/zoho/crm-oas/main/v8.0/users.json",
		path:       "openapi/zoho-crm-v8-users-openapi.json",
		title:      "Users API",
		openapi:    "3.1.0",
		status:     apitools.CatalogRefreshParseableOpenAPIInvalid,
	},
}

var overlayArtifacts = []overlayArtifact{
	{
		providerID:  "action-network",
		artifactID:  "action-network-api-v2-overlay",
		path:        "advisory-overlays/action-network-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://actionnetwork.org/docs/v2/",
	},
	{
		providerID:  "adalo",
		artifactID:  "adalo-api-overlay",
		path:        "advisory-overlays/adalo-api-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://help.adalo.com/integrations/the-adalo-api",
	},
	{
		providerID:  "affinity",
		artifactID:  "affinity-v1-api-overlay",
		path:        "advisory-overlays/affinity-v1-api-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://api-docs.affinity.co/",
	},
	{
		providerID:  "agile-crm",
		artifactID:  "agile-crm-rest-api-overlay",
		path:        "advisory-overlays/agile-crm-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://github.com/agilecrm/rest-api",
	},
	{
		providerID:  "acuity-scheduling",
		artifactID:  "acuity-scheduling-api-v1-overlay",
		path:        "advisory-overlays/acuity-scheduling-api-v1-overlay.json",
		builderPath: "overlay-builders/build_m22_human_docs_overlays.go",
		sourceURL:   "https://developers.acuityscheduling.com/reference",
	},
	{
		providerID:  "activecampaign",
		artifactID:  "activecampaign-api-v3-overlay",
		path:        "advisory-overlays/activecampaign-api-v3-overlay.json",
		builderPath: "overlay-builders/build_m21_human_docs_overlays.go",
		sourceURL:   "https://developers.activecampaign.com/reference/overview",
	},
	{
		providerID:  "airtable",
		artifactID:  "airtable-web-api-overlay",
		path:        "advisory-overlays/airtable-web-api-overlay.json",
		builderPath: "overlay-builders/build_airtable_overlay.go",
		sourceURL:   "https://airtable.com/developers/web/api/introduction",
	},
	{
		providerID:  "adobe-acrobat-sign",
		artifactID:  "adobe-acrobat-sign-api-overlay",
		path:        "advisory-overlays/adobe-acrobat-sign-api-overlay.json",
		builderPath: "overlay-builders/build_m57_human_docs_overlays.go",
		sourceURL:   "https://developer.adobe.com/acrobat-sign/docs/overview/sdks/openapi",
	},
	{
		providerID:  "aftership",
		artifactID:  "aftership-tracking-api-overlay",
		path:        "advisory-overlays/aftership-tracking-api-overlay.json",
		builderPath: "overlay-builders/build_m57_human_docs_overlays.go",
		sourceURL:   "https://www.aftership.com/docs/tracking",
	},
	{
		providerID:  "aircall",
		artifactID:  "aircall-public-api-overlay",
		path:        "advisory-overlays/aircall-public-api-overlay.json",
		builderPath: "overlay-builders/build_m57_human_docs_overlays.go",
		sourceURL:   "https://developer.aircall.io/api-references/",
	},
	{
		providerID:  "apollo",
		artifactID:  "apollo-api-overlay",
		path:        "advisory-overlays/apollo-api-overlay.json",
		builderPath: "overlay-builders/build_m57_human_docs_overlays.go",
		sourceURL:   "https://docs.apollo.io/llms.txt",
	},
	{
		providerID:  "checkr",
		artifactID:  "checkr-api-overlay",
		path:        "advisory-overlays/checkr-api-overlay.json",
		builderPath: "overlay-builders/build_m57_human_docs_overlays.go",
		sourceURL:   "https://docs.checkr.com/",
	},
	{
		providerID:  "marketo",
		artifactID:  "marketo-rest-api-overlay",
		path:        "advisory-overlays/marketo-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m57_human_docs_overlays.go",
		sourceURL:   "https://experienceleague.adobe.com/en/docs/marketo-developer/marketo/rest/rest-api",
	},
	{
		providerID:  "bamboohr",
		artifactID:  "bamboohr-api-v1-overlay",
		path:        "advisory-overlays/bamboohr-api-v1-overlay.json",
		builderPath: "overlay-builders/build_m21_human_docs_overlays.go",
		sourceURL:   "https://documentation.bamboohr.com/docs",
	},
	{
		providerID:  "bannerbear",
		artifactID:  "bannerbear-api-v2-overlay",
		path:        "advisory-overlays/bannerbear-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://developers.bannerbear.com/v2/",
	},
	{
		providerID:  "beeminder",
		artifactID:  "beeminder-api-v1-overlay",
		path:        "advisory-overlays/beeminder-api-v1-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://api.beeminder.com/",
	},
	{
		providerID:  "calendly",
		artifactID:  "calendly-public-api-overlay",
		path:        "advisory-overlays/calendly-public-api-overlay.json",
		builderPath: "overlay-builders/build_calendly_overlay.go",
		sourceURL:   "https://developer.calendly.com/api-docs",
	},
	{
		providerID:  "clockify",
		artifactID:  "clockify-api-v1-overlay",
		path:        "advisory-overlays/clockify-api-v1-overlay.json",
		builderPath: "overlay-builders/build_m22_human_docs_overlays.go",
		sourceURL:   "https://docs.clockify.me/",
	},
	{
		providerID:  "clearbit",
		artifactID:  "clearbit-api-overlay",
		path:        "advisory-overlays/clearbit-api-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://help.clearbit.com/hc/en-us/categories/360000913214-APIs",
	},
	{
		providerID:  "contentful",
		artifactID:  "contentful-management-api-overlay",
		path:        "advisory-overlays/contentful-management-api-overlay.json",
		builderPath: "overlay-builders/build_m21_human_docs_overlays.go",
		sourceURL:   "https://www.contentful.com/developers/docs/references/content-management-api/",
	},
	{
		providerID:  "copper",
		artifactID:  "copper-developer-api-overlay",
		path:        "advisory-overlays/copper-developer-api-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://developer.copper.com/",
	},
	{
		providerID:  "databricks",
		artifactID:  "databricks-workspace-rest-overlay",
		path:        "advisory-overlays/databricks-workspace-rest-overlay.json",
		builderPath: "overlay-builders/build_m20_human_docs_overlays.go",
		sourceURL:   "https://docs.databricks.com/api/workspace/introduction",
	},
	{
		providerID:  "dropbox",
		artifactID:  "dropbox-core-api-overlay",
		path:        "advisory-overlays/dropbox-core-api-overlay.json",
		builderPath: "overlay-builders/build_dropbox_overlay.go",
		sourceURL:   "https://github.com/dropbox/dropbox-api-spec",
		metadata: map[string]string{
			"derived_from_official_machine_spec": "true",
			"source_protocol":                    "dropbox-stone",
		},
	},
	{
		providerID:  "eventbrite",
		artifactID:  "eventbrite-platform-api-v3-overlay",
		path:        "advisory-overlays/eventbrite-platform-api-v3-overlay.json",
		builderPath: "overlay-builders/build_m21_human_docs_overlays.go",
		sourceURL:   "https://www.eventbrite.com/platform/api",
	},
	{
		providerID:  "freshdesk",
		artifactID:  "freshdesk-api-v2-overlay",
		path:        "advisory-overlays/freshdesk-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m21_human_docs_overlays.go",
		sourceURL:   "https://developers.freshdesk.com/api",
	},
	{
		providerID:  "freshservice",
		artifactID:  "freshservice-api-v2-overlay",
		path:        "advisory-overlays/freshservice-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://api.freshservice.com/",
	},
	{
		providerID:  "ghost",
		artifactID:  "ghost-admin-api-overlay",
		path:        "advisory-overlays/ghost-admin-api-overlay.json",
		builderPath: "overlay-builders/build_m22_human_docs_overlays.go",
		sourceURL:   "https://docs.ghost.org/admin-api/",
	},
	{
		providerID:  "grist",
		artifactID:  "grist-rest-api-overlay",
		path:        "advisory-overlays/grist-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://support.getgrist.com/rest-api/",
	},
	{
		providerID:  "gong",
		artifactID:  "gong-public-api-overlay",
		path:        "advisory-overlays/gong-public-api-overlay.json",
		builderPath: "overlay-builders/build_m23_human_docs_overlays.go",
		sourceURL:   "https://help.gong.io/docs/what-the-gong-api-provides",
	},
	{
		providerID:  "harvest",
		artifactID:  "harvest-api-v2-overlay",
		path:        "advisory-overlays/harvest-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m22_human_docs_overlays.go",
		sourceURL:   "https://help.getharvest.com/api-v2/",
	},
	{
		providerID:  "help-scout",
		artifactID:  "help-scout-inbox-api-v2-overlay",
		path:        "advisory-overlays/help-scout-inbox-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m22_human_docs_overlays.go",
		sourceURL:   "https://developer.helpscout.com/mailbox-api/",
	},
	{
		providerID:  "google-calendar",
		artifactID:  "google-calendar-v3-overlay",
		path:        "advisory-overlays/google-calendar-v3-overlay.json",
		builderPath: "overlay-builders/build_google_calendar_overlay.go",
		sourceURL:   "https://developers.google.com/workspace/calendar/api/v3/reference",
	},
	{
		providerID:  "google-sheets",
		artifactID:  "google-sheets-v4-overlay",
		path:        "advisory-overlays/google-sheets-v4-overlay.json",
		builderPath: "overlay-builders/build_google_sheets_overlay.go",
		sourceURL:   "https://developers.google.com/workspace/sheets/api/reference/rest",
	},
	{
		providerID:  "jenkins",
		artifactID:  "jenkins-remote-api-overlay",
		path:        "advisory-overlays/jenkins-remote-api-overlay.json",
		builderPath: "overlay-builders/build_m20_human_docs_overlays.go",
		sourceURL:   "https://www.jenkins.io/doc/book/using/remote-access-api/",
	},
	{
		providerID:  "mailchimp",
		artifactID:  "mailchimp-marketing-api-overlay",
		path:        "advisory-overlays/mailchimp-marketing-api-overlay.json",
		builderPath: "overlay-builders/build_mailchimp_overlay.go",
		sourceURL:   "https://mailchimp.com/developer/marketing/api/",
	},
	{
		providerID:  "iterable",
		artifactID:  "iterable-api-overlay",
		path:        "advisory-overlays/iterable-api-overlay.json",
		builderPath: "overlay-builders/build_m22_human_docs_overlays.go",
		sourceURL:   "https://api.iterable.com/api/docs",
	},
	{
		providerID:  "mailjet",
		artifactID:  "mailjet-rest-api-overlay",
		path:        "advisory-overlays/mailjet-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m22_human_docs_overlays.go",
		sourceURL:   "https://documentation.mailjet.com/hc/en-us/articles/360044088173-REST-API",
	},
	{
		providerID:  "coingecko",
		artifactID:  "coingecko-api-v3-overlay",
		path:        "advisory-overlays/coingecko-api-v3-overlay.json",
		builderPath: "overlay-builders/build_m24_human_docs_overlays.go",
		sourceURL:   "https://docs.coingecko.com/reference/introduction",
	},
	{
		providerID:  "hackernews",
		artifactID:  "hackernews-firebase-api-overlay",
		path:        "advisory-overlays/hackernews-firebase-api-overlay.json",
		builderPath: "overlay-builders/build_m24_human_docs_overlays.go",
		sourceURL:   "https://github.com/HackerNews/API",
	},
	{
		providerID:  "nasa",
		artifactID:  "nasa-open-apis-overlay",
		path:        "advisory-overlays/nasa-open-apis-overlay.json",
		builderPath: "overlay-builders/build_m24_human_docs_overlays.go",
		sourceURL:   "https://api.nasa.gov/",
	},
	{
		providerID:  "onesimpleapi",
		artifactID:  "onesimpleapi-toolkit-overlay",
		path:        "advisory-overlays/onesimpleapi-toolkit-overlay.json",
		builderPath: "overlay-builders/build_m24_human_docs_overlays.go",
		sourceURL:   "https://onesimpleapi.com/docs",
	},
	{
		providerID:  "openthesaurus",
		artifactID:  "openthesaurus-api-overlay",
		path:        "advisory-overlays/openthesaurus-api-overlay.json",
		builderPath: "overlay-builders/build_m24_human_docs_overlays.go",
		sourceURL:   "https://www.openthesaurus.de/about/api",
	},
	{
		providerID:  "openweathermap",
		artifactID:  "openweathermap-one-call-3-overlay",
		path:        "advisory-overlays/openweathermap-one-call-3-overlay.json",
		builderPath: "overlay-builders/build_openweathermap_overlay.go",
		sourceURL:   "https://openweathermap.org/api/one-call-3?collection=one_call_api_3.0",
	},
	{
		providerID:  "postmark",
		artifactID:  "postmark-api-overlay",
		path:        "advisory-overlays/postmark-api-overlay.json",
		builderPath: "overlay-builders/build_m21_human_docs_overlays.go",
		sourceURL:   "https://postmarkapp.com/developer/api/overview",
	},
	{
		providerID:  "quickbooks",
		artifactID:  "quickbooks-online-accounting-api-overlay",
		path:        "advisory-overlays/quickbooks-online-accounting-api-overlay.json",
		builderPath: "overlay-builders/build_quickbooks_overlay.go",
		sourceURL:   "https://developer.intuit.com/app/developer/qbo/docs/learn/explore-the-quickbooks-online-api",
	},
	{
		providerID:  "quickchart",
		artifactID:  "quickchart-api-overlay",
		path:        "advisory-overlays/quickchart-api-overlay.json",
		builderPath: "overlay-builders/build_m24_human_docs_overlays.go",
		sourceURL:   "https://quickchart.io/documentation/",
	},
	{
		providerID:  "reddit",
		artifactID:  "reddit-api-overlay",
		path:        "advisory-overlays/reddit-api-overlay.json",
		builderPath: "overlay-builders/build_m24_human_docs_overlays.go",
		sourceURL:   "https://www.reddit.com/dev/api/",
	},
	{
		providerID:  "autopilot",
		artifactID:  "autopilot-api-overlay",
		path:        "advisory-overlays/autopilot-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://autopilot.docs.apiary.io/",
	},
	{
		providerID:  "drift",
		artifactID:  "drift-platform-api-overlay",
		path:        "advisory-overlays/drift-platform-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://devdocs.drift.com/docs/platform-apis",
	},
	{
		providerID:  "freshworks-crm",
		artifactID:  "freshworks-crm-api-overlay",
		path:        "advisory-overlays/freshworks-crm-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://developers.freshworks.com/crm/api/",
	},
	{
		providerID:  "getresponse",
		artifactID:  "getresponse-api-v3-overlay",
		path:        "advisory-overlays/getresponse-api-v3-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://apidocs.getresponse.com/v3",
	},
	{
		providerID:  "keap",
		artifactID:  "keap-rest-api-overlay",
		path:        "advisory-overlays/keap-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://developer.keap.com/docs/rest/1000/",
	},
	{
		providerID:  "mailerlite",
		artifactID:  "mailerlite-api-overlay",
		path:        "advisory-overlays/mailerlite-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://developers.mailerlite.com/docs/",
	},
	{
		providerID:  "mautic",
		artifactID:  "mautic-api-overlay",
		path:        "advisory-overlays/mautic-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://developer.mautic.org/",
	},
	{
		providerID:  "monica-crm",
		artifactID:  "monica-crm-api-overlay",
		path:        "advisory-overlays/monica-crm-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://www.monicahq.com/api",
	},
	{
		providerID:  "salesmate",
		artifactID:  "salesmate-api-overlay",
		path:        "advisory-overlays/salesmate-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://apidocs.salesmate.io/",
	},
	{
		providerID:  "sendy",
		artifactID:  "sendy-api-overlay",
		path:        "advisory-overlays/sendy-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://sendy.co/api",
	},
	{
		providerID:  "vero",
		artifactID:  "vero-track-api-overlay",
		path:        "advisory-overlays/vero-track-api-overlay.json",
		builderPath: "overlay-builders/build_m25_human_docs_overlays.go",
		sourceURL:   "https://help.getvero.com/api-reference/track/overview",
	},
	{
		providerID:  "jotform",
		artifactID:  "jotform-api-overlay",
		path:        "advisory-overlays/jotform-api-overlay.json",
		builderPath: "overlay-builders/build_m26_human_docs_overlays.go",
		sourceURL:   "https://api.jotform.com/docs/",
	},
	{
		providerID:  "formio",
		artifactID:  "formio-api-overlay",
		path:        "advisory-overlays/formio-api-overlay.json",
		builderPath: "overlay-builders/build_m26_human_docs_overlays.go",
		sourceURL:   "https://help.form.io/developers/introduction/api-documentation",
	},
	{
		providerID:  "formstack",
		artifactID:  "formstack-api-v2-overlay",
		path:        "advisory-overlays/formstack-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m26_human_docs_overlays.go",
		sourceURL:   "https://developers.formstack.com/v2.0/reference/api-overview",
	},
	{
		providerID:  "surveymonkey",
		artifactID:  "surveymonkey-api-v3-overlay",
		path:        "advisory-overlays/surveymonkey-api-v3-overlay.json",
		builderPath: "overlay-builders/build_m26_human_docs_overlays.go",
		sourceURL:   "https://api.surveymonkey.com/v3/docs",
	},
	{
		providerID:  "bubble",
		artifactID:  "bubble-api-overlay",
		path:        "advisory-overlays/bubble-api-overlay.json",
		builderPath: "overlay-builders/build_m26_human_docs_overlays.go",
		sourceURL:   "https://manual.bubble.io/help-guides/integrations/api/the-bubble-api",
	},
	{
		providerID:  "cockpit",
		artifactID:  "cockpit-api-overlay",
		path:        "advisory-overlays/cockpit-api-overlay.json",
		builderPath: "overlay-builders/build_m26_human_docs_overlays.go",
		sourceURL:   "https://getcockpit.com/documentation/core/api",
	},
	{
		providerID:  "stackby",
		artifactID:  "stackby-api-overlay",
		path:        "advisory-overlays/stackby-api-overlay.json",
		builderPath: "overlay-builders/build_m26_human_docs_overlays.go",
		sourceURL:   "https://help.stackby.com/en/articles/29-developer-api",
	},
	{
		providerID:  "filemaker",
		artifactID:  "filemaker-data-api-overlay",
		path:        "advisory-overlays/filemaker-data-api-overlay.json",
		builderPath: "overlay-builders/build_m26_human_docs_overlays.go",
		sourceURL:   "https://help.claris.com/en/data-api-guide/content/data-api-reference.html",
	},
	{
		providerID:  "facebook",
		artifactID:  "facebook-graph-api-overlay",
		path:        "advisory-overlays/facebook-graph-api-overlay.json",
		builderPath: "overlay-builders/build_m27_human_docs_overlays.go",
		sourceURL:   "https://developers.facebook.com/docs/graph-api/",
	},
	{
		providerID:  "facebook-lead-ads",
		artifactID:  "facebook-lead-ads-overlay",
		path:        "advisory-overlays/facebook-lead-ads-overlay.json",
		builderPath: "overlay-builders/build_m27_human_docs_overlays.go",
		sourceURL:   "https://developers.facebook.com/docs/marketing-api/guides/lead-ads/retrieving/",
	},
	{
		providerID:  "linkedin",
		artifactID:  "linkedin-api-overlay",
		path:        "advisory-overlays/linkedin-api-overlay.json",
		builderPath: "overlay-builders/build_m27_human_docs_overlays.go",
		sourceURL:   "https://learn.microsoft.com/en-us/linkedin/marketing/",
	},
	{
		providerID:  "messagebird",
		artifactID:  "messagebird-api-overlay",
		path:        "advisory-overlays/messagebird-api-overlay.json",
		builderPath: "overlay-builders/build_m27_human_docs_overlays.go",
		sourceURL:   "https://developers.messagebird.com/api/",
	},
	{
		providerID:  "twake",
		artifactID:  "twake-developers-api-overlay",
		path:        "advisory-overlays/twake-developers-api-overlay.json",
		builderPath: "overlay-builders/build_m27_human_docs_overlays.go",
		sourceURL:   "https://doc.twake.app/developers-api/get-started",
	},
	{
		providerID:  "twist",
		artifactID:  "twist-api-v3-overlay",
		path:        "advisory-overlays/twist-api-v3-overlay.json",
		builderPath: "overlay-builders/build_m27_human_docs_overlays.go",
		sourceURL:   "https://developer.twist.com/v3/",
	},
	{
		providerID:  "whatsapp",
		artifactID:  "whatsapp-cloud-api-overlay",
		path:        "advisory-overlays/whatsapp-cloud-api-overlay.json",
		builderPath: "overlay-builders/build_m27_human_docs_overlays.go",
		sourceURL:   "https://developers.facebook.com/docs/whatsapp/cloud-api/",
	},
	{
		providerID:  "magento",
		artifactID:  "magento-rest-api-overlay",
		path:        "advisory-overlays/magento-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://developer.adobe.com/commerce/webapi/rest/reference/",
	},
	{
		providerID:  "gumroad",
		artifactID:  "gumroad-api-overlay",
		path:        "advisory-overlays/gumroad-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://gumroad.com/api",
	},
	{
		providerID:  "invoice-ninja",
		artifactID:  "invoice-ninja-api-overlay",
		path:        "advisory-overlays/invoice-ninja-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://api-docs.invoicing.co/",
	},
	{
		providerID:  "erpnext",
		artifactID:  "erpnext-rest-api-overlay",
		path:        "advisory-overlays/erpnext-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://docs.frappe.io/erpnext/rest-api",
	},
	{
		providerID:  "woocommerce",
		artifactID:  "woocommerce-rest-api-overlay",
		path:        "advisory-overlays/woocommerce-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://developer.woocommerce.com/docs/apis/rest-api/v3/",
	},
	{
		providerID:  "wise",
		artifactID:  "wise-platform-api-overlay",
		path:        "advisory-overlays/wise-platform-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://docs.wise.com/api-reference",
	},
	{
		providerID:  "dhl",
		artifactID:  "dhl-shipment-tracking-overlay",
		path:        "advisory-overlays/dhl-shipment-tracking-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://developer.dhl.com/api-reference/shipment-tracking?language_content_entity=en",
	},
	{
		providerID:  "onfleet",
		artifactID:  "onfleet-api-overlay",
		path:        "advisory-overlays/onfleet-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://docs.onfleet.com/reference",
	},
	{
		providerID:  "unleashed-software",
		artifactID:  "unleashed-software-api-overlay",
		path:        "advisory-overlays/unleashed-software-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://apidocs.unleashedsoftware.com/",
	},
	{
		providerID:  "workable",
		artifactID:  "workable-api-overlay",
		path:        "advisory-overlays/workable-api-overlay.json",
		builderPath: "overlay-builders/build_m28_human_docs_overlays.go",
		sourceURL:   "https://workable.readme.io/reference",
	},
	{
		providerID:  "bitwarden",
		artifactID:  "bitwarden-public-api-overlay",
		path:        "advisory-overlays/bitwarden-public-api-overlay.json",
		builderPath: "overlay-builders/build_m29_human_docs_overlays.go",
		sourceURL:   "https://bitwarden.com/help/api/",
	},
	{
		providerID:  "cisco-webex",
		artifactID:  "cisco-webex-api-overlay",
		path:        "advisory-overlays/cisco-webex-api-overlay.json",
		builderPath: "overlay-builders/build_m29_human_docs_overlays.go",
		sourceURL:   "https://developer.webex.com/docs/api/v1/rooms",
	},
	{
		providerID:  "cortex",
		artifactID:  "cortex-api-overlay",
		path:        "advisory-overlays/cortex-api-overlay.json",
		builderPath: "overlay-builders/build_m29_human_docs_overlays.go",
		sourceURL:   "https://docs.strangebee.com/cortex/api/api-guide/",
	},
	{
		providerID:  "home-assistant",
		artifactID:  "home-assistant-rest-api-overlay",
		path:        "advisory-overlays/home-assistant-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m29_human_docs_overlays.go",
		sourceURL:   "https://developers.home-assistant.io/docs/api/rest/",
	},
	{
		providerID:  "netscaler",
		artifactID:  "netscaler-adc-nitro-api-overlay",
		path:        "advisory-overlays/netscaler-adc-nitro-api-overlay.json",
		builderPath: "overlay-builders/build_m29_human_docs_overlays.go",
		sourceURL:   "https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/api-reference.html",
	},
	{
		providerID:  "venafi",
		artifactID:  "venafi-api-overlay",
		path:        "advisory-overlays/venafi-api-overlay.json",
		builderPath: "overlay-builders/build_m29_human_docs_overlays.go",
		sourceURL:   "https://developer.venafi.com/tlsprotectcloud/reference",
	},
	{
		providerID:  "wekan",
		artifactID:  "wekan-rest-api-overlay",
		path:        "advisory-overlays/wekan-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m29_human_docs_overlays.go",
		sourceURL:   "https://github.com/wekan/wekan/wiki/REST-API",
	},
	{
		providerID:  "zammad",
		artifactID:  "zammad-api-overlay",
		path:        "advisory-overlays/zammad-api-overlay.json",
		builderPath: "overlay-builders/build_m29_human_docs_overlays.go",
		sourceURL:   "https://docs.zammad.org/en/latest/api/intro.html",
	},
	{
		providerID:  "humantic-ai",
		artifactID:  "humantic-ai-api-overlay",
		path:        "advisory-overlays/humantic-ai-api-overlay.json",
		builderPath: "overlay-builders/build_m30_human_docs_overlays.go",
		sourceURL:   "https://api.humantic.ai/",
	},
	{
		providerID:  "hunter",
		artifactID:  "hunter-api-overlay",
		path:        "advisory-overlays/hunter-api-overlay.json",
		builderPath: "overlay-builders/build_m30_human_docs_overlays.go",
		sourceURL:   "https://hunter.io/api-documentation",
	},
	{
		providerID:  "lingvanex",
		artifactID:  "lingvanex-api-overlay",
		path:        "advisory-overlays/lingvanex-api-overlay.json",
		builderPath: "overlay-builders/build_m30_human_docs_overlays.go",
		sourceURL:   "https://docs.lingvanex.com/reference/user-guide",
	},
	{
		providerID:  "mistral-ai",
		artifactID:  "mistral-ai-api-overlay",
		path:        "advisory-overlays/mistral-ai-api-overlay.json",
		builderPath: "overlay-builders/build_m30_human_docs_overlays.go",
		sourceURL:   "https://docs.mistral.ai/api",
	},
	{
		providerID:  "mindee",
		artifactID:  "mindee-api-overlay",
		path:        "advisory-overlays/mindee-api-overlay.json",
		builderPath: "overlay-builders/build_m30_human_docs_overlays.go",
		sourceURL:   "https://docs.mindee.com/integrations/api-overview",
	},
	{
		providerID:  "phantombuster",
		artifactID:  "phantombuster-api-overlay",
		path:        "advisory-overlays/phantombuster-api-overlay.json",
		builderPath: "overlay-builders/build_m30_human_docs_overlays.go",
		sourceURL:   "https://hub.phantombuster.com/docs/api",
	},
	{
		providerID:  "uplead",
		artifactID:  "uplead-api-overlay",
		path:        "advisory-overlays/uplead-api-overlay.json",
		builderPath: "overlay-builders/build_m30_human_docs_overlays.go",
		sourceURL:   "https://docs.uplead.com/",
	},
	{
		providerID:  "dropcontact",
		artifactID:  "dropcontact-api-overlay",
		path:        "advisory-overlays/dropcontact-api-overlay.json",
		builderPath: "overlay-builders/build_m30_human_docs_overlays.go",
		sourceURL:   "https://developer.dropcontact.com/",
	},
	{
		providerID:  "mocean",
		artifactID:  "mocean-api-overlay",
		path:        "advisory-overlays/mocean-api-overlay.json",
		builderPath: "overlay-builders/build_m31_human_docs_overlays.go",
		sourceURL:   "https://moceanapi.com/docs",
	},
	{
		providerID:  "msg91",
		artifactID:  "msg91-api-overlay",
		path:        "advisory-overlays/msg91-api-overlay.json",
		builderPath: "overlay-builders/build_m31_human_docs_overlays.go",
		sourceURL:   "https://docs.msg91.com/sms",
	},
	{
		providerID:  "plivo",
		artifactID:  "plivo-api-overlay",
		path:        "advisory-overlays/plivo-api-overlay.json",
		builderPath: "overlay-builders/build_m31_human_docs_overlays.go",
		sourceURL:   "https://www.plivo.com/docs/messaging/api/message/retrieve-a-message",
	},
	{
		providerID:  "pushbullet",
		artifactID:  "pushbullet-api-overlay",
		path:        "advisory-overlays/pushbullet-api-overlay.json",
		builderPath: "overlay-builders/build_m31_human_docs_overlays.go",
		sourceURL:   "https://docs.pushbullet.com/",
	},
	{
		providerID:  "pushcut",
		artifactID:  "pushcut-api-overlay",
		path:        "advisory-overlays/pushcut-api-overlay.json",
		builderPath: "overlay-builders/build_m31_human_docs_overlays.go",
		sourceURL:   "https://www.pushcut.io/support/integrations",
	},
	{
		providerID:  "pushover",
		artifactID:  "pushover-api-overlay",
		path:        "advisory-overlays/pushover-api-overlay.json",
		builderPath: "overlay-builders/build_m31_human_docs_overlays.go",
		sourceURL:   "https://pushover.net/api",
	},
	{
		providerID:  "sms77",
		artifactID:  "sms77-api-overlay",
		path:        "advisory-overlays/sms77-api-overlay.json",
		builderPath: "overlay-builders/build_m31_human_docs_overlays.go",
		sourceURL:   "https://docs.seven.io/en/rest-api/endpoints/sms",
	},
	{
		providerID:  "disqus",
		artifactID:  "disqus-api-overlay",
		path:        "advisory-overlays/disqus-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://disqus.com/api/docs/",
	},
	{
		providerID:  "medium",
		artifactID:  "medium-api-overlay",
		path:        "advisory-overlays/medium-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://github.com/Medium/medium-api-docs",
	},
	{
		providerID:  "npm",
		artifactID:  "npm-registry-api-overlay",
		path:        "advisory-overlays/npm-registry-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md",
	},
	{
		providerID:  "storyblok",
		artifactID:  "storyblok-api-overlay",
		path:        "advisory-overlays/storyblok-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://www.storyblok.com/docs/api/content-delivery/v2",
	},
	{
		providerID:  "strapi",
		artifactID:  "strapi-rest-api-overlay",
		path:        "advisory-overlays/strapi-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://docs.strapi.io/cms/api/rest",
	},
	{
		providerID:  "wordpress",
		artifactID:  "wordpress-rest-api-overlay",
		path:        "advisory-overlays/wordpress-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://developer.wordpress.org/rest-api/",
	},
	{
		providerID:  "wufoo",
		artifactID:  "wufoo-api-v3-overlay",
		path:        "advisory-overlays/wufoo-api-v3-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://www.wufoo.com/docs/api/v3/",
	},
	{
		providerID:  "yourls",
		artifactID:  "yourls-api-overlay",
		path:        "advisory-overlays/yourls-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://yourls.org/docs/guide/advanced/api",
	},
	{
		providerID:  "raindrop",
		artifactID:  "raindrop-api-overlay",
		path:        "advisory-overlays/raindrop-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://developer.raindrop.io/v1/",
	},
	{
		providerID:  "travis-ci",
		artifactID:  "travis-ci-api-overlay",
		path:        "advisory-overlays/travis-ci-api-overlay.json",
		builderPath: "overlay-builders/build_m32_human_docs_overlays.go",
		sourceURL:   "https://developer.travis-ci.com/",
	},
	{
		providerID:  "flow",
		artifactID:  "flow-api-overlay",
		path:        "advisory-overlays/flow-api-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://developer.getflow.com/api",
	},
	{
		providerID:  "gotowebinar",
		artifactID:  "gotowebinar-api-overlay",
		path:        "advisory-overlays/gotowebinar-api-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://developer.goto.com/GoToWebinarV2/",
	},
	{
		providerID:  "halopsa",
		artifactID:  "halopsa-api-overlay",
		path:        "advisory-overlays/halopsa-api-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://apidoc.halopsa.com/",
	},
	{
		providerID:  "lonescale",
		artifactID:  "lonescale-api-overlay",
		path:        "advisory-overlays/lonescale-api-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://help-center.lonescale.com/en/articles/6454360-lonescale-public-api",
	},
	{
		providerID:  "lemlist",
		artifactID:  "lemlist-api-overlay",
		path:        "advisory-overlays/lemlist-api-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://developer.lemlist.com/api-reference/getting-started/overview",
	},
	{
		providerID:  "profitwell",
		artifactID:  "profitwell-api-v2-overlay",
		path:        "advisory-overlays/profitwell-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://profitwellapiv2.docs.apiary.io/",
	},
	{
		providerID:  "quickbase",
		artifactID:  "quickbase-rest-api-overlay",
		path:        "advisory-overlays/quickbase-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://developer.quickbase.com/",
	},
	{
		providerID:  "taiga",
		artifactID:  "taiga-api-overlay",
		path:        "advisory-overlays/taiga-api-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://docs.taiga.io/api.html",
	},
	{
		providerID:  "tapfiliate",
		artifactID:  "tapfiliate-api-overlay",
		path:        "advisory-overlays/tapfiliate-api-overlay.json",
		builderPath: "overlay-builders/build_m33_human_docs_overlays.go",
		sourceURL:   "https://tapfiliate.com/docs/rest/",
	},
	{
		providerID:  "apitemplate-io",
		artifactID:  "apitemplate-io-api-overlay",
		path:        "advisory-overlays/apitemplate-io-api-overlay.json",
		builderPath: "overlay-builders/build_m34_human_docs_overlays.go",
		sourceURL:   "https://docs.apitemplate.io/api/index.html",
	},
	{
		providerID:  "currents",
		artifactID:  "currents-api-overlay",
		path:        "advisory-overlays/currents-api-overlay.json",
		builderPath: "overlay-builders/build_m34_human_docs_overlays.go",
		sourceURL:   "https://docs.currents.dev/api",
	},
	{
		providerID:  "demio",
		artifactID:  "demio-api-overlay",
		path:        "advisory-overlays/demio-api-overlay.json",
		builderPath: "overlay-builders/build_m34_human_docs_overlays.go",
		sourceURL:   "https://publicdemioapi.docs.apiary.io/",
	},
	{
		providerID:  "mandrill",
		artifactID:  "mandrill-transactional-api-overlay",
		path:        "advisory-overlays/mandrill-transactional-api-overlay.json",
		builderPath: "overlay-builders/build_m34_human_docs_overlays.go",
		sourceURL:   "https://mailchimp.com/developer/transactional/api/",
	},
	{
		providerID:  "metabase",
		artifactID:  "metabase-api-overlay",
		path:        "advisory-overlays/metabase-api-overlay.json",
		builderPath: "overlay-builders/build_m34_human_docs_overlays.go",
		sourceURL:   "https://www.metabase.com/docs/latest/api",
	},
	{
		providerID:  "salesforce",
		artifactID:  "salesforce-rest-core-overlay",
		path:        "advisory-overlays/salesforce-rest-core-overlay.json",
		builderPath: "overlay-builders/build_salesforce_overlay.go",
		sourceURL:   "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest.htm",
	},
	{
		providerID:  "sentry",
		artifactID:  "sentry-rest-api-overlay",
		path:        "advisory-overlays/sentry-rest-api-overlay.json",
		builderPath: "overlay-builders/build_m20_human_docs_overlays.go",
		sourceURL:   "https://docs.sentry.io/api/",
	},
	{
		providerID:  "servicenow",
		artifactID:  "servicenow-rest-api-overlay",
		path:        "advisory-overlays/servicenow-rest-api-overlay.json",
		builderPath: "overlay-builders/build_servicenow_overlay.go",
		sourceURL:   "https://www.servicenow.com/docs/r/api-reference/rest-api-explorer/c_RESTAPI.html",
	},
	{
		providerID:  "shopify",
		artifactID:  "shopify-admin-rest-overlay",
		path:        "advisory-overlays/shopify-admin-rest-overlay.json",
		builderPath: "overlay-builders/build_shopify_overlay.go",
		sourceURL:   "https://shopify.dev/docs/api/admin-rest",
	},
	{
		providerID:  "splunk",
		artifactID:  "splunk-enterprise-rest-overlay",
		path:        "advisory-overlays/splunk-enterprise-rest-overlay.json",
		builderPath: "overlay-builders/build_m20_human_docs_overlays.go",
		sourceURL:   "https://docs.splunk.com/Documentation/Splunk/latest/RESTREF",
	},
	{
		providerID:  "telegram",
		artifactID:  "telegram-bot-api-overlay",
		path:        "advisory-overlays/telegram-bot-api-overlay.json",
		builderPath: "overlay-builders/build_m20_human_docs_overlays.go",
		sourceURL:   "https://core.telegram.org/bots/api",
	},
	{
		providerID:  "todoist",
		artifactID:  "todoist-rest-api-v2-overlay",
		path:        "advisory-overlays/todoist-rest-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m21_human_docs_overlays.go",
		sourceURL:   "https://developer.todoist.com/rest/v2/",
	},
	{
		providerID:  "typeform",
		artifactID:  "typeform-rest-api-overlay",
		path:        "advisory-overlays/typeform-rest-api-overlay.json",
		builderPath: "overlay-builders/build_typeform_overlay.go",
		sourceURL:   "https://www.typeform.com/developers/get-started/",
	},
	{
		providerID:  "webflow",
		artifactID:  "webflow-data-api-v2-overlay",
		path:        "advisory-overlays/webflow-data-api-v2-overlay.json",
		builderPath: "overlay-builders/build_m21_human_docs_overlays.go",
		sourceURL:   "https://developers.webflow.com/data/reference",
	},
}
