// Command cataloggen validates the reviewed catalog JSON and generates the
// checked-in manifest and lookup indexes consumed by the catalog package.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/OpenUdon/apitools/catalog"
	"github.com/OpenUdon/apitools/internal/artifactio"
)

const manifestVersion = "apitools.catalog-manifest.v1"

type manifest struct {
	Version                     string `json:"version"`
	CatalogVersion              string `json:"catalog_version"`
	CatalogSHA256               string `json:"catalog_sha256"`
	CatalogBytes                int    `json:"catalog_bytes"`
	CandidateCount              int    `json:"candidate_count"`
	ProviderCount               int    `json:"provider_count"`
	SpecReferenceCount          int    `json:"spec_reference_count"`
	SecurityClassificationCount int    `json:"security_classification_count"`
	SecurityOverlayCount        int    `json:"security_overlay_count"`
}

type generatedOutputs struct {
	catalog  []byte
	manifest []byte
	goSource []byte
}

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, out io.Writer) error {
	fs := flag.NewFlagSet("cataloggen", flag.ContinueOnError)
	fs.SetOutput(out)
	root := fs.String("root", ".", "apitools repository root")
	check := fs.Bool("check", false, "verify checked-in outputs without writing")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return fmt.Errorf("unexpected argument %q", fs.Arg(0))
	}
	rootAbs, err := filepath.Abs(strings.TrimSpace(*root))
	if err != nil {
		return err
	}
	catalogPath := filepath.Join(rootAbs, "catalog", "data", "catalog.json")
	content, err := os.ReadFile(catalogPath)
	if err != nil {
		return err
	}
	generated, err := buildOutputs(content)
	if err != nil {
		return err
	}
	outputs := []struct {
		path string
		data []byte
	}{
		{path: filepath.Join("catalog", "data", "catalog.json"), data: generated.catalog},
		{path: filepath.Join("catalog", "data", "manifest.json"), data: generated.manifest},
		{path: filepath.Join("catalog", "catalog_gen.go"), data: generated.goSource},
	}
	if *check {
		for _, output := range outputs {
			current, err := os.ReadFile(filepath.Join(rootAbs, output.path))
			if err != nil {
				return fmt.Errorf("catalog generated output %s: %w", output.path, err)
			}
			if !bytes.Equal(current, output.data) {
				return fmt.Errorf("catalog generated output %s is stale; run go run ./cmd/cataloggen", output.path)
			}
		}
		fmt.Fprintln(out, "catalog generated outputs are current")
		return nil
	}
	for _, output := range outputs {
		if _, err := artifactio.WriteFile(rootAbs, output.path, output.data, artifactio.WriteOptions{Mode: 0o644, Force: true}); err != nil {
			return err
		}
	}
	fmt.Fprintln(out, "generated catalog/data/manifest.json and catalog/catalog_gen.go")
	return nil
}

func buildOutputs(content []byte) (generatedOutputs, error) {
	bundle, err := catalog.ParseCatalogBundle(content)
	if err != nil {
		return generatedOutputs{}, err
	}
	canonical, err := json.MarshalIndent(bundle, "", "  ")
	if err != nil {
		return generatedOutputs{}, err
	}
	canonical = append(canonical, '\n')
	digest := sha256.Sum256(canonical)
	digestText := hex.EncodeToString(digest[:])
	specCount := 0
	for _, provider := range bundle.Providers {
		specCount += len(provider.SpecReferences)
	}
	manifestValue := manifest{
		Version:                     manifestVersion,
		CatalogVersion:              bundle.Version,
		CatalogSHA256:               digestText,
		CatalogBytes:                len(canonical),
		CandidateCount:              len(bundle.Candidates),
		ProviderCount:               len(bundle.Providers),
		SpecReferenceCount:          specCount,
		SecurityClassificationCount: len(bundle.SecurityClassifications),
		SecurityOverlayCount:        len(bundle.SecurityOverlays),
	}
	manifestJSON, err := json.MarshalIndent(manifestValue, "", "  ")
	if err != nil {
		return generatedOutputs{}, err
	}
	manifestJSON = append(manifestJSON, '\n')
	goSource, err := generateGo(bundle, manifestValue)
	if err != nil {
		return generatedOutputs{}, err
	}
	return generatedOutputs{catalog: canonical, manifest: manifestJSON, goSource: goSource}, nil
}

func generateGo(bundle catalog.CatalogBundle, value manifest) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString("// Code generated by go run ./cmd/cataloggen; DO NOT EDIT.\n\n")
	builder.WriteString("package catalog\n\n")
	fmt.Fprintf(&builder, "const generatedCatalogManifestVersion = %s\n", strconv.Quote(value.Version))
	fmt.Fprintf(&builder, "const generatedCatalogSHA256 = %s\n", strconv.Quote(value.CatalogSHA256))
	fmt.Fprintf(&builder, "const generatedCatalogBytes = %d\n", value.CatalogBytes)
	fmt.Fprintf(&builder, "const generatedCandidateCount = %d\n", value.CandidateCount)
	fmt.Fprintf(&builder, "const generatedProviderCount = %d\n", value.ProviderCount)
	fmt.Fprintf(&builder, "const generatedSpecReferenceCount = %d\n", value.SpecReferenceCount)
	fmt.Fprintf(&builder, "const generatedSecurityClassificationCount = %d\n", value.SecurityClassificationCount)
	fmt.Fprintf(&builder, "const generatedSecurityOverlayCount = %d\n\n", value.SecurityOverlayCount)

	writeIndexMap(&builder, "generatedCandidateIndexByID", candidateIDs(bundle.Candidates))
	writeIndexMap(&builder, "generatedProviderIndexByID", providerIDs(bundle.Providers))
	writeGroupedIndexes(&builder, "generatedSecurityClassificationIndexesByProvider", classificationProviders(bundle.SecurityClassifications))
	writeGroupedIndexes(&builder, "generatedSecurityOverlayIndexesByProvider", overlayProviders(bundle.SecurityOverlays))

	formatted, err := format.Source([]byte(builder.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated catalog indexes: %w", err)
	}
	return formatted, nil
}

func writeIndexMap(builder *strings.Builder, name string, values []string) {
	fmt.Fprintf(builder, "var %s = map[string]int{\n", name)
	for index, value := range values {
		fmt.Fprintf(builder, "\t%s: %d,\n", strconv.Quote(value), index)
	}
	builder.WriteString("}\n\n")
}

func writeGroupedIndexes(builder *strings.Builder, name string, values []string) {
	grouped := map[string][]int{}
	for index, value := range values {
		grouped[value] = append(grouped[value], index)
	}
	keys := make([]string, 0, len(grouped))
	for key := range grouped {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	fmt.Fprintf(builder, "var %s = map[string][]int{\n", name)
	for _, key := range keys {
		fmt.Fprintf(builder, "\t%s: {", strconv.Quote(key))
		for index, value := range grouped[key] {
			if index > 0 {
				builder.WriteString(", ")
			}
			fmt.Fprint(builder, value)
		}
		builder.WriteString("},\n")
	}
	builder.WriteString("}\n\n")
}

func candidateIDs(values []catalog.Candidate) []string {
	out := make([]string, len(values))
	for index, value := range values {
		out[index] = value.ID
	}
	return out
}

func providerIDs(values []catalog.Provider) []string {
	out := make([]string, len(values))
	for index, value := range values {
		out[index] = value.ID
	}
	return out
}

func classificationProviders(values []catalog.SecurityClassification) []string {
	out := make([]string, len(values))
	for index, value := range values {
		out[index] = value.ProviderID
	}
	return out
}

func overlayProviders(values []catalog.SecurityOverlay) []string {
	out := make([]string, len(values))
	for index, value := range values {
		out[index] = value.ProviderID
	}
	return out
}
